/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountInsights : This is a container object for all lending-related insights. This field will be returned only for European customers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountInsights {
    #[serde(rename = "risk", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub risk: Option<Option<models::RiskIndicators>>,
    #[serde(rename = "affordability", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub affordability: Option<Option<models::AffordabilityInsights>>,
}

impl AccountInsights {
    /// This is a container object for all lending-related insights. This field will be returned only for European customers.
    pub fn new() -> AccountInsights {
        AccountInsights {
            risk: None,
            affordability: None,
        }
    }
}

