/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountAssets {
    /// Plaid’s unique identifier for the account. This value will not change unless Plaid can't reconcile the account with the data returned by the financial institution. This may occur, for example, when the name of the account changes. If this happens a new `account_id` will be assigned to the account.  The `account_id` can also change if the `access_token` is deleted and the same credentials that were used to generate that `access_token` are used to generate a new `access_token` on a later date. In that case, the new `account_id` will be different from the old `account_id`.  If an account with a specific `account_id` disappears instead of changing, the account is likely closed. Closed accounts are not returned by the Plaid API.  Like all Plaid identifiers, the `account_id` is case sensitive.
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "balances")]
    pub balances: models::AccountBalance,
    /// The last 2-4 alphanumeric characters of an account's official account number. Note that the mask may be non-unique between an Item's accounts, and it may also not match the mask that the bank displays to the user.
    #[serde(rename = "mask", deserialize_with = "Option::deserialize")]
    pub mask: Option<String>,
    /// The name of the account, either assigned by the user or by the financial institution itself
    #[serde(rename = "name")]
    pub name: String,
    /// The official name of the account as given by the financial institution
    #[serde(rename = "official_name", deserialize_with = "Option::deserialize")]
    pub official_name: Option<String>,
    #[serde(rename = "type")]
    pub r#type: models::AccountType,
    #[serde(rename = "subtype", deserialize_with = "Option::deserialize")]
    pub subtype: Option<models::AccountSubtype>,
    /// The current verification status of an Auth Item initiated through Automated or Manual micro-deposits.  Returned for Auth Items only.  `pending_automatic_verification`: The Item is pending automatic verification  `pending_manual_verification`: The Item is pending manual micro-deposit verification. Items remain in this state until the user successfully verifies the two amounts.  `automatically_verified`: The Item has successfully been automatically verified   `manually_verified`: The Item has successfully been manually verified  `verification_expired`: Plaid was unable to automatically verify the deposit within 7 calendar days and will no longer attempt to validate the Item. Users may retry by submitting their information again through Link.  `verification_failed`: The Item failed manual micro-deposit verification because the user exhausted all 3 verification attempts. Users may retry by submitting their information again through Link.   
    #[serde(rename = "verification_status", skip_serializing_if = "Option::is_none")]
    pub verification_status: Option<VerificationStatus>,
    /// The duration of transaction history available for this Item, typically defined as the time since the date of the earliest transaction in that account. Only returned by Assets endpoints.
    #[serde(rename = "days_available")]
    pub days_available: f64,
    /// Transaction history associated with the account. Only returned by Assets endpoints. Transaction history returned by endpoints such as `/transactions/get` or `/investments/transactions/get` will be returned in the top-level `transactions` field instead.
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::AssetReportTransaction>,
    /// Data returned by the financial institution about the account owner or owners. Only returned by Identity or Assets endpoints. Multiple owners on a single account will be represented in the same `owner` object, not in multiple owner objects within the array.
    #[serde(rename = "owners")]
    pub owners: Vec<models::Owner>,
    /// Calculated data about the historical balances on the account. Only returned by Assets endpoints.
    #[serde(rename = "historical_balances")]
    pub historical_balances: Vec<models::HistoricalBalance>,
}

impl AccountAssets {
    pub fn new(account_id: String, balances: models::AccountBalance, mask: Option<String>, name: String, official_name: Option<String>, r#type: models::AccountType, subtype: Option<models::AccountSubtype>, days_available: f64, transactions: Vec<models::AssetReportTransaction>, owners: Vec<models::Owner>, historical_balances: Vec<models::HistoricalBalance>) -> AccountAssets {
        AccountAssets {
            account_id,
            balances,
            mask,
            name,
            official_name,
            r#type,
            subtype,
            verification_status: None,
            days_available,
            transactions,
            owners,
            historical_balances,
        }
    }
}
/// The current verification status of an Auth Item initiated through Automated or Manual micro-deposits.  Returned for Auth Items only.  `pending_automatic_verification`: The Item is pending automatic verification  `pending_manual_verification`: The Item is pending manual micro-deposit verification. Items remain in this state until the user successfully verifies the two amounts.  `automatically_verified`: The Item has successfully been automatically verified   `manually_verified`: The Item has successfully been manually verified  `verification_expired`: Plaid was unable to automatically verify the deposit within 7 calendar days and will no longer attempt to validate the Item. Users may retry by submitting their information again through Link.  `verification_failed`: The Item failed manual micro-deposit verification because the user exhausted all 3 verification attempts. Users may retry by submitting their information again through Link.   
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VerificationStatus {
    #[serde(rename = "pending_automatic_verification")]
    PendingAutomaticVerification,
    #[serde(rename = "pending_manual_verification")]
    PendingManualVerification,
    #[serde(rename = "manually_verified")]
    ManuallyVerified,
    #[serde(rename = "verification_expired")]
    VerificationExpired,
    #[serde(rename = "verification_failed")]
    VerificationFailed,
}

impl Default for VerificationStatus {
    fn default() -> VerificationStatus {
        Self::PendingAutomaticVerification
    }
}

