/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountVerificationInsights : Insights from performing database verification for the account. Only returned for Auth Items using Database Auth.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountVerificationInsights {
    /// Indicates the score of the name match between the given name provided during database verification (available in the [`verification_name`](https://plaid.com/docs/api/products/auth/#auth-get-response-accounts-verification-name) field if using standard Database Auth, or provided in the request if using `/auth/verify`) and matched Plaid network accounts. If defined, will be a value between 0 and 100. Will be undefined if name matching was not enabled for the database verification session or if there were no eligible Plaid network matches to compare the given name with.
    #[serde(rename = "name_match_score", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name_match_score: Option<Option<i32>>,
    #[serde(rename = "network_status")]
    pub network_status: models::AccountVerificationInsightsNetworkStatus,
    #[serde(rename = "previous_returns", skip_serializing_if = "Option::is_none")]
    pub previous_returns: Option<models::AccountVerificationInsightsPreviousReturns>,
    #[serde(rename = "account_number_format")]
    pub account_number_format: models::AccountVerificationInsightsAccountNumberFormat,
}

impl AccountVerificationInsights {
    /// Insights from performing database verification for the account. Only returned for Auth Items using Database Auth.
    pub fn new(network_status: models::AccountVerificationInsightsNetworkStatus, account_number_format: models::AccountVerificationInsightsAccountNumberFormat) -> AccountVerificationInsights {
        AccountVerificationInsights {
            name_match_score: None,
            network_status,
            previous_returns: None,
            account_number_format,
        }
    }
}

