/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AchClass : Specifies the use case of the transfer.  Required for transfers on an ACH network.  `\"arc\"` - Accounts Receivable Entry  `\"cbr`\" - Cross Border Entry  `\"ccd\"` - Corporate Credit or Debit - fund transfer between two corporate bank accounts  `\"cie\"` - Customer Initiated Entry  `\"cor\"` - Automated Notification of Change  `\"ctx\"` - Corporate Trade Exchange  `\"iat\"` - International  `\"mte\"` - Machine Transfer Entry  `\"pbr\"` - Cross Border Entry  `\"pop\"` - Point-of-Purchase Entry  `\"pos\"` - Point-of-Sale Entry  `\"ppd\"` - Prearranged Payment or Deposit - the transfer is part of a pre-existing relationship with a consumer, eg. bill payment  `\"rck\"` - Re-presented Check Entry  `\"tel\"` - Telephone-Initiated Entry  `\"web\"` - Internet-Initiated Entry - debits from a consumer’s account where their authorization is obtained over the Internet
/// Specifies the use case of the transfer.  Required for transfers on an ACH network.  `\"arc\"` - Accounts Receivable Entry  `\"cbr`\" - Cross Border Entry  `\"ccd\"` - Corporate Credit or Debit - fund transfer between two corporate bank accounts  `\"cie\"` - Customer Initiated Entry  `\"cor\"` - Automated Notification of Change  `\"ctx\"` - Corporate Trade Exchange  `\"iat\"` - International  `\"mte\"` - Machine Transfer Entry  `\"pbr\"` - Cross Border Entry  `\"pop\"` - Point-of-Purchase Entry  `\"pos\"` - Point-of-Sale Entry  `\"ppd\"` - Prearranged Payment or Deposit - the transfer is part of a pre-existing relationship with a consumer, eg. bill payment  `\"rck\"` - Re-presented Check Entry  `\"tel\"` - Telephone-Initiated Entry  `\"web\"` - Internet-Initiated Entry - debits from a consumer’s account where their authorization is obtained over the Internet
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AchClass {
    #[serde(rename = "arc")]
    Arc,
    #[serde(rename = "cbr")]
    Cbr,
    #[serde(rename = "ccd")]
    Ccd,
    #[serde(rename = "cie")]
    Cie,
    #[serde(rename = "cor")]
    Cor,
    #[serde(rename = "ctx")]
    Ctx,
    #[serde(rename = "iat")]
    Iat,
    #[serde(rename = "mte")]
    Mte,
    #[serde(rename = "pbr")]
    Pbr,
    #[serde(rename = "pop")]
    Pop,
    #[serde(rename = "pos")]
    Pos,
    #[serde(rename = "ppd")]
    Ppd,
    #[serde(rename = "rck")]
    Rck,
    #[serde(rename = "tel")]
    Tel,
    #[serde(rename = "web")]
    Web,

}

impl std::fmt::Display for AchClass {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Arc => write!(f, "arc"),
            Self::Cbr => write!(f, "cbr"),
            Self::Ccd => write!(f, "ccd"),
            Self::Cie => write!(f, "cie"),
            Self::Cor => write!(f, "cor"),
            Self::Ctx => write!(f, "ctx"),
            Self::Iat => write!(f, "iat"),
            Self::Mte => write!(f, "mte"),
            Self::Pbr => write!(f, "pbr"),
            Self::Pop => write!(f, "pop"),
            Self::Pos => write!(f, "pos"),
            Self::Ppd => write!(f, "ppd"),
            Self::Rck => write!(f, "rck"),
            Self::Tel => write!(f, "tel"),
            Self::Web => write!(f, "web"),
        }
    }
}

impl Default for AchClass {
    fn default() -> AchClass {
        Self::Arc
    }
}

