/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetsErrorWebhook : Fired when Asset Report generation has failed. The resulting `error` will have an `error_type` of `ASSET_REPORT_ERROR`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsErrorWebhook {
    /// `ASSETS`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `ERROR`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    #[serde(rename = "error", deserialize_with = "Option::deserialize")]
    pub error: Option<models::Error>,
    /// The ID associated with the Asset Report.
    #[serde(rename = "asset_report_id")]
    pub asset_report_id: String,
}

impl AssetsErrorWebhook {
    /// Fired when Asset Report generation has failed. The resulting `error` will have an `error_type` of `ASSET_REPORT_ERROR`.
    pub fn new(webhook_type: String, webhook_code: String, error: Option<models::Error>, asset_report_id: String) -> AssetsErrorWebhook {
        AssetsErrorWebhook {
            webhook_type,
            webhook_code,
            error,
            asset_report_id,
        }
    }
}

