/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetDetail : Details about an asset.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetDetail {
    /// A vendor created unique Identifier.
    #[serde(rename = "AssetUniqueIdentifier")]
    pub asset_unique_identifier: String,
    /// A unique alphanumeric string identifying an asset.
    #[serde(rename = "AssetAccountIdentifier")]
    pub asset_account_identifier: String,
    /// Account Report As of Date / Create Date. Format YYYY-MM-DD
    #[serde(rename = "AssetAsOfDate")]
    pub asset_as_of_date: String,
    /// A text description that further defines the Asset. This could be used to describe the shares associated with the stocks, bonds or mutual funds, retirement funds or business owned that the borrower has disclosed (named) as an asset.
    #[serde(rename = "AssetDescription", deserialize_with = "Option::deserialize")]
    pub asset_description: Option<String>,
    /// Asset Account Available Balance.
    #[serde(rename = "AssetAvailableBalanceAmount")]
    pub asset_available_balance_amount: f64,
    /// A vendor created unique Identifier
    #[serde(rename = "AssetCurrentBalanceAmount")]
    pub asset_current_balance_amount: f64,
    /// Total market value of holdings (non-restricted, vested, not crypto, not other, not cash) Note: Any employer stock plan balance must be excluded from the total account balance (identification is 'stock plan')
    #[serde(rename = "AssetHoldingBalanceAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asset_holding_balance_amount: Option<Option<f64>>,
    /// HoldingsBalance net MarginAmount
    #[serde(rename = "AssetHoldingBalanceNetMarginAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asset_holding_balance_net_margin_amount: Option<Option<f64>>,
    /// Total market value of all bonds held (non-restricted, vested)
    #[serde(rename = "AssetBondsBalanceAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asset_bonds_balance_amount: Option<Option<f64>>,
    /// Total market value of all stocks held (non-restricted, vested, not employer sponsored stock plan)
    #[serde(rename = "AssetStocksBalanceAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asset_stocks_balance_amount: Option<Option<f64>>,
    /// Total balance of all cryptocurrency held (non-restricted, vested)
    #[serde(rename = "AssetCryptoBalanceAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asset_crypto_balance_amount: Option<Option<f64>>,
    /// Total balance of all other holding types (non-restricted, vested)
    #[serde(rename = "AssetOtherBalanceAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asset_other_balance_amount: Option<Option<f64>>,
    /// loan balance (amount owed by account owner)
    #[serde(rename = "AssetMarginAmountBalance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asset_margin_amount_balance: Option<Option<f64>>,
    /// amount available for cash withdrawal
    #[serde(rename = "AssetAvailableCashBalanceAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asset_available_cash_balance_amount: Option<Option<f64>>,
    /// cash balance of the account
    #[serde(rename = "AssetCashBalanceAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asset_cash_balance_amount: Option<Option<f64>>,
    #[serde(rename = "AssetType")]
    pub asset_type: models::AssetType,
    /// Additional Asset Decription some examples are Investment Tax-Deferred , Loan, 401K, 403B, Checking, Money Market, Credit Card,ROTH,529,Biller,ROLLOVER,CD,Savings,Investment Taxable, IRA, Mortgage, Line Of Credit.
    #[serde(rename = "AssetTypeAdditionalDescription", deserialize_with = "Option::deserialize")]
    pub asset_type_additional_description: Option<String>,
    /// The Number of days requested made to the Financial Institution. Example When looking for 3 months of data from the FI, pass in 90 days.
    #[serde(rename = "AssetDaysRequestedCount")]
    pub asset_days_requested_count: i32,
    /// Ownership type of the asset account.
    #[serde(rename = "AssetOwnershipType", deserialize_with = "Option::deserialize")]
    pub asset_ownership_type: Option<String>,
    /// Whether or not the account is a retirement account (e.g., 401K, 403b, 457, thrift savings plans, traditional and Roth, IRAs, SEP-IRA, SIMPLE-IRA, KEOGH, state retirement savings plans, other independent and IRS-qualified employer retirement plans)
    #[serde(rename = "AssetRetirementIndicator", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asset_retirement_indicator: Option<Option<AssetRetirementIndicator>>,
    /// Whether the account is employer sponsored retirement account or not (e.g., 401K, 403b, 457, thrift savings plan)
    #[serde(rename = "AssetEmployerSponsoredIndicator", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asset_employer_sponsored_indicator: Option<Option<AssetEmployerSponsoredIndicator>>,
}

impl AssetDetail {
    /// Details about an asset.
    pub fn new(asset_unique_identifier: String, asset_account_identifier: String, asset_as_of_date: String, asset_description: Option<String>, asset_available_balance_amount: f64, asset_current_balance_amount: f64, asset_type: models::AssetType, asset_type_additional_description: Option<String>, asset_days_requested_count: i32, asset_ownership_type: Option<String>) -> AssetDetail {
        AssetDetail {
            asset_unique_identifier,
            asset_account_identifier,
            asset_as_of_date,
            asset_description,
            asset_available_balance_amount,
            asset_current_balance_amount,
            asset_holding_balance_amount: None,
            asset_holding_balance_net_margin_amount: None,
            asset_bonds_balance_amount: None,
            asset_stocks_balance_amount: None,
            asset_crypto_balance_amount: None,
            asset_other_balance_amount: None,
            asset_margin_amount_balance: None,
            asset_available_cash_balance_amount: None,
            asset_cash_balance_amount: None,
            asset_type,
            asset_type_additional_description,
            asset_days_requested_count,
            asset_ownership_type,
            asset_retirement_indicator: None,
            asset_employer_sponsored_indicator: None,
        }
    }
}
/// Whether or not the account is a retirement account (e.g., 401K, 403b, 457, thrift savings plans, traditional and Roth, IRAs, SEP-IRA, SIMPLE-IRA, KEOGH, state retirement savings plans, other independent and IRS-qualified employer retirement plans)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetRetirementIndicator {
    #[serde(rename = "true")]
    True,
    #[serde(rename = "false")]
    False,
}

impl Default for AssetRetirementIndicator {
    fn default() -> AssetRetirementIndicator {
        Self::True
    }
}
/// Whether the account is employer sponsored retirement account or not (e.g., 401K, 403b, 457, thrift savings plan)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetEmployerSponsoredIndicator {
    #[serde(rename = "true")]
    True,
    #[serde(rename = "false")]
    False,
}

impl Default for AssetEmployerSponsoredIndicator {
    fn default() -> AssetEmployerSponsoredIndicator {
        Self::True
    }
}

