/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthVerifyRequest : AuthVerifyRequest defines the request schema for `/auth/verify`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthVerifyRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// Account owner's legal name
    #[serde(rename = "legal_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub legal_name: Option<Option<String>>,
    #[serde(rename = "numbers")]
    pub numbers: Box<models::AuthVerifyRequestNumbers>,
}

impl AuthVerifyRequest {
    /// AuthVerifyRequest defines the request schema for `/auth/verify`
    pub fn new(numbers: models::AuthVerifyRequestNumbers) -> AuthVerifyRequest {
        AuthVerifyRequest {
            client_id: None,
            secret: None,
            legal_name: None,
            numbers: Box::new(numbers),
        }
    }
}

