/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthVerifyResponse : AuthVerifyResponse defines the response schema for `/auth/verify`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthVerifyResponse {
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
    /// The `item_id` value of the Item created for verification. If numbers data provided is invalid, an item may not be created.
    #[serde(rename = "item_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<Option<String>>,
    /// Indicates the Item's database verification status. Possible values are:  `database_insights_fail`: The Item's numbers have been verified using Plaid's data sources and have signal for being invalid and/or have no signal for being valid. Typically this indicates that the routing number is invalid, the account number does not match the account number format associated with the routing number, or the account has been reported as closed or frozen. Only returned for Auth Items created via Database Auth.  `database_insights_pass`: The Item's numbers have been verified using Plaid's data sources: the routing and account number match a routing and account number of an account recognized on the Plaid network, and the account is not known by Plaid to be frozen or closed. Only returned for Auth Items created via Database Auth.  `database_insights_pass_with_caution`: The Item's numbers have been verified using Plaid's data sources and have some signal for being valid: the routing and account number were not recognized on the Plaid network, but the routing number is valid and the account number is a potential valid account number for that routing number. Only returned for Auth Items created via Database Auth. 
    #[serde(rename = "verification_status")]
    pub verification_status: String,
    #[serde(rename = "verification_insights")]
    pub verification_insights: models::AccountVerificationInsights,
}

impl AuthVerifyResponse {
    /// AuthVerifyResponse defines the response schema for `/auth/verify`
    pub fn new(request_id: String, verification_status: String, verification_insights: models::AccountVerificationInsights) -> AuthVerifyResponse {
        AuthVerifyResponse {
            request_id,
            item_id: None,
            verification_status,
            verification_insights,
        }
    }
}

