/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BankTransferReceiverDetails : The receiver details if the type of this event is `reciever_pending` or `reciever_posted`. Null value otherwise.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankTransferReceiverDetails {
    /// The sign of the available balance for the receiver bank account associated with the receiver event at the time the matching transaction was found. Can be `positive`, `negative`, or null if the balance was not available at the time.
    #[serde(rename = "available_balance", deserialize_with = "Option::deserialize")]
    pub available_balance: Option<AvailableBalance>,
}

impl BankTransferReceiverDetails {
    /// The receiver details if the type of this event is `reciever_pending` or `reciever_posted`. Null value otherwise.
    pub fn new(available_balance: Option<AvailableBalance>) -> BankTransferReceiverDetails {
        BankTransferReceiverDetails {
            available_balance,
        }
    }
}
/// The sign of the available balance for the receiver bank account associated with the receiver event at the time the matching transaction was found. Can be `positive`, `negative`, or null if the balance was not available at the time.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AvailableBalance {
    #[serde(rename = "positive")]
    Positive,
    #[serde(rename = "negative")]
    Negative,
}

impl Default for AvailableBalance {
    fn default() -> AvailableBalance {
        Self::Positive
    }
}

