/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BankPenaltiesIndicators : Insights into bank penalties and fees, including overdraft fees, NSF fees, and other bank-imposed charges.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankPenaltiesIndicators {
    /// The total value of outflow transactions categorized as `BANK_PENALTIES`, across all the accounts in the report within the requested time window.
    #[serde(rename = "amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Option<f64>>,
    /// The ISO-4217 currency code of the amount. Always `null` if `unofficial_currency_code` is non-`null`.
    #[serde(rename = "iso_currency_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub iso_currency_code: Option<Option<String>>,
    /// The unofficial currency code associated with the amount. Always `null` if `iso_currency_code` is non-`null`.  See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `unofficial_currency_code`s.
    #[serde(rename = "unofficial_currency_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unofficial_currency_code: Option<Option<String>>,
    #[serde(rename = "monthly_average", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub monthly_average: Option<Option<models::MonthlyAverage>>,
    /// Detailed categories view of all the transactions that fall into the `BANK_PENALTIES` credit category within the given time window, across all the accounts in the report.
    #[serde(rename = "category_details", skip_serializing_if = "Option::is_none")]
    pub category_details: Option<Vec<models::CategoryExpenses>>,
    /// The total number of transactions that fall into the `BANK_PENALTIES` credit category, across all the accounts in the report.
    #[serde(rename = "transactions_count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transactions_count: Option<Option<i32>>,
    /// The monthly summaries of the transactions that fall into the `BANK_PENALTIES` credit category within the given time window, across all the accounts in the report.
    #[serde(rename = "monthly_summaries", skip_serializing_if = "Option::is_none")]
    pub monthly_summaries: Option<Vec<models::MonthlySummary>>,
    /// The number of days since the last transaction that falls into the `BANK_PENALTIES` credit category, across all the accounts in the report.
    #[serde(rename = "days_since_last_occurrence", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub days_since_last_occurrence: Option<Option<i32>>,
    /// The percentage of the user's monthly inflows that was spent on transactions that fall into the `BANK_PENALTIES` credit category within the given time window, across all the accounts in the report. For example, a value of 100 represents that 100% of the inflows were spent on transactions that fall into the `BANK_PENALTIES` credit category. If there's no available income for the given time period, this field value will be `-1`.
    #[serde(rename = "percentage_of_income", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub percentage_of_income: Option<Option<f64>>,
}

impl BankPenaltiesIndicators {
    /// Insights into bank penalties and fees, including overdraft fees, NSF fees, and other bank-imposed charges.
    pub fn new() -> BankPenaltiesIndicators {
        BankPenaltiesIndicators {
            amount: None,
            iso_currency_code: None,
            unofficial_currency_code: None,
            monthly_average: None,
            category_details: None,
            transactions_count: None,
            monthly_summaries: None,
            days_since_last_occurrence: None,
            percentage_of_income: None,
        }
    }
}

