/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BaseReportAccountMetadata : Metadata about the extracted account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseReportAccountMetadata {
    /// The beginning of the range of the financial institution provided data for the account, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (\"yyyy-mm-dd\").
    #[serde(rename = "start_date", deserialize_with = "Option::deserialize")]
    pub start_date: Option<chrono::NaiveDate>,
    /// The end of the range of the financial institution provided data for the account, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (\"yyyy-mm-dd\").
    #[serde(rename = "end_date", deserialize_with = "Option::deserialize")]
    pub end_date: Option<chrono::NaiveDate>,
}

impl BaseReportAccountMetadata {
    /// Metadata about the extracted account.
    pub fn new(start_date: Option<chrono::NaiveDate>, end_date: Option<chrono::NaiveDate>) -> BaseReportAccountMetadata {
        BaseReportAccountMetadata {
            start_date,
            end_date,
        }
    }
}

