/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BaseReportInvestments : A set of fields describing the investments data on an account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseReportInvestments {
    /// Quantities and values of securities held in the investment account. Map to the `securities` array for security details.
    #[serde(rename = "holdings")]
    pub holdings: Vec<models::BaseReportInvestmentHolding>,
    /// Details of specific securities held in the investment account.
    #[serde(rename = "securities")]
    pub securities: Vec<models::BaseReportInvestmentSecurity>,
    /// Transaction history on the investment account.
    #[serde(rename = "investment_transactions")]
    pub investment_transactions: Vec<models::BaseReportInvestmentTransaction>,
}

impl BaseReportInvestments {
    /// A set of fields describing the investments data on an account.
    pub fn new(holdings: Vec<models::BaseReportInvestmentHolding>, securities: Vec<models::BaseReportInvestmentSecurity>, investment_transactions: Vec<models::BaseReportInvestmentTransaction>) -> BaseReportInvestments {
        BaseReportInvestments {
            holdings,
            securities,
            investment_transactions,
        }
    }
}

