/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BaseReportAverageFlowInsights : Average dollar amount of credit or debit transactions out of the account. This field will only be included for depository accounts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseReportAverageFlowInsights {
    /// The start date of this time period. The date will be returned in an ISO 8601 format (YYYY-MM-DD).
    #[serde(rename = "start_date")]
    pub start_date: chrono::NaiveDate,
    /// The end date of this time period. The date will be returned in an ISO 8601 format (YYYY-MM-DD).
    #[serde(rename = "end_date")]
    pub end_date: chrono::NaiveDate,
    #[serde(rename = "total_amount")]
    pub total_amount: models::CreditAmountWithCurrency,
}

impl BaseReportAverageFlowInsights {
    /// Average dollar amount of credit or debit transactions out of the account. This field will only be included for depository accounts.
    pub fn new(start_date: chrono::NaiveDate, end_date: chrono::NaiveDate, total_amount: models::CreditAmountWithCurrency) -> BaseReportAverageFlowInsights {
        BaseReportAverageFlowInsights {
            start_date,
            end_date,
            total_amount,
        }
    }
}

