/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BetaPartnerEndCustomer : The details for an end customer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BetaPartnerEndCustomer {
    /// The `client_id` of the end customer.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// The company name associated with the end customer.
    #[serde(rename = "company_name", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::PartnerEndCustomerStatus>,
    /// Mapping of product names to their current status.
    #[serde(rename = "product_statuses", skip_serializing_if = "Option::is_none")]
    pub product_statuses: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// A list of fields that are still required to be submitted.
    #[serde(rename = "requirements_due", skip_serializing_if = "Option::is_none")]
    pub requirements_due: Option<Vec<models::PartnerEndCustomerRequirementDue>>,
}

impl BetaPartnerEndCustomer {
    /// The details for an end customer.
    pub fn new() -> BetaPartnerEndCustomer {
        BetaPartnerEndCustomer {
            client_id: None,
            company_name: None,
            status: None,
            product_statuses: None,
            requirements_due: None,
        }
    }
}

