/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BetaPartnerCustomerV1EnableResponse : Response schema for `/beta/partner/customer/v1/enable`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BetaPartnerCustomerV1EnableResponse {
    #[serde(rename = "end_customer_client_id", skip_serializing_if = "Option::is_none")]
    pub end_customer_client_id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::PartnerEndCustomerStatus>,
    /// Mapping of product names to their current status.
    #[serde(rename = "product_statuses", skip_serializing_if = "Option::is_none")]
    pub product_statuses: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "production_secret", skip_serializing_if = "Option::is_none")]
    pub production_secret: Option<String>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl BetaPartnerCustomerV1EnableResponse {
    /// Response schema for `/beta/partner/customer/v1/enable`.
    pub fn new() -> BetaPartnerCustomerV1EnableResponse {
        BetaPartnerCustomerV1EnableResponse {
            end_customer_client_id: None,
            status: None,
            product_statuses: None,
            production_secret: None,
            request_id: None,
        }
    }
}

