/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BetaPartnerCustomerV1UpdateResponse : Response schema for `/beta/partner/customer/v1/update`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BetaPartnerCustomerV1UpdateResponse {
    #[serde(rename = "end_customer", skip_serializing_if = "Option::is_none")]
    pub end_customer: Option<models::BetaPartnerEndCustomer>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl BetaPartnerCustomerV1UpdateResponse {
    /// Response schema for `/beta/partner/customer/v1/update`.
    pub fn new() -> BetaPartnerCustomerV1UpdateResponse {
        BetaPartnerCustomerV1UpdateResponse {
            end_customer: None,
            request_id: None,
        }
    }
}

