/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BusinessKybCheck : Results from the KYB (Know Your Business) identity verification check
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BusinessKybCheck {
    #[serde(rename = "status")]
    pub status: models::BusinessVerificationStatusKybCheck,
    /// A score from 0 to 100 indicating the confidence in KYB (Know Your Business) identity assessment for the business
    #[serde(rename = "score")]
    pub score: i32,
    #[serde(rename = "name")]
    pub name: models::BusinessFieldMatchSummary,
    #[serde(rename = "address")]
    pub address: models::BusinessFieldMatchSummary,
    #[serde(rename = "website")]
    pub website: models::BusinessFieldMatchSummary,
    #[serde(rename = "match_details", deserialize_with = "Option::deserialize")]
    pub match_details: Option<models::BusinessKybMatchDetails>,
}

impl BusinessKybCheck {
    /// Results from the KYB (Know Your Business) identity verification check
    pub fn new(status: models::BusinessVerificationStatusKybCheck, score: i32, name: models::BusinessFieldMatchSummary, address: models::BusinessFieldMatchSummary, website: models::BusinessFieldMatchSummary, match_details: Option<models::BusinessKybMatchDetails>) -> BusinessKybCheck {
        BusinessKybCheck {
            status,
            score,
            name,
            address,
            website,
            match_details,
        }
    }
}

