/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BusinessWebsiteAnalysis : Website analysis details if a website is found for the provided website in the search terms.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BusinessWebsiteAnalysis {
    #[serde(rename = "is_parked")]
    pub is_parked: models::BusinessCheckBooleanStatus,
    #[serde(rename = "email_is_deliverable")]
    pub email_is_deliverable: models::BusinessCheckBooleanStatus,
    #[serde(rename = "website_build_status")]
    pub website_build_status: models::BusinessWebsiteBuildStatus,
    #[serde(rename = "whois_record")]
    pub whois_record: models::BusinessWhoisRecord,
    #[serde(rename = "ssl")]
    pub ssl: models::BusinessWebsiteSsl,
}

impl BusinessWebsiteAnalysis {
    /// Website analysis details if a website is found for the provided website in the search terms.
    pub fn new(is_parked: models::BusinessCheckBooleanStatus, email_is_deliverable: models::BusinessCheckBooleanStatus, website_build_status: models::BusinessWebsiteBuildStatus, whois_record: models::BusinessWhoisRecord, ssl: models::BusinessWebsiteSsl) -> BusinessWebsiteAnalysis {
        BusinessWebsiteAnalysis {
            is_parked,
            email_is_deliverable,
            website_build_status,
            whois_record,
            ssl,
        }
    }
}

