/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BusinessDigitalPresenceCheck : Results from the digital presence check.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BusinessDigitalPresenceCheck {
    #[serde(rename = "status")]
    pub status: models::BusinessVerificationStatusWebPresenceCheck,
    /// A score from 0 to 100 indicating digital presence confidence.
    #[serde(rename = "score")]
    pub score: i32,
    #[serde(rename = "address")]
    pub address: models::BusinessFieldMatchSummary,
    #[serde(rename = "phone_number")]
    pub phone_number: models::BusinessFieldMatchSummary,
    #[serde(rename = "email_address")]
    pub email_address: models::BusinessFieldMatchSummary,
    #[serde(rename = "website")]
    pub website: models::BusinessFieldMatchSummary,
    #[serde(rename = "website_analysis", deserialize_with = "Option::deserialize")]
    pub website_analysis: Option<models::BusinessWebsiteAnalysis>,
}

impl BusinessDigitalPresenceCheck {
    /// Results from the digital presence check.
    pub fn new(status: models::BusinessVerificationStatusWebPresenceCheck, score: i32, address: models::BusinessFieldMatchSummary, phone_number: models::BusinessFieldMatchSummary, email_address: models::BusinessFieldMatchSummary, website: models::BusinessFieldMatchSummary, website_analysis: Option<models::BusinessWebsiteAnalysis>) -> BusinessDigitalPresenceCheck {
        BusinessDigitalPresenceCheck {
            status,
            score,
            address,
            phone_number,
            email_address,
            website,
            website_analysis,
        }
    }
}

