/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BusinessWebsite : Website associated with a business
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BusinessWebsite {
    /// URL of the business website
    #[serde(rename = "url", deserialize_with = "Option::deserialize")]
    pub url: Option<String>,
}

impl BusinessWebsite {
    /// Website associated with a business
    pub fn new(url: Option<String>) -> BusinessWebsite {
        BusinessWebsite {
            url,
        }
    }
}

