/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BusinessVerificationCreateRequest : Request input for creating a business verification
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BusinessVerificationCreateRequest {
    /// A unique ID that identifies the end user in your system. Either a `user_id` or the `client_user_id` must be provided. This ID can also be used to associate user-specific data from other Plaid products. Financial Account Matching requires this field and the `/link/token/create` `client_user_id` to be consistent. Personally identifiable information, such as an email address or phone number, should not be used in the `client_user_id`.
    #[serde(rename = "client_user_id")]
    pub client_user_id: String,
    #[serde(rename = "business", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub business: Option<Option<models::BusinessVerificationCreateRequestBusiness>>,
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl BusinessVerificationCreateRequest {
    /// Request input for creating a business verification
    pub fn new(client_user_id: String) -> BusinessVerificationCreateRequest {
        BusinessVerificationCreateRequest {
            client_user_id,
            business: None,
            client_id: None,
            secret: None,
        }
    }
}

