/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BusinessEntityType : The legal structure or type of business entity
/// The legal structure or type of business entity
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BusinessEntityType {
    #[serde(rename = "sole_proprietorship")]
    SoleProprietorship,
    #[serde(rename = "general_partnership")]
    GeneralPartnership,
    #[serde(rename = "llc")]
    Llc,
    #[serde(rename = "llp")]
    Llp,
    #[serde(rename = "lllp")]
    Lllp,
    #[serde(rename = "lp")]
    Lp,
    #[serde(rename = "c_corporation")]
    CCorporation,
    #[serde(rename = "s_corporation")]
    SCorporation,
    #[serde(rename = "b_corporation")]
    BCorporation,
    #[serde(rename = "nonprofit")]
    Nonprofit,
    #[serde(rename = "cooperative")]
    Cooperative,
    #[serde(rename = "trust")]
    Trust,
    #[serde(rename = "professional_association")]
    ProfessionalAssociation,
    #[serde(rename = "professional_corporation")]
    ProfessionalCorporation,
    #[serde(rename = "trade_name")]
    TradeName,
    #[serde(rename = "bank")]
    Bank,
    #[serde(rename = "credit_union")]
    CreditUnion,
    #[serde(rename = "insurance")]
    Insurance,
    #[serde(rename = "other")]
    Other,
    #[serde(rename = "unknown")]
    Unknown,

}

impl std::fmt::Display for BusinessEntityType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SoleProprietorship => write!(f, "sole_proprietorship"),
            Self::GeneralPartnership => write!(f, "general_partnership"),
            Self::Llc => write!(f, "llc"),
            Self::Llp => write!(f, "llp"),
            Self::Lllp => write!(f, "lllp"),
            Self::Lp => write!(f, "lp"),
            Self::CCorporation => write!(f, "c_corporation"),
            Self::SCorporation => write!(f, "s_corporation"),
            Self::BCorporation => write!(f, "b_corporation"),
            Self::Nonprofit => write!(f, "nonprofit"),
            Self::Cooperative => write!(f, "cooperative"),
            Self::Trust => write!(f, "trust"),
            Self::ProfessionalAssociation => write!(f, "professional_association"),
            Self::ProfessionalCorporation => write!(f, "professional_corporation"),
            Self::TradeName => write!(f, "trade_name"),
            Self::Bank => write!(f, "bank"),
            Self::CreditUnion => write!(f, "credit_union"),
            Self::Insurance => write!(f, "insurance"),
            Self::Other => write!(f, "other"),
            Self::Unknown => write!(f, "unknown"),
        }
    }
}

impl Default for BusinessEntityType {
    fn default() -> BusinessEntityType {
        Self::SoleProprietorship
    }
}

