/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BusinessKybMatchDetails : Detailed information about the business from data provider results
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BusinessKybMatchDetails {
    /// Names associated with the business.
    #[serde(rename = "names")]
    pub names: Vec<models::ProviderBusinessName>,
    #[serde(rename = "entity_type", deserialize_with = "Option::deserialize")]
    pub entity_type: Option<models::BusinessEntityType>,
    /// Addresses associated with the business
    #[serde(rename = "addresses")]
    pub addresses: Vec<models::ProviderBusinessAddress>,
    /// Phone numbers associated with the business
    #[serde(rename = "phone_numbers")]
    pub phone_numbers: Vec<models::BusinessPhoneNumber>,
    /// Email addresses associated with the business
    #[serde(rename = "email_addresses")]
    pub email_addresses: Vec<models::BusinessEmailAddress>,
    /// Websites associated with the business
    #[serde(rename = "websites")]
    pub websites: Vec<models::BusinessWebsite>,
    /// A date in the format YYYY-MM-DD (RFC 3339 Section 5.6).
    #[serde(rename = "formation_date", deserialize_with = "Option::deserialize")]
    pub formation_date: Option<chrono::NaiveDate>,
}

impl BusinessKybMatchDetails {
    /// Detailed information about the business from data provider results
    pub fn new(names: Vec<models::ProviderBusinessName>, entity_type: Option<models::BusinessEntityType>, addresses: Vec<models::ProviderBusinessAddress>, phone_numbers: Vec<models::BusinessPhoneNumber>, email_addresses: Vec<models::BusinessEmailAddress>, websites: Vec<models::BusinessWebsite>, formation_date: Option<chrono::NaiveDate>) -> BusinessKybMatchDetails {
        BusinessKybMatchDetails {
            names,
            entity_type,
            addresses,
            phone_numbers,
            email_addresses,
            websites,
            formation_date,
        }
    }
}

