/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CashflowReportTransactionsGetResponse : CashflowReportTransactionsGetResponse defines the response schema for `/cashflow_report/transactions/get`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashflowReportTransactionsGetResponse {
    /// An array containing the `accounts` associated with the Item for which transactions are being returned. Each transaction can be mapped to its corresponding account via the `account_id` field.
    #[serde(rename = "accounts")]
    pub accounts: Vec<models::BusinessAccount>,
    /// An array containing transactions from the account. Transactions are returned in reverse chronological order, with the most recent at the beginning of the array. The maximum number of transactions returned is determined by the `count` parameter.
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::CashflowReportTransaction>,
    /// The total number of transactions available within the date range specified. If `total_transactions` is larger than the size of the `transactions` array, more transactions are available and can be fetched via manipulating the `offset` parameter.
    #[serde(rename = "total_transactions")]
    pub total_transactions: i32,
    #[serde(rename = "item")]
    pub item: models::Item,
    /// Cursor used for fetching any future updates after the latest update provided in this response.
    #[serde(rename = "next_cursor")]
    pub next_cursor: String,
    /// Represents if more than requested count of transactions exists to be fetched
    #[serde(rename = "has_more")]
    pub has_more: bool,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl CashflowReportTransactionsGetResponse {
    /// CashflowReportTransactionsGetResponse defines the response schema for `/cashflow_report/transactions/get`
    pub fn new(accounts: Vec<models::BusinessAccount>, transactions: Vec<models::CashflowReportTransaction>, total_transactions: i32, item: models::Item, next_cursor: String, has_more: bool, request_id: String) -> CashflowReportTransactionsGetResponse {
        CashflowReportTransactionsGetResponse {
            accounts,
            transactions,
            total_transactions,
            item,
            next_cursor,
            has_more,
            request_id,
        }
    }
}

