/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CashflowReportMonthlySummary : Monthly summary statistics derived from transaction-level data.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashflowReportMonthlySummary {
    /// The start date of the period covered in this monthly summary.  This date will be the first day of the month, unless the month being covered is a partial month because it is the first month included in the summary and the date range being requested does not begin with the first day of the month.  The date will be returned in an ISO 8601 format (YYYY-MM-DD).
    #[serde(rename = "start_date")]
    pub start_date: chrono::NaiveDate,
    /// The end date of the period included in this monthly summary.  This date will be the last day of the month, unless the month being covered is a partial month because it is the last month included in the summary and the date range being requested does not end with the last day of the month.  The date will be returned in an ISO 8601 format (YYYY-MM-DD).
    #[serde(rename = "end_date")]
    pub end_date: chrono::NaiveDate,
    #[serde(rename = "starting_balance", deserialize_with = "Option::deserialize")]
    pub starting_balance: Option<Box<models::CashflowReportMonthlySummaryStartingBalance>>,
    #[serde(rename = "ending_balance", deserialize_with = "Option::deserialize")]
    pub ending_balance: Option<Box<models::CashflowReportMonthlySummaryEndingBalance>>,
    #[serde(rename = "average_daily_ending_balance")]
    pub average_daily_ending_balance: Box<models::CashflowReportMonthlySummaryAverageDailyEndingBalance>,
    #[serde(rename = "average_daily_inflow_amount")]
    pub average_daily_inflow_amount: Box<models::CashflowReportMonthlySummaryAverageDailyInflowAmount>,
    #[serde(rename = "average_daily_outflow_amount")]
    pub average_daily_outflow_amount: Box<models::CashflowReportMonthlySummaryAverageDailyOutflowAmount>,
    #[serde(rename = "average_daily_net_cashflow_amount")]
    pub average_daily_net_cashflow_amount: Box<models::CashflowReportMonthlySummaryAverageDailyNetCashflowAmount>,
    /// The average count of the number of daily inflow transactions. Rounded to 2 decimal places.
    #[serde(rename = "average_daily_inflow_transaction_count")]
    pub average_daily_inflow_transaction_count: f64,
    /// The average count of the number of daily outflow transactions. Rounded to 2 decimal places.
    #[serde(rename = "average_daily_outflow_transaction_count")]
    pub average_daily_outflow_transaction_count: f64,
    #[serde(rename = "total_revenue")]
    pub total_revenue: Box<models::CashflowReportMonthlySummaryTotalRevenue>,
    #[serde(rename = "total_loan_payment")]
    pub total_loan_payment: Box<models::CashflowReportMonthlySummaryTotalLoanPayment>,
    #[serde(rename = "total_variable_expense")]
    pub total_variable_expense: Box<models::CashflowReportMonthlySummaryTotalVariableExpense>,
    #[serde(rename = "total_payroll")]
    pub total_payroll: Box<models::CashflowReportMonthlySummaryTotalPayroll>,
    /// The total number of all NSF transactions during this month.
    #[serde(rename = "nsf_transaction_count")]
    pub nsf_transaction_count: i32,
    /// The total number of all overdraft transactions during this month.
    #[serde(rename = "overdraft_transaction_count")]
    pub overdraft_transaction_count: i32,
    /// The number of days with a negative daily average ending balance. The daily average is calculated across all valid accounts. Values will be in the range [0, 31].
    #[serde(rename = "negative_ending_balance_day_count")]
    pub negative_ending_balance_day_count: i32,
}

impl CashflowReportMonthlySummary {
    /// Monthly summary statistics derived from transaction-level data.
    pub fn new(start_date: chrono::NaiveDate, end_date: chrono::NaiveDate, starting_balance: Option<models::CashflowReportMonthlySummaryStartingBalance>, ending_balance: Option<models::CashflowReportMonthlySummaryEndingBalance>, average_daily_ending_balance: models::CashflowReportMonthlySummaryAverageDailyEndingBalance, average_daily_inflow_amount: models::CashflowReportMonthlySummaryAverageDailyInflowAmount, average_daily_outflow_amount: models::CashflowReportMonthlySummaryAverageDailyOutflowAmount, average_daily_net_cashflow_amount: models::CashflowReportMonthlySummaryAverageDailyNetCashflowAmount, average_daily_inflow_transaction_count: f64, average_daily_outflow_transaction_count: f64, total_revenue: models::CashflowReportMonthlySummaryTotalRevenue, total_loan_payment: models::CashflowReportMonthlySummaryTotalLoanPayment, total_variable_expense: models::CashflowReportMonthlySummaryTotalVariableExpense, total_payroll: models::CashflowReportMonthlySummaryTotalPayroll, nsf_transaction_count: i32, overdraft_transaction_count: i32, negative_ending_balance_day_count: i32) -> CashflowReportMonthlySummary {
        CashflowReportMonthlySummary {
            start_date,
            end_date,
            starting_balance: if let Some(x) = starting_balance {Some(Box::new(x))} else {None},
            ending_balance: if let Some(x) = ending_balance {Some(Box::new(x))} else {None},
            average_daily_ending_balance: Box::new(average_daily_ending_balance),
            average_daily_inflow_amount: Box::new(average_daily_inflow_amount),
            average_daily_outflow_amount: Box::new(average_daily_outflow_amount),
            average_daily_net_cashflow_amount: Box::new(average_daily_net_cashflow_amount),
            average_daily_inflow_transaction_count,
            average_daily_outflow_transaction_count,
            total_revenue: Box::new(total_revenue),
            total_loan_payment: Box::new(total_loan_payment),
            total_variable_expense: Box::new(total_variable_expense),
            total_payroll: Box::new(total_payroll),
            nsf_transaction_count,
            overdraft_transaction_count,
            negative_ending_balance_day_count,
        }
    }
}

