/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CashFlowUpdatesInsightsV2Webhook : For each item on an enabled user, this webhook will fire up to four times a day with status information. This webhook will not fire immediately upon enrollment in Cash Flow Updates. The payload may contain an `insights` array with insights that have been detected, if any (e.g. `LOW_BALANCE_DETECTED`, `LARGE_DEPOSIT_DETECTED`). Upon receiving the webhook, call `/cra/monitoring_insights/get` to retrieve the updated insights.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashFlowUpdatesInsightsV2Webhook {
    /// `CASH_FLOW_UPDATES`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `CASH_FLOW_INSIGHTS_UPDATED`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    #[serde(rename = "status")]
    pub status: models::MonitoringInsightsStatus,
    /// The `user_id` associated with the user whose data is being requested. This is received by calling `user/create`.
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// Array containing the insights detected within the generated report, if any. Possible values include:   `LARGE_DEPOSIT_DETECTED`: signaling a deposit over $5,000   `LOW_BALANCE_DETECTED`: signaling a balance below $100   `NEW_LOAN_PAYMENT_DETECTED`: signaling a new loan payment   `NSF_OVERDRAFT_DETECTED`: signaling an NSF overdraft
    #[serde(rename = "insights")]
    pub insights: Vec<models::CashFlowInsight>,
    #[serde(rename = "environment")]
    pub environment: models::WebhookEnvironmentValues,
}

impl CashFlowUpdatesInsightsV2Webhook {
    /// For each item on an enabled user, this webhook will fire up to four times a day with status information. This webhook will not fire immediately upon enrollment in Cash Flow Updates. The payload may contain an `insights` array with insights that have been detected, if any (e.g. `LOW_BALANCE_DETECTED`, `LARGE_DEPOSIT_DETECTED`). Upon receiving the webhook, call `/cra/monitoring_insights/get` to retrieve the updated insights.
    pub fn new(webhook_type: String, webhook_code: String, status: models::MonitoringInsightsStatus, user_id: String, insights: Vec<models::CashFlowInsight>, environment: models::WebhookEnvironmentValues) -> CashFlowUpdatesInsightsV2Webhook {
        CashFlowUpdatesInsightsV2Webhook {
            webhook_type,
            webhook_code,
            status,
            user_id,
            insights,
            environment,
        }
    }
}

