/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CashflowReportAccountInsights : Insights on the account level. These are only returned for Credit and Depository type accounts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashflowReportAccountInsights {
    /// Calculated data about the historical balances on the account.  Available for `credit` and `depository` type accounts.
    #[serde(rename = "historical_balances")]
    pub historical_balances: Vec<models::CashflowReportHistoricalBalance>,
    /// Monthly summary statistics derived from transaction-level data.
    #[serde(rename = "monthly_summaries")]
    pub monthly_summaries: Vec<models::CashflowReportMonthlySummary>,
}

impl CashflowReportAccountInsights {
    /// Insights on the account level. These are only returned for Credit and Depository type accounts.
    pub fn new(historical_balances: Vec<models::CashflowReportHistoricalBalance>, monthly_summaries: Vec<models::CashflowReportMonthlySummary>) -> CashflowReportAccountInsights {
        CashflowReportAccountInsights {
            historical_balances,
            monthly_summaries,
        }
    }
}

