/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CashFlowUpdatesInsightsWebhook : For each user's Item enabled for Cash Flow Updates, this webhook will fire between one and four times a day with information on the status of the update. This webhook will not fire immediately upon enrollment in Cash Flow Updates. Upon receiving the webhook, call `/cra/monitoring_insights/get` to retrieve the updated insights. At approximately the same time as the `INSIGHTS_UPDATED` webhook, any event-driven `CASH_FLOW_UPDATES` webhooks (e.g. `LOW_BALANCE_DETECTED`, `LARGE_DEPOSIT_DETECTED`) that were triggered by the update will also fire. This webhook has been replaced by the `CASH_FLOW_INSIGHTS_UPDATED` webhook for all customers who began using Plaid Check on or after December 10, 2025.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashFlowUpdatesInsightsWebhook {
    /// `CASH_FLOW_UPDATES`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `INSIGHTS_UPDATED`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    #[serde(rename = "status")]
    pub status: models::MonitoringInsightsStatus,
    /// The `user_id` that the report is associated with
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "environment")]
    pub environment: models::WebhookEnvironmentValues,
}

impl CashFlowUpdatesInsightsWebhook {
    /// For each user's Item enabled for Cash Flow Updates, this webhook will fire between one and four times a day with information on the status of the update. This webhook will not fire immediately upon enrollment in Cash Flow Updates. Upon receiving the webhook, call `/cra/monitoring_insights/get` to retrieve the updated insights. At approximately the same time as the `INSIGHTS_UPDATED` webhook, any event-driven `CASH_FLOW_UPDATES` webhooks (e.g. `LOW_BALANCE_DETECTED`, `LARGE_DEPOSIT_DETECTED`) that were triggered by the update will also fire. This webhook has been replaced by the `CASH_FLOW_INSIGHTS_UPDATED` webhook for all customers who began using Plaid Check on or after December 10, 2025.
    pub fn new(webhook_type: String, webhook_code: String, status: models::MonitoringInsightsStatus, user_id: String, environment: models::WebhookEnvironmentValues) -> CashFlowUpdatesInsightsWebhook {
        CashFlowUpdatesInsightsWebhook {
            webhook_type,
            webhook_code,
            status,
            user_id,
            environment,
        }
    }
}

