/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CashFlowUpdatesLowBalanceWebhook : For each user's item enabled for Cash Flow Updates, this webhook will fire when an update detects a balance below $100. Upon receiving the webhook, call `/cra/monitoring_insights/get` to retrieve the updated insights.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashFlowUpdatesLowBalanceWebhook {
    /// `CASH_FLOW_UPDATES`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `LOW_BALANCE_DETECTED`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    #[serde(rename = "status")]
    pub status: models::MonitoringInsightsStatus,
    /// The `user_id` that the report is associated with
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "environment")]
    pub environment: models::WebhookEnvironmentValues,
}

impl CashFlowUpdatesLowBalanceWebhook {
    /// For each user's item enabled for Cash Flow Updates, this webhook will fire when an update detects a balance below $100. Upon receiving the webhook, call `/cra/monitoring_insights/get` to retrieve the updated insights.
    pub fn new(webhook_type: String, webhook_code: String, status: models::MonitoringInsightsStatus, user_id: String, environment: models::WebhookEnvironmentValues) -> CashFlowUpdatesLowBalanceWebhook {
        CashFlowUpdatesLowBalanceWebhook {
            webhook_type,
            webhook_code,
            status,
            user_id,
            environment,
        }
    }
}

