/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CashflowReportTransactionsGetRequestOptions : An optional object to be used with the request. If specified, `options` must not be `null`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashflowReportTransactionsGetRequestOptions {
    /// A list of `account_ids` to retrieve for the Item  Note: An error will be returned if a provided `account_id` is not associated with the Item.
    #[serde(rename = "account_ids", skip_serializing_if = "Option::is_none")]
    pub account_ids: Option<Vec<String>>,
}

impl CashflowReportTransactionsGetRequestOptions {
    /// An optional object to be used with the request. If specified, `options` must not be `null`.
    pub fn new() -> CashflowReportTransactionsGetRequestOptions {
        CashflowReportTransactionsGetRequestOptions {
            account_ids: None,
        }
    }
}

