/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CashflowReportGetResponse : CashflowReportGetResponse defines the response schema for `/cashflow_report/get`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashflowReportGetResponse {
    /// An array containing the `accounts` associated with the Item for which transactions are being returned. Each transaction can be mapped to its corresponding account via the `account_id` field.
    #[serde(rename = "accounts")]
    pub accounts: Vec<models::BusinessAccount>,
    /// An array containing transactions from the account. Transactions are returned in reverse chronological order, with the most recent at the beginning of the array. The maximum number of transactions returned is determined by the `count` parameter.
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::CashflowReportTransaction>,
    /// The total number of transactions available within the date range specified. If `total_transactions` is larger than the size of the `transactions` array, more transactions are available and can be fetched via manipulating the `offset` parameter.
    #[serde(rename = "total_transactions")]
    pub total_transactions: i32,
    #[serde(rename = "item")]
    pub item: models::Item,
    /// Cursor used for fetching any future updates after the latest update provided in this response.
    #[serde(rename = "next_cursor")]
    pub next_cursor: String,
    /// Represents if more than requested count of transactions exists to be fetched
    #[serde(rename = "has_more")]
    pub has_more: bool,
    /// The last successful update time in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format ( `YYYY-MM-DDTHH:mm:ssZ` )
    #[serde(rename = "last_successful_update_time")]
    pub last_successful_update_time: chrono::DateTime<chrono::FixedOffset>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl CashflowReportGetResponse {
    /// CashflowReportGetResponse defines the response schema for `/cashflow_report/get`
    pub fn new(accounts: Vec<models::BusinessAccount>, transactions: Vec<models::CashflowReportTransaction>, total_transactions: i32, item: models::Item, next_cursor: String, has_more: bool, last_successful_update_time: chrono::DateTime<chrono::FixedOffset>, request_id: String) -> CashflowReportGetResponse {
        CashflowReportGetResponse {
            accounts,
            transactions,
            total_transactions,
            item,
            next_cursor,
            has_more,
            last_successful_update_time,
            request_id,
        }
    }
}

