/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClientUserIdentityAddress : User address information.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientUserIdentityAddress {
    /// First line of street address.
    #[serde(rename = "street_1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub street_1: Option<Option<String>>,
    /// Second line of street address.
    #[serde(rename = "street_2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub street_2: Option<Option<String>>,
    /// City name.
    #[serde(rename = "city", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub city: Option<Option<String>>,
    /// State, province or region.
    #[serde(rename = "region", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub region: Option<Option<String>>,
    /// Country code.
    #[serde(rename = "country")]
    pub country: String,
    /// Postal or ZIP code.
    #[serde(rename = "postal_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<Option<String>>,
    /// Indicates whether this is the primary address for the User.
    #[serde(rename = "primary")]
    pub primary: bool,
}

impl ClientUserIdentityAddress {
    /// User address information.
    pub fn new(country: String, primary: bool) -> ClientUserIdentityAddress {
        ClientUserIdentityAddress {
            street_1: None,
            street_2: None,
            city: None,
            region: None,
            country,
            postal_code: None,
            primary,
        }
    }
}

