/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClientCustomization : Custom client fields
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientCustomization {
    /// Custom entity ID that maps to a merchant or counterparty. This is different from the `merchant_entity_id` as well as the `entity_id` on the counterparties object to meet client specific needs.
    #[serde(rename = "custom_entity_id", skip_serializing_if = "Option::is_none")]
    pub custom_entity_id: Option<String>,
}

impl ClientCustomization {
    /// Custom client fields
    pub fn new() -> ClientCustomization {
        ClientCustomization {
            custom_entity_id: None,
        }
    }
}

