/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConsumerReportPdfGetRequest : ConsumerReportPDFGetRequest defines the request schema for `/consumer_report/pdf/get`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConsumerReportPdfGetRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// The user token associated with the User data is being requested for. This field is used only by customers with pre-existing integrations that already use the `user_token` field. All other customers should use the `user_id` instead. For more details, see [New User APIs](https://plaid.com/docs/api/users/user-apis).
    #[serde(rename = "user_token")]
    pub user_token: String,
}

impl ConsumerReportPdfGetRequest {
    /// ConsumerReportPDFGetRequest defines the request schema for `/consumer_report/pdf/get`
    pub fn new(user_token: String) -> ConsumerReportPdfGetRequest {
        ConsumerReportPdfGetRequest {
            client_id: None,
            secret: None,
            user_token,
        }
    }
}

