/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CountryCode : ISO-3166-1 alpha-2 country code standard.
/// ISO-3166-1 alpha-2 country code standard.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CountryCode {
    #[serde(rename = "US")]
    Us,
    #[serde(rename = "GB")]
    Gb,
    #[serde(rename = "ES")]
    Es,
    #[serde(rename = "NL")]
    Nl,
    #[serde(rename = "FR")]
    Fr,
    #[serde(rename = "IE")]
    Ie,
    #[serde(rename = "CA")]
    Ca,

}

impl std::fmt::Display for CountryCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Us => write!(f, "US"),
            Self::Gb => write!(f, "GB"),
            Self::Es => write!(f, "ES"),
            Self::Nl => write!(f, "NL"),
            Self::Fr => write!(f, "FR"),
            Self::Ie => write!(f, "IE"),
            Self::Ca => write!(f, "CA"),
        }
    }
}

impl Default for CountryCode {
    fn default() -> CountryCode {
        Self::Us
    }
}

