/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CounterpartyNumbers : Account numbers associated with the counterparty, when available. This field is currently only filled in for select financial institutions in Europe.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CounterpartyNumbers {
    #[serde(rename = "bacs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bacs: Option<Option<Box<models::CounterpartyNumbersBacs>>>,
    #[serde(rename = "international", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub international: Option<Option<Box<models::CounterpartyNumbersInternational>>>,
}

impl CounterpartyNumbers {
    /// Account numbers associated with the counterparty, when available. This field is currently only filled in for select financial institutions in Europe.
    pub fn new() -> CounterpartyNumbers {
        CounterpartyNumbers {
            bacs: None,
            international: None,
        }
    }
}

