/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraPartnerInsightsBaseFicoScoreVersion : The version of the base FICO score model.
/// The version of the base FICO score model.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CraPartnerInsightsBaseFicoScoreVersion {
    #[serde(rename = "8")]
    Variant8,
    #[serde(rename = "9")]
    Variant9,
    #[serde(rename = "10")]
    Variant10,
    #[serde(rename = "10T")]
    Variant10T,

}

impl std::fmt::Display for CraPartnerInsightsBaseFicoScoreVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant8 => write!(f, "8"),
            Self::Variant9 => write!(f, "9"),
            Self::Variant10 => write!(f, "10"),
            Self::Variant10T => write!(f, "10T"),
        }
    }
}

impl Default for CraPartnerInsightsBaseFicoScoreVersion {
    fn default() -> CraPartnerInsightsBaseFicoScoreVersion {
        Self::Variant8
    }
}

