/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraVoaReportTransactionsInsights : Transaction data associated with the account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraVoaReportTransactionsInsights {
    /// Transaction history associated with the account.
    #[serde(rename = "all_transactions")]
    pub all_transactions: Vec<models::BaseReportTransaction>,
    /// The latest timeframe provided by the FI, in an ISO 8601 format (YYYY-MM-DD).
    #[serde(rename = "end_date", deserialize_with = "Option::deserialize")]
    pub end_date: Option<chrono::NaiveDate>,
    /// The earliest timeframe provided by the FI, in an ISO 8601 format (YYYY-MM-DD).
    #[serde(rename = "start_date", deserialize_with = "Option::deserialize")]
    pub start_date: Option<chrono::NaiveDate>,
}

impl CraVoaReportTransactionsInsights {
    /// Transaction data associated with the account.
    pub fn new(all_transactions: Vec<models::BaseReportTransaction>, end_date: Option<chrono::NaiveDate>, start_date: Option<chrono::NaiveDate>) -> CraVoaReportTransactionsInsights {
        CraVoaReportTransactionsInsights {
            all_transactions,
            end_date,
            start_date,
        }
    }
}

