/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraPartnerInsights : The Partner Insights report of the bank data for an end user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraPartnerInsights {
    /// A unique identifier associated with the Partner Insights object.
    #[serde(rename = "report_id", skip_serializing_if = "Option::is_none")]
    pub report_id: Option<String>,
    /// The time when the Partner Insights report was generated.
    #[serde(rename = "generated_time", skip_serializing_if = "Option::is_none")]
    pub generated_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Client-generated identifier, which can be used by lenders to track loan applications.
    #[serde(rename = "client_report_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client_report_id: Option<Option<String>>,
    #[serde(rename = "fico", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fico: Option<Option<Box<models::CraPartnerInsightsFicoResults>>>,
    #[serde(rename = "prism", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prism: Option<Option<models::CraPartnerInsightsPrism>>,
    /// The list of Items used in the report along with the associated metadata about the Item.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::CraPartnerInsightsItem>>,
}

impl CraPartnerInsights {
    /// The Partner Insights report of the bank data for an end user.
    pub fn new() -> CraPartnerInsights {
        CraPartnerInsights {
            report_id: None,
            generated_time: None,
            client_report_id: None,
            fico: None,
            prism: None,
            items: None,
        }
    }
}

