/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraPartnerInsightsFicoInput : Configurations for FICO products used in the Partner Insights flow.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraPartnerInsightsFicoInput {
    /// ID provided by FICO that uniquely identifies the lender. Required for UltraFICO score generation. Sometimes referred to as Lender Org ID.
    #[serde(rename = "fico_lender_id")]
    pub fico_lender_id: String,
    /// Client-generated identifier that uniquely identifies the FICO Application ID across FICO systems.
    #[serde(rename = "lender_application_id")]
    pub lender_application_id: String,
    /// A list of UltraFICO scoring requests. Each request contains all configuration required to generate an UltraFICO score.
    #[serde(rename = "ultrafico_score_requests")]
    pub ultrafico_score_requests: Vec<models::CraPartnerInsightsUltraFicoScoreRequest>,
}

impl CraPartnerInsightsFicoInput {
    /// Configurations for FICO products used in the Partner Insights flow.
    pub fn new(fico_lender_id: String, lender_application_id: String, ultrafico_score_requests: Vec<models::CraPartnerInsightsUltraFicoScoreRequest>) -> CraPartnerInsightsFicoInput {
        CraPartnerInsightsFicoInput {
            fico_lender_id,
            lender_application_id,
            ultrafico_score_requests,
        }
    }
}

