/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCheckReportVerificationPdfReportType : The type of verification PDF report to fetch.
/// The type of verification PDF report to fetch.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CraCheckReportVerificationPdfReportType {
    #[serde(rename = "voa")]
    Voa,
    #[serde(rename = "employment_refresh")]
    EmploymentRefresh,

}

impl std::fmt::Display for CraCheckReportVerificationPdfReportType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Voa => write!(f, "voa"),
            Self::EmploymentRefresh => write!(f, "employment_refresh"),
        }
    }
}

impl Default for CraCheckReportVerificationPdfReportType {
    fn default() -> CraCheckReportVerificationPdfReportType {
        Self::Voa
    }
}

