/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraIncomeInsightsUserSummary : Aggregated summary of all income streams for this user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraIncomeInsightsUserSummary {
    /// List of a user's aggregated income metrics for each currency.
    #[serde(rename = "income_metrics")]
    pub income_metrics: Vec<models::CraIncomeMetrics>,
}

impl CraIncomeInsightsUserSummary {
    /// Aggregated summary of all income streams for this user.
    pub fn new(income_metrics: Vec<models::CraIncomeMetrics>) -> CraIncomeInsightsUserSummary {
        CraIncomeInsightsUserSummary {
            income_metrics,
        }
    }
}

