/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraPartnerInsightsUltraFicoScoreRequest : Configuration required to generate a single UltraFICO score.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraPartnerInsightsUltraFicoScoreRequest {
    #[serde(rename = "ultrafico_score_version")]
    pub ultrafico_score_version: models::CraPartnerInsightsUltraFicoScoreVersion,
    /// FICO identifier for a particular scoring request. Should only be provided by UltraFICO as part of the FICO-led Flow.
    #[serde(rename = "fico_scoring_request_id", skip_serializing_if = "Option::is_none")]
    pub fico_scoring_request_id: Option<String>,
    /// Client-generated identifier that can be used to correlate scoring requests and scoring results.
    #[serde(rename = "request_correlation_id", skip_serializing_if = "Option::is_none")]
    pub request_correlation_id: Option<String>,
    #[serde(rename = "base_fico_score")]
    pub base_fico_score: Box<models::CraPartnerInsightsBaseFicoScore>,
}

impl CraPartnerInsightsUltraFicoScoreRequest {
    /// Configuration required to generate a single UltraFICO score.
    pub fn new(ultrafico_score_version: models::CraPartnerInsightsUltraFicoScoreVersion, base_fico_score: models::CraPartnerInsightsBaseFicoScore) -> CraPartnerInsightsUltraFicoScoreRequest {
        CraPartnerInsightsUltraFicoScoreRequest {
            ultrafico_score_version,
            fico_scoring_request_id: None,
            request_correlation_id: None,
            base_fico_score: Box::new(base_fico_score),
        }
    }
}

