/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraEmploymentRefreshReportAccount : Employment Refresh Report information about an account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraEmploymentRefreshReportAccount {
    /// Plaid’s unique identifier for the account. This value will not change unless Plaid can't reconcile the account with the data returned by the financial institution. This may occur, for example, when the name of the account changes. If this happens a new `account_id` will be assigned to the account.  If an account with a specific `account_id` disappears instead of changing, the account is likely closed. Closed accounts are not returned by the Plaid API.  Like all Plaid identifiers, the `account_id` is case sensitive.
    #[serde(rename = "account_id")]
    pub account_id: String,
    /// The name of the account, either assigned by the user or by the financial institution itself.
    #[serde(rename = "name")]
    pub name: String,
    /// The official name of the account as given by the financial institution.
    #[serde(rename = "official_name", deserialize_with = "Option::deserialize")]
    pub official_name: Option<String>,
    #[serde(rename = "type")]
    pub r#type: models::AccountType,
    #[serde(rename = "subtype", deserialize_with = "Option::deserialize")]
    pub subtype: Option<models::AccountSubtype>,
    /// Transaction history associated with the account for the Employment Refresh Report. Note that this transaction differs from a Base Report transaction in that it will only be deposits, and the amounts will be omitted.
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::CraEmploymentRefreshReportTransaction>,
}

impl CraEmploymentRefreshReportAccount {
    /// Employment Refresh Report information about an account.
    pub fn new(account_id: String, name: String, official_name: Option<String>, r#type: models::AccountType, subtype: Option<models::AccountSubtype>, transactions: Vec<models::CraEmploymentRefreshReportTransaction>) -> CraEmploymentRefreshReportAccount {
        CraEmploymentRefreshReportAccount {
            account_id,
            name,
            official_name,
            r#type,
            subtype,
            transactions,
        }
    }
}

