/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraVerificationReport : Contains data for the CRA Home Lending Report.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraVerificationReport {
    /// The unique identifier associated with the Home Lending Report object. This ID will be the same as the Base Report ID.
    #[serde(rename = "report_id")]
    pub report_id: String,
    /// A unique token that can be shared with GSEs in order to provide them access to the report. This is automatically created during report generation when GSE options are specified.
    #[serde(rename = "gse_reference_id", skip_serializing_if = "Option::is_none")]
    pub gse_reference_id: Option<String>,
    /// Client-generated identifier, which can be used by lenders to track loan applications.
    #[serde(rename = "client_report_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client_report_id: Option<Option<String>>,
    #[serde(rename = "voa", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub voa: Option<Option<models::CraVoaReport>>,
    #[serde(rename = "employment_refresh", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub employment_refresh: Option<Option<models::CraEmploymentRefreshReport>>,
}

impl CraVerificationReport {
    /// Contains data for the CRA Home Lending Report.
    pub fn new(report_id: String) -> CraVerificationReport {
        CraVerificationReport {
            report_id,
            gse_reference_id: None,
            client_report_id: None,
            voa: None,
            employment_refresh: None,
        }
    }
}

