/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraIncomeCategory : The income category for a given stream. The streams returned in the response will be filtered based on these primary and secondary income categories.  See the [Income V2 Category Taxonomy](https://plaid.com/documents/income-v2-category-taxonomy.csv) for a full list of income categories.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraIncomeCategory {
    /// A high level category that communicates the broad category of the stream.
    #[serde(rename = "primary")]
    pub primary: String,
    /// A granular category conveying the stream's intent.
    #[serde(rename = "secondary")]
    pub secondary: String,
}

impl CraIncomeCategory {
    /// The income category for a given stream. The streams returned in the response will be filtered based on these primary and secondary income categories.  See the [Income V2 Category Taxonomy](https://plaid.com/documents/income-v2-category-taxonomy.csv) for a full list of income categories.
    pub fn new(primary: String, secondary: String) -> CraIncomeCategory {
        CraIncomeCategory {
            primary,
            secondary,
        }
    }
}

