/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraIncomeTransactionOutlier : Metadata on whether this income transaction is an outlier.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraIncomeTransactionOutlier {
    /// Indicates whether an income transaction amount is unusually high compared to the amounts for that stream.
    #[serde(rename = "is_outlier")]
    pub is_outlier: bool,
    /// The amount that the transaction differs from the stream average transaction amount.
    #[serde(rename = "amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Option<f64>>,
}

impl CraIncomeTransactionOutlier {
    /// Metadata on whether this income transaction is an outlier.
    pub fn new(is_outlier: bool) -> CraIncomeTransactionOutlier {
        CraIncomeTransactionOutlier {
            is_outlier,
            amount: None,
        }
    }
}

