/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraPartnerInsightsUltraFicoScore : The calculated UltraFICO score.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraPartnerInsightsUltraFicoScore {
    #[serde(rename = "ultrafico_score_version")]
    pub ultrafico_score_version: models::CraPartnerInsightsUltraFicoScoreVersion,
    /// Numeric value of the UltraFICO score.
    #[serde(rename = "score")]
    pub score: i32,
    /// The first reason code associated with the score.
    #[serde(rename = "reason_code_1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason_code_1: Option<Option<String>>,
    /// The second reason code associated with the score.
    #[serde(rename = "reason_code_2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason_code_2: Option<Option<String>>,
    /// The third reason code associated with the score.
    #[serde(rename = "reason_code_3", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason_code_3: Option<Option<String>>,
    /// The fourth reason code associated with the score.
    #[serde(rename = "reason_code_4", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason_code_4: Option<Option<String>>,
    /// The first positive reason code associated with the score.
    #[serde(rename = "positive_reason_code_1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub positive_reason_code_1: Option<Option<String>>,
    /// The second positive reason code associated with the score.
    #[serde(rename = "positive_reason_code_2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub positive_reason_code_2: Option<Option<String>>,
    /// The third positive reason code associated with the score.
    #[serde(rename = "positive_reason_code_3", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub positive_reason_code_3: Option<Option<String>>,
    /// The fourth positive reason code associated with the score.
    #[serde(rename = "positive_reason_code_4", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub positive_reason_code_4: Option<Option<String>>,
    /// Whether inquiries adversely affected the score but were not represented in one of the four reason codes. Sometimes referred to as the FACTA Flag.
    #[serde(rename = "did_inquiries_adversely_affect_score", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub did_inquiries_adversely_affect_score: Option<Option<bool>>,
}

impl CraPartnerInsightsUltraFicoScore {
    /// The calculated UltraFICO score.
    pub fn new(ultrafico_score_version: models::CraPartnerInsightsUltraFicoScoreVersion, score: i32) -> CraPartnerInsightsUltraFicoScore {
        CraPartnerInsightsUltraFicoScore {
            ultrafico_score_version,
            score,
            reason_code_1: None,
            reason_code_2: None,
            reason_code_3: None,
            reason_code_4: None,
            positive_reason_code_1: None,
            positive_reason_code_2: None,
            positive_reason_code_3: None,
            positive_reason_code_4: None,
            did_inquiries_adversely_affect_score: None,
        }
    }
}

