/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraBankIncomeIncomeProvider : The object containing data about the income provider.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraBankIncomeIncomeProvider {
    /// The name of the income provider.
    #[serde(rename = "name")]
    pub name: String,
    /// Indicates whether the income provider name is normalized by comparing it against a canonical set of known providers.
    #[serde(rename = "is_normalized")]
    pub is_normalized: bool,
}

impl CraBankIncomeIncomeProvider {
    /// The object containing data about the income provider.
    pub fn new(name: String, is_normalized: bool) -> CraBankIncomeIncomeProvider {
        CraBankIncomeIncomeProvider {
            name,
            is_normalized,
        }
    }
}

