/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraVoaReportAttributes : Attributes for the VOA report.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraVoaReportAttributes {
    #[serde(rename = "total_inflow_amount", deserialize_with = "Option::deserialize")]
    pub total_inflow_amount: Option<models::TotalReportInflowAmount>,
    #[serde(rename = "total_outflow_amount", deserialize_with = "Option::deserialize")]
    pub total_outflow_amount: Option<models::TotalReportOutflowAmount>,
}

impl CraVoaReportAttributes {
    /// Attributes for the VOA report.
    pub fn new(total_inflow_amount: Option<models::TotalReportInflowAmount>, total_outflow_amount: Option<models::TotalReportOutflowAmount>) -> CraVoaReportAttributes {
        CraVoaReportAttributes {
            total_inflow_amount,
            total_outflow_amount,
        }
    }
}

