/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraPartnerInsightsBureau : The credit bureau that provided the base FICO score.
/// The credit bureau that provided the base FICO score.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CraPartnerInsightsBureau {
    #[serde(rename = "EQUIFAX")]
    Equifax,
    #[serde(rename = "EXPERIAN")]
    Experian,
    #[serde(rename = "TRANSUNION")]
    Transunion,

}

impl std::fmt::Display for CraPartnerInsightsBureau {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Equifax => write!(f, "EQUIFAX"),
            Self::Experian => write!(f, "EXPERIAN"),
            Self::Transunion => write!(f, "TRANSUNION"),
        }
    }
}

impl Default for CraPartnerInsightsBureau {
    fn default() -> CraPartnerInsightsBureau {
        Self::Equifax
    }
}

