/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCheckReportVerificationGetEmploymentRefreshOptions : Defines configuration options for the Employment Refresh Report.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraCheckReportVerificationGetEmploymentRefreshOptions {
    /// The number of days of data to request for the report. This field is required if an Employment Refresh Report is requested. Maximum is 731.
    #[serde(rename = "days_requested")]
    pub days_requested: i32,
}

impl CraCheckReportVerificationGetEmploymentRefreshOptions {
    /// Defines configuration options for the Employment Refresh Report.
    pub fn new(days_requested: i32) -> CraCheckReportVerificationGetEmploymentRefreshOptions {
        CraCheckReportVerificationGetEmploymentRefreshOptions {
            days_requested,
        }
    }
}

