/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraAnnualIncomeValues : Modeled estimate of the annual income.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraAnnualIncomeValues {
    /// Gross Income modeled from trends of observed transactions.
    #[serde(rename = "gross_income")]
    pub gross_income: f64,
    /// Net Income estimated from observed transactions.
    #[serde(rename = "net_income")]
    pub net_income: f64,
}

impl CraAnnualIncomeValues {
    /// Modeled estimate of the annual income.
    pub fn new(gross_income: f64, net_income: f64) -> CraAnnualIncomeValues {
        CraAnnualIncomeValues {
            gross_income,
            net_income,
        }
    }
}

