/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCheckReportPartnerInsightsGetOptions : Deprecated, specify `partner_insights.prism_versions` instead.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraCheckReportPartnerInsightsGetOptions {
    #[serde(rename = "prism_versions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prism_versions: Option<Option<Box<models::PrismVersionsDeprecated>>>,
}

impl CraCheckReportPartnerInsightsGetOptions {
    /// Deprecated, specify `partner_insights.prism_versions` instead.
    pub fn new() -> CraCheckReportPartnerInsightsGetOptions {
        CraCheckReportPartnerInsightsGetOptions {
            prism_versions: None,
        }
    }
}

