/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCreditProfileReportGetRequest : CraCreditProfileReportGetRequest defines the request schema for `/cra/credit_profile/report/get`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraCreditProfileReportGetRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// A unique user identifier, created by `/user/create`. Integrations that began using `/user/create` after December 10, 2025 use this field to identify a user instead of the `user_token`. For more details, see [new user APIs](https://plaid.com/docs/api/users/user-apis).
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "consumer_report_permissible_purpose")]
    pub consumer_report_permissible_purpose: models::ConsumerReportPermissiblePurpose,
    /// Client-generated identifier, which can be used by lenders to track loan applications.
    #[serde(rename = "client_report_id")]
    pub client_report_id: String,
    #[serde(rename = "report_type")]
    pub report_type: models::CraCreditProfileReportType,
    #[serde(rename = "inquiry_type")]
    pub inquiry_type: models::CraCreditProfileInquiryType,
    #[serde(rename = "version")]
    pub version: models::CraCreditProfileReportVersion,
}

impl CraCreditProfileReportGetRequest {
    /// CraCreditProfileReportGetRequest defines the request schema for `/cra/credit_profile/report/get`.
    pub fn new(user_id: String, consumer_report_permissible_purpose: models::ConsumerReportPermissiblePurpose, client_report_id: String, report_type: models::CraCreditProfileReportType, inquiry_type: models::CraCreditProfileInquiryType, version: models::CraCreditProfileReportVersion) -> CraCreditProfileReportGetRequest {
        CraCreditProfileReportGetRequest {
            client_id: None,
            secret: None,
            user_id,
            consumer_report_permissible_purpose,
            client_report_id,
            report_type,
            inquiry_type,
            version,
        }
    }
}

