/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraVoaReportAccountHistoricalBalance : An object representing a balance held by an account in the past.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraVoaReportAccountHistoricalBalance {
    /// The total amount of funds in the account, calculated from the `current` balance in the `balance` object by subtracting inflows and adding back outflows according to the posted date of each transaction.
    #[serde(rename = "current")]
    pub current: f64,
    /// The date of the calculated historical balance, in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
    #[serde(rename = "date")]
    pub date: chrono::NaiveDate,
    /// The ISO-4217 currency code of the balance. Always `null` if `unofficial_currency_code` is non-`null`.
    #[serde(rename = "iso_currency_code", deserialize_with = "Option::deserialize")]
    pub iso_currency_code: Option<String>,
    /// The unofficial currency code associated with the balance. Always `null` if `iso_currency_code` is non-`null`.  See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `unofficial_currency_code`s.
    #[serde(rename = "unofficial_currency_code", deserialize_with = "Option::deserialize")]
    pub unofficial_currency_code: Option<String>,
}

impl CraVoaReportAccountHistoricalBalance {
    /// An object representing a balance held by an account in the past.
    pub fn new(current: f64, date: chrono::NaiveDate, iso_currency_code: Option<String>, unofficial_currency_code: Option<String>) -> CraVoaReportAccountHistoricalBalance {
        CraVoaReportAccountHistoricalBalance {
            current,
            date,
            iso_currency_code,
            unofficial_currency_code,
        }
    }
}

