/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCashflowInsightsReport : Contains data for the CRA Cashflow Insights Report.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraCashflowInsightsReport {
    /// The unique identifier associated with the report object.
    #[serde(rename = "report_id")]
    pub report_id: String,
    /// The time when the report was generated.
    #[serde(rename = "generated_time")]
    pub generated_time: chrono::DateTime<chrono::FixedOffset>,
    /// A map of cash flow attributes, where the key is a string, and the value is a float, int, or boolean. The specific list of attributes will depend on the cash flow attributes version used. For a full list of attributes, contact your account manager.
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<serde_json::Value>,
}

impl CraCashflowInsightsReport {
    /// Contains data for the CRA Cashflow Insights Report.
    pub fn new(report_id: String, generated_time: chrono::DateTime<chrono::FixedOffset>) -> CraCashflowInsightsReport {
        CraCashflowInsightsReport {
            report_id,
            generated_time,
            attributes: None,
        }
    }
}

