/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraIncomeNextPayment : Metadata of the income stream's next payment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraIncomeNextPayment {
    /// The expected date of the income stream's next payment. The date will be returned in an ISO 8601 format (YYYY-MM-DD).
    #[serde(rename = "date")]
    pub date: chrono::NaiveDate,
}

impl CraIncomeNextPayment {
    /// Metadata of the income stream's next payment.
    pub fn new(date: chrono::NaiveDate) -> CraIncomeNextPayment {
        CraIncomeNextPayment {
            date,
        }
    }
}

