/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCheckReportNetworkInsightsGetOptions : Defines configuration options to generate Network Insights
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraCheckReportNetworkInsightsGetOptions {
    #[serde(rename = "network_insights_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub network_insights_version: Option<Option<models::NetworkInsightsVersion>>,
}

impl CraCheckReportNetworkInsightsGetOptions {
    /// Defines configuration options to generate Network Insights
    pub fn new() -> CraCheckReportNetworkInsightsGetOptions {
        CraCheckReportNetworkInsightsGetOptions {
            network_insights_version: None,
        }
    }
}

