/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCheckReportVerificationGetResponse : CraCheckReportVerificationGetResponse defines the response schema for `/cra/check_report/verification/get`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraCheckReportVerificationGetResponse {
    #[serde(rename = "report")]
    pub report: models::CraVerificationReport,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
    /// If the home lending report generation was successful but a subset of data could not be retrieved, this array will contain information about the errors causing information to be missing.
    #[serde(rename = "warnings")]
    pub warnings: Vec<models::CheckReportWarning>,
}

impl CraCheckReportVerificationGetResponse {
    /// CraCheckReportVerificationGetResponse defines the response schema for `/cra/check_report/verification/get`.
    pub fn new(report: models::CraVerificationReport, request_id: String, warnings: Vec<models::CheckReportWarning>) -> CraCheckReportVerificationGetResponse {
        CraCheckReportVerificationGetResponse {
            report,
            request_id,
            warnings,
        }
    }
}

