/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCreditProfileLendScore : An individual LendScore result within a credit profile report.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraCreditProfileLendScore {
    /// The score returned by the LendScore model. Will be an integer in the range 1 to 99. Higher scores indicate lower credit risk.
    #[serde(rename = "score", deserialize_with = "Option::deserialize")]
    pub score: Option<i32>,
    /// The reasons for an individual having risk according to the LendScore. For a full list of possible reason codes and a mapping of reason codes to human-readable reasons, contact your Plaid Account Manager. Different LendScore versions will use different sets of reason codes.
    #[serde(rename = "reason_codes")]
    pub reason_codes: Vec<String>,
    /// The variant identifier for this LendScore result.
    #[serde(rename = "variant")]
    pub variant: String,
    /// Human-readable description of why the LendScore could not be computed.
    #[serde(rename = "error_reason", deserialize_with = "Option::deserialize")]
    pub error_reason: Option<String>,
}

impl CraCreditProfileLendScore {
    /// An individual LendScore result within a credit profile report.
    pub fn new(score: Option<i32>, reason_codes: Vec<String>, variant: String, error_reason: Option<String>) -> CraCreditProfileLendScore {
        CraCreditProfileLendScore {
            score,
            reason_codes,
            variant,
            error_reason,
        }
    }
}

