/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraVoaReportItem : A representation of an Item within a VOA report.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraVoaReportItem {
    /// Data about each of the accounts open on the Item.
    #[serde(rename = "accounts")]
    pub accounts: Vec<models::CraVoaReportAccount>,
    /// The full financial institution name associated with the Item.
    #[serde(rename = "institution_name")]
    pub institution_name: String,
    /// The id of the financial institution associated with the Item.
    #[serde(rename = "institution_id")]
    pub institution_id: String,
    /// The `item_id` of the Item associated with this webhook, warning, or error
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// The date and time when this Item’s data was last retrieved from the financial institution, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "last_update_time")]
    pub last_update_time: chrono::DateTime<chrono::FixedOffset>,
}

impl CraVoaReportItem {
    /// A representation of an Item within a VOA report.
    pub fn new(accounts: Vec<models::CraVoaReportAccount>, institution_name: String, institution_id: String, item_id: String, last_update_time: chrono::DateTime<chrono::FixedOffset>) -> CraVoaReportItem {
        CraVoaReportItem {
            accounts,
            institution_name,
            institution_id,
            item_id,
            last_update_time,
        }
    }
}

