/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraIncomeStreamInsights : Modeled insights for a given income stream.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraIncomeStreamInsights {
    #[serde(rename = "income_category")]
    pub income_category: models::CraIncomeCategory,
    #[serde(rename = "pay_frequency")]
    pub pay_frequency: models::CreditBankIncomePayFrequency,
    #[serde(rename = "income_provider", deserialize_with = "Option::deserialize")]
    pub income_provider: Option<models::CraBankIncomeIncomeProvider>,
    #[serde(rename = "status")]
    pub status: models::CraBankIncomeStatus,
    #[serde(rename = "next_payment", deserialize_with = "Option::deserialize")]
    pub next_payment: Option<models::CraIncomeNextPayment>,
}

impl CraIncomeStreamInsights {
    /// Modeled insights for a given income stream.
    pub fn new(income_category: models::CraIncomeCategory, pay_frequency: models::CreditBankIncomePayFrequency, income_provider: Option<models::CraBankIncomeIncomeProvider>, status: models::CraBankIncomeStatus, next_payment: Option<models::CraIncomeNextPayment>) -> CraIncomeStreamInsights {
        CraIncomeStreamInsights {
            income_category,
            pay_frequency,
            income_provider,
            status,
            next_payment,
        }
    }
}

