/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraVoaReportAccount : VOA Report information about an account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraVoaReportAccount {
    /// Plaid’s unique identifier for the account. This value will not change unless Plaid can't reconcile the account with the data returned by the financial institution. This may occur, for example, when the name of the account changes. If this happens a new `account_id` will be assigned to the account.  If an account with a specific `account_id` disappears instead of changing, the account is likely closed. Closed accounts are not returned by the Plaid API.  Like all Plaid identifiers, the `account_id` is case sensitive.
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "balances")]
    pub balances: models::CraVoaReportAccountBalances,
    /// The information about previously submitted valid dispute statements by the consumer
    #[serde(rename = "consumer_disputes")]
    pub consumer_disputes: Vec<models::ConsumerDispute>,
    /// The last 2-4 alphanumeric characters of an account's official account number. Note that the mask may be non-unique between an Item's accounts, and it may also not match the mask that the bank displays to the user.
    #[serde(rename = "mask", deserialize_with = "Option::deserialize")]
    pub mask: Option<String>,
    /// The name of the account, either assigned by the user or by the financial institution itself.
    #[serde(rename = "name")]
    pub name: String,
    /// The official name of the account as given by the financial institution.
    #[serde(rename = "official_name", deserialize_with = "Option::deserialize")]
    pub official_name: Option<String>,
    #[serde(rename = "type")]
    pub r#type: models::AccountType,
    #[serde(rename = "subtype", deserialize_with = "Option::deserialize")]
    pub subtype: Option<models::AccountSubtype>,
    /// The duration of transaction history available within this report for this Item, typically defined as the time since the date of the earliest transaction in that account.
    #[serde(rename = "days_available")]
    pub days_available: f64,
    #[serde(rename = "transactions_insights")]
    pub transactions_insights: models::CraVoaReportTransactionsInsights,
    /// Data returned by the financial institution about the account owner or owners.
    #[serde(rename = "owners")]
    pub owners: Vec<models::Owner>,
    #[serde(rename = "ownership_type", deserialize_with = "Option::deserialize")]
    pub ownership_type: Option<models::OwnershipType>,
    #[serde(rename = "investments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub investments: Option<Option<models::BaseReportInvestments>>,
}

impl CraVoaReportAccount {
    /// VOA Report information about an account.
    pub fn new(account_id: String, balances: models::CraVoaReportAccountBalances, consumer_disputes: Vec<models::ConsumerDispute>, mask: Option<String>, name: String, official_name: Option<String>, r#type: models::AccountType, subtype: Option<models::AccountSubtype>, days_available: f64, transactions_insights: models::CraVoaReportTransactionsInsights, owners: Vec<models::Owner>, ownership_type: Option<models::OwnershipType>) -> CraVoaReportAccount {
        CraVoaReportAccount {
            account_id,
            balances,
            consumer_disputes,
            mask,
            name,
            official_name,
            r#type,
            subtype,
            days_available,
            transactions_insights,
            owners,
            ownership_type,
            investments: None,
        }
    }
}

