/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraMonitoringInsightsItem : An object representing a Monitoring Insights Item
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraMonitoringInsightsItem {
    /// The date and time when the specific insights were generated (per-item), in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (e.g. \"2018-04-12T03:32:11Z\").
    #[serde(rename = "date_generated")]
    pub date_generated: chrono::DateTime<chrono::FixedOffset>,
    /// The `item_id` of the Item associated with the insights
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// The id of the financial institution associated with the Item.
    #[serde(rename = "institution_id")]
    pub institution_id: String,
    /// The full financial institution name associated with the Item.
    #[serde(rename = "institution_name")]
    pub institution_name: String,
    #[serde(rename = "status")]
    pub status: models::MonitoringInsightsItemStatus,
    #[serde(rename = "insights", deserialize_with = "Option::deserialize")]
    pub insights: Option<models::MonitoringInsights>,
    /// Data about each of the accounts open on the Item.
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<models::BaseReportAccount>>,
}

impl CraMonitoringInsightsItem {
    /// An object representing a Monitoring Insights Item
    pub fn new(date_generated: chrono::DateTime<chrono::FixedOffset>, item_id: String, institution_id: String, institution_name: String, status: models::MonitoringInsightsItemStatus, insights: Option<models::MonitoringInsights>) -> CraMonitoringInsightsItem {
        CraMonitoringInsightsItem {
            date_generated,
            item_id,
            institution_id,
            institution_name,
            status,
            insights,
            accounts: None,
        }
    }
}

