/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraEmploymentRefreshReport : An object representing an Employment Refresh Report.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraEmploymentRefreshReport {
    /// The date and time when the Employment Refresh Report was created, in ISO 8601 format (e.g. \"2018-04-12T03:32:11Z\").
    #[serde(rename = "generated_time")]
    pub generated_time: chrono::DateTime<chrono::FixedOffset>,
    /// The number of days of transaction history that the Employment Refresh Report covers.
    #[serde(rename = "days_requested")]
    pub days_requested: f64,
    /// Data returned by Plaid about each of the Items included in the Employment Refresh Report.
    #[serde(rename = "items")]
    pub items: Vec<models::CraEmploymentRefreshReportItem>,
}

impl CraEmploymentRefreshReport {
    /// An object representing an Employment Refresh Report.
    pub fn new(generated_time: chrono::DateTime<chrono::FixedOffset>, days_requested: f64, items: Vec<models::CraEmploymentRefreshReportItem>) -> CraEmploymentRefreshReport {
        CraEmploymentRefreshReport {
            generated_time,
            days_requested,
            items,
        }
    }
}

