/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraUpgradeFailedWebhook : Fired when a Check Report upgrade attempt has failed
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraUpgradeFailedWebhook {
    /// `CHECK_REPORT`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `UPGRADE_FAILED`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    /// The `user_id` corresponding to the user the webhook has fired for.
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// An array of `item_id`s for items that failed to be upgraded by a Check Report upgrade attempt.
    #[serde(rename = "item_ids")]
    pub item_ids: Vec<String>,
    #[serde(rename = "environment")]
    pub environment: models::WebhookEnvironmentValues,
}

impl CraUpgradeFailedWebhook {
    /// Fired when a Check Report upgrade attempt has failed
    pub fn new(webhook_type: String, webhook_code: String, user_id: String, item_ids: Vec<String>, environment: models::WebhookEnvironmentValues) -> CraUpgradeFailedWebhook {
        CraUpgradeFailedWebhook {
            webhook_type,
            webhook_code,
            user_id,
            item_ids,
            environment,
        }
    }
}

