/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCheckReportFreddieMacGetResponse : CraCheckReportFreddieMacGetResponse defines the response schema for `/cra/check_report/freddie_mac/get`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraCheckReportFreddieMacGetResponse {
    #[serde(rename = "DEAL")]
    pub deal: models::CraCheckReportFreddieMacVerificationOfAssetsDeal,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
    /// The Verification Of Assets (VOA) schema version.
    #[serde(rename = "SchemaVersion")]
    pub schema_version: f64,
}

impl CraCheckReportFreddieMacGetResponse {
    /// CraCheckReportFreddieMacGetResponse defines the response schema for `/cra/check_report/freddie_mac/get`
    pub fn new(deal: models::CraCheckReportFreddieMacVerificationOfAssetsDeal, request_id: String, schema_version: f64) -> CraCheckReportFreddieMacGetResponse {
        CraCheckReportFreddieMacGetResponse {
            deal,
            request_id,
            schema_version,
        }
    }
}

