/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCheckReportIncomeInsightsGetOptions : Defines configuration options to generate Income Insights.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraCheckReportIncomeInsightsGetOptions {
    #[serde(rename = "income_insights_filter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub income_insights_filter: Option<Option<Box<models::IncomeInsightsFilter>>>,
    #[serde(rename = "income_insights_version", deserialize_with = "Option::deserialize")]
    pub income_insights_version: Option<models::IncomeInsightsVersion>,
}

impl CraCheckReportIncomeInsightsGetOptions {
    /// Defines configuration options to generate Income Insights.
    pub fn new(income_insights_version: Option<models::IncomeInsightsVersion>) -> CraCheckReportIncomeInsightsGetOptions {
        CraCheckReportIncomeInsightsGetOptions {
            income_insights_filter: None,
            income_insights_version,
        }
    }
}

