/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraIncomeInsights : The Check Income Insights Report for an end user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraIncomeInsights {
    /// The unique identifier associated with the Check Income Insights Report.
    #[serde(rename = "report_id", skip_serializing_if = "Option::is_none")]
    pub report_id: Option<String>,
    /// The time when the Check Income Insights Report was generated.
    #[serde(rename = "generated_time", skip_serializing_if = "Option::is_none")]
    pub generated_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The number of days requested by the customer for the Check Income Insights Report.
    #[serde(rename = "days_requested", skip_serializing_if = "Option::is_none")]
    pub days_requested: Option<i32>,
    /// Client-generated identifier, which can be used by lenders to track loan applications.
    #[serde(rename = "client_report_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client_report_id: Option<Option<String>>,
    /// The list of Items in the report along with the associated metadata about the Item.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::CraBankIncomeItem>>,
    #[serde(rename = "user_summary", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_summary: Option<Option<models::CraIncomeInsightsUserSummary>>,
    /// The list of income streams for this user.
    #[serde(rename = "income_streams", skip_serializing_if = "Option::is_none")]
    pub income_streams: Option<Vec<models::CraIncomeStream>>,
    #[serde(rename = "bank_income_summary", skip_serializing_if = "Option::is_none")]
    pub bank_income_summary: Option<models::CraBankIncomeSummary>,
    /// If data from the report was unable to be retrieved, the warnings object will contain information about the error that caused the data to be incomplete.
    #[serde(rename = "warnings", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Vec<models::CraBankIncomeWarning>>,
}

impl CraIncomeInsights {
    /// The Check Income Insights Report for an end user.
    pub fn new() -> CraIncomeInsights {
        CraIncomeInsights {
            report_id: None,
            generated_time: None,
            days_requested: None,
            client_report_id: None,
            items: None,
            user_summary: None,
            income_streams: None,
            bank_income_summary: None,
            warnings: None,
        }
    }
}

