/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraVoaReport : An object representing a VOA report.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CraVoaReport {
    /// The date and time when the VOA Report was created, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (e.g. \"2018-04-12T03:32:11Z\").
    #[serde(rename = "generated_time")]
    pub generated_time: chrono::DateTime<chrono::FixedOffset>,
    /// The number of days of transaction history that the VOA report covers.
    #[serde(rename = "days_requested")]
    pub days_requested: f64,
    /// Data returned by Plaid about each of the Items included in the Base Report.
    #[serde(rename = "items")]
    pub items: Vec<models::CraVoaReportItem>,
    #[serde(rename = "attributes")]
    pub attributes: models::CraVoaReportAttributes,
}

impl CraVoaReport {
    /// An object representing a VOA report.
    pub fn new(generated_time: chrono::DateTime<chrono::FixedOffset>, days_requested: f64, items: Vec<models::CraVoaReportItem>, attributes: models::CraVoaReportAttributes) -> CraVoaReport {
        CraVoaReport {
            generated_time,
            days_requested,
            items,
            attributes,
        }
    }
}

