/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCheckReportVerificationGetReportType : Type of home lending report.
/// Type of home lending report.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CraCheckReportVerificationGetReportType {
    #[serde(rename = "VOA")]
    Voa,
    #[serde(rename = "EMPLOYMENT_REFRESH")]
    EmploymentRefresh,

}

impl std::fmt::Display for CraCheckReportVerificationGetReportType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Voa => write!(f, "VOA"),
            Self::EmploymentRefresh => write!(f, "EMPLOYMENT_REFRESH"),
        }
    }
}

impl Default for CraCheckReportVerificationGetReportType {
    fn default() -> CraCheckReportVerificationGetReportType {
        Self::Voa
    }
}

