/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CraCreditProfileInquiryType : The inquiry type of credit profile report.
/// The inquiry type of credit profile report.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CraCreditProfileInquiryType {
    #[serde(rename = "SOFT_INQUIRY")]
    SoftInquiry,
    #[serde(rename = "STANDARD_INQUIRY")]
    StandardInquiry,

}

impl std::fmt::Display for CraCreditProfileInquiryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SoftInquiry => write!(f, "SOFT_INQUIRY"),
            Self::StandardInquiry => write!(f, "STANDARD_INQUIRY"),
        }
    }
}

impl Default for CraCreditProfileInquiryType {
    fn default() -> CraCreditProfileInquiryType {
        Self::SoftInquiry
    }
}

