/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomSandboxTransaction : Data to populate as test transaction data.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomSandboxTransaction {
    /// The date of the transaction, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD) format. Transaction date must be the present date or a date up to 14 days in the past. Future dates are not allowed.
    #[serde(rename = "date_transacted")]
    pub date_transacted: chrono::NaiveDate,
    /// The date the transaction posted, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD) format. Posted date must be the present date or a date up to 14 days in the past. Future dates are not allowed.
    #[serde(rename = "date_posted")]
    pub date_posted: chrono::NaiveDate,
    /// The transaction amount. Can be negative.
    #[serde(rename = "amount")]
    pub amount: f64,
    /// The transaction description.
    #[serde(rename = "description")]
    pub description: String,
    /// The ISO-4217 format currency code for the transaction. Defaults to USD.
    #[serde(rename = "iso_currency_code", skip_serializing_if = "Option::is_none")]
    pub iso_currency_code: Option<String>,
}

impl CustomSandboxTransaction {
    /// Data to populate as test transaction data.
    pub fn new(date_transacted: chrono::NaiveDate, date_posted: chrono::NaiveDate, amount: f64, description: String) -> CustomSandboxTransaction {
        CustomSandboxTransaction {
            date_transacted,
            date_posted,
            amount,
            description,
            iso_currency_code: None,
        }
    }
}

