/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DocumentAnalysis : High level descriptions of how the associated document was processed. If a document fails verification, the details in the `analysis` object should help clarify why the document was rejected.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentAnalysis {
    #[serde(rename = "authenticity")]
    pub authenticity: models::DocumentAuthenticityMatchCode,
    #[serde(rename = "image_quality")]
    pub image_quality: models::ImageQuality,
    #[serde(rename = "extracted_data", deserialize_with = "Option::deserialize")]
    pub extracted_data: Option<models::PhysicalDocumentExtractedDataAnalysis>,
    #[serde(rename = "fraud_analysis_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fraud_analysis_details: Option<Option<models::FraudAnalysisDetails>>,
    #[serde(rename = "image_quality_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_quality_details: Option<Option<models::ImageQualityDetails>>,
    #[serde(rename = "human_review", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub human_review: Option<Option<models::HumanReview>>,
    #[serde(rename = "aamva_verification", deserialize_with = "Option::deserialize")]
    pub aamva_verification: Option<models::AamvaAnalysis>,
}

impl DocumentAnalysis {
    /// High level descriptions of how the associated document was processed. If a document fails verification, the details in the `analysis` object should help clarify why the document was rejected.
    pub fn new(authenticity: models::DocumentAuthenticityMatchCode, image_quality: models::ImageQuality, extracted_data: Option<models::PhysicalDocumentExtractedDataAnalysis>, aamva_verification: Option<models::AamvaAnalysis>) -> DocumentAnalysis {
        DocumentAnalysis {
            authenticity,
            image_quality,
            extracted_data,
            fraud_analysis_details: None,
            image_quality_details: None,
            human_review: None,
            aamva_verification,
        }
    }
}

