/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Employee : Data about the employee.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Employee {
    /// The name of the employee.
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "address", deserialize_with = "Option::deserialize")]
    pub address: Option<Box<models::AddressDataNullable>>,
}

impl Employee {
    /// Data about the employee.
    pub fn new(name: Option<String>, address: Option<models::AddressDataNullable>) -> Employee {
        Employee {
            name,
            address: if let Some(x) = address {Some(Box::new(x))} else {None},
        }
    }
}

