/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExpenditureSummary : Summary statistics for a specific expenditure category, including total amount, monthly average, and percentage of income.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpenditureSummary {
    /// The total value of all the aggregated transactions in this expenditure category.
    #[serde(rename = "amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Option<f64>>,
    /// The ISO-4217 currency code of the amount. Always `null` if `unofficial_currency_code` is non-`null`.
    #[serde(rename = "iso_currency_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub iso_currency_code: Option<Option<String>>,
    /// The unofficial currency code associated with the amount. Always `null` if `iso_currency_code` is non-`null`.  See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `unofficial_currency_code`s.
    #[serde(rename = "unofficial_currency_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unofficial_currency_code: Option<Option<String>>,
    #[serde(rename = "monthly_average", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub monthly_average: Option<Option<models::MonthlyAverage>>,
    /// The total number of outflow transactions in this expenses group, within the given time window across all the accounts in the report.
    #[serde(rename = "transactions_count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transactions_count: Option<Option<i32>>,
    /// The percentage of the total inflows that was spent in this expenses group, within the given time window across all the accounts in the report. For example, a value of 100 represents that 100% of the inflows were spent on transactions that fall into this expenditure group. If there's no available income for the giving time period, this field value will be `-1`.
    #[serde(rename = "percentage_of_income", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub percentage_of_income: Option<Option<f64>>,
    /// The primary credit categories of the expenses within the given time window, across all the accounts in the report.  The categories are sorted in descending order by the total value spent. See the [category taxonomy](https://plaid.com/documents/credit-category-taxonomy.csv) for a full listing of category IDs.
    #[serde(rename = "top_categories", skip_serializing_if = "Option::is_none")]
    pub top_categories: Option<Vec<models::CategoryExpenses>>,
}

impl ExpenditureSummary {
    /// Summary statistics for a specific expenditure category, including total amount, monthly average, and percentage of income.
    pub fn new() -> ExpenditureSummary {
        ExpenditureSummary {
            amount: None,
            iso_currency_code: None,
            unofficial_currency_code: None,
            monthly_average: None,
            transactions_count: None,
            percentage_of_income: None,
            top_categories: None,
        }
    }
}

