/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FdxLifecycleEvent : Details of consent or payment network identifier or other entity's revocation request or other lifecycle status change event
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FdxLifecycleEvent {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::FdxEventStatus>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<models::FdxUpdateReason>,
    /// Additional information or description of an `OTHER` reason
    #[serde(rename = "otherReason", skip_serializing_if = "Option::is_none")]
    pub other_reason: Option<String>,
    #[serde(rename = "initiator", skip_serializing_if = "Option::is_none")]
    pub initiator: Option<models::FdxPartyType>,
    /// ISO 8601 date-time in format 'YYYY-MM-DDThh:mm:ss.nnn[Z|[+|-]hh:mm]' according to [IETF RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14)
    #[serde(rename = "updatedTime", skip_serializing_if = "Option::is_none")]
    pub updated_time: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl FdxLifecycleEvent {
    /// Details of consent or payment network identifier or other entity's revocation request or other lifecycle status change event
    pub fn new() -> FdxLifecycleEvent {
        FdxLifecycleEvent {
            status: None,
            reason: None,
            other_reason: None,
            initiator: None,
            updated_time: None,
        }
    }
}

