/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FdxUpdateReason : Reason for lifecycle event status change
/// Reason for lifecycle event status change
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FdxUpdateReason {
    #[serde(rename = "BUSINESS_RULE")]
    BusinessRule,
    #[serde(rename = "SECURITY_EVENT")]
    SecurityEvent,
    #[serde(rename = "USER_ACTION")]
    UserAction,
    #[serde(rename = "OTHER")]
    Other,

}

impl std::fmt::Display for FdxUpdateReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BusinessRule => write!(f, "BUSINESS_RULE"),
            Self::SecurityEvent => write!(f, "SECURITY_EVENT"),
            Self::UserAction => write!(f, "USER_ACTION"),
            Self::Other => write!(f, "OTHER"),
        }
    }
}

impl Default for FdxUpdateReason {
    fn default() -> FdxUpdateReason {
        Self::BusinessRule
    }
}

