/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FixedIncome : Details about the fixed income security.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FixedIncome {
    #[serde(rename = "yield_rate", deserialize_with = "Option::deserialize")]
    pub yield_rate: Option<models::YieldRate>,
    /// The maturity date for this fixed income security, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "maturity_date", deserialize_with = "Option::deserialize")]
    pub maturity_date: Option<chrono::NaiveDate>,
    /// The issue date for this fixed income security, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "issue_date", deserialize_with = "Option::deserialize")]
    pub issue_date: Option<chrono::NaiveDate>,
    /// The face value that is paid upon maturity of the fixed income security, per unit of security.
    #[serde(rename = "face_value", deserialize_with = "Option::deserialize")]
    pub face_value: Option<f64>,
}

impl FixedIncome {
    /// Details about the fixed income security.
    pub fn new(yield_rate: Option<models::YieldRate>, maturity_date: Option<chrono::NaiveDate>, issue_date: Option<chrono::NaiveDate>, face_value: Option<f64>) -> FixedIncome {
        FixedIncome {
            yield_rate,
            maturity_date,
            issue_date,
            face_value,
        }
    }
}

