/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FraudCheckOutcomeWithNoData : The outcome of the fraud check, when available.
/// The outcome of the fraud check, when available.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FraudCheckOutcomeWithNoData {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "no_data")]
    NoData,

}

impl std::fmt::Display for FraudCheckOutcomeWithNoData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Success => write!(f, "success"),
            Self::Failed => write!(f, "failed"),
            Self::NoData => write!(f, "no_data"),
        }
    }
}

impl Default for FraudCheckOutcomeWithNoData {
    fn default() -> FraudCheckOutcomeWithNoData {
        Self::Success
    }
}

