/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FraudCheckOutcome : The outcome of the fraud check.
/// The outcome of the fraud check.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FraudCheckOutcome {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failed")]
    Failed,

}

impl std::fmt::Display for FraudCheckOutcome {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Success => write!(f, "success"),
            Self::Failed => write!(f, "failed"),
        }
    }
}

impl Default for FraudCheckOutcome {
    fn default() -> FraudCheckOutcome {
        Self::Success
    }
}

