/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HumanReviewStatus : The outcome of the human review check, when available. The following values are possible:   `success` - The document passed the check.  `failed` - The document failed the check.  `no_data` - The document was submitted, but the document specialist review was not completed in time.
/// The outcome of the human review check, when available. The following values are possible:   `success` - The document passed the check.  `failed` - The document failed the check.  `no_data` - The document was submitted, but the document specialist review was not completed in time.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HumanReviewStatus {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "no_data")]
    NoData,

}

impl std::fmt::Display for HumanReviewStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Success => write!(f, "success"),
            Self::Failed => write!(f, "failed"),
            Self::NoData => write!(f, "no_data"),
        }
    }
}

impl Default for HumanReviewStatus {
    fn default() -> HumanReviewStatus {
        Self::Success
    }
}

