/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HumanReview : Details about the human review check, which refers to a check that is performed by a document specialist.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HumanReview {
    #[serde(rename = "status")]
    pub status: models::HumanReviewStatus,
}

impl HumanReview {
    /// Details about the human review check, which refers to a check that is performed by a document specialist.
    pub fn new(status: models::HumanReviewStatus) -> HumanReview {
        HumanReview {
            status,
        }
    }
}

