/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IdvProtectEvent : Information about a Protect event including Trust Index score and fraud attributes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdvProtectEvent {
    /// The event ID.
    #[serde(rename = "event_id")]
    pub event_id: String,
    /// The timestamp of the event, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format, e.g. `\"2017-09-14T14:42:19.350Z\"`
    #[serde(rename = "timestamp")]
    pub timestamp: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "trust_index", deserialize_with = "Option::deserialize")]
    pub trust_index: Option<models::TrustIndex>,
    /// Event fraud attributes as an arbitrary set of key-value pairs.
    #[serde(rename = "fraud_attributes", deserialize_with = "Option::deserialize")]
    pub fraud_attributes: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl IdvProtectEvent {
    /// Information about a Protect event including Trust Index score and fraud attributes.
    pub fn new(event_id: String, timestamp: chrono::DateTime<chrono::FixedOffset>, trust_index: Option<models::TrustIndex>, fraud_attributes: Option<std::collections::HashMap<String, serde_json::Value>>) -> IdvProtectEvent {
        IdvProtectEvent {
            event_id,
            timestamp,
            trust_index,
            fraud_attributes,
        }
    }
}

