/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IncomeVerificationStatusWebhook : Fired when the status of an income verification instance has changed. It will typically take several minutes for this webhook to fire after the end user has uploaded their documents in the Document Income flow.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IncomeVerificationStatusWebhook {
    /// `\"INCOME\"`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `income_verification`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    /// The `income_verification_id` of the verification instance whose status is being reported.
    #[serde(rename = "income_verification_id")]
    pub income_verification_id: String,
    /// `VERIFICATION_STATUS_PROCESSING_COMPLETE`: The income verification status processing has completed.  `VERIFICATION_STATUS_UPLOAD_ERROR`: An upload error occurred when the end user attempted to upload their verification documentation.  `VERIFICATION_STATUS_INVALID_TYPE`: The end user attempted to upload verification documentation in an unsupported file format.  `VERIFICATION_STATUS_DOCUMENT_REJECTED`: The documentation uploaded by the end user was recognized as a supported file format, but not recognized as a valid paystub.  `VERIFICATION_STATUS_PROCESSING_FAILED`: A failure occurred when attempting to process the verification documentation.
    #[serde(rename = "verification_status")]
    pub verification_status: String,
}

impl IncomeVerificationStatusWebhook {
    /// Fired when the status of an income verification instance has changed. It will typically take several minutes for this webhook to fire after the end user has uploaded their documents in the Document Income flow.
    pub fn new(webhook_type: String, webhook_code: String, income_verification_id: String, verification_status: String) -> IncomeVerificationStatusWebhook {
        IncomeVerificationStatusWebhook {
            webhook_type,
            webhook_code,
            income_verification_id,
            verification_status,
        }
    }
}

