/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IncomeVerificationPayrollFlowType : Flow types to retrieve payroll income data
/// Flow types to retrieve payroll income data
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncomeVerificationPayrollFlowType {
    #[serde(rename = "payroll_digital_income")]
    PayrollDigitalIncome,
    #[serde(rename = "payroll_document_income")]
    PayrollDocumentIncome,

}

impl std::fmt::Display for IncomeVerificationPayrollFlowType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PayrollDigitalIncome => write!(f, "payroll_digital_income"),
            Self::PayrollDocumentIncome => write!(f, "payroll_document_income"),
        }
    }
}

impl Default for IncomeVerificationPayrollFlowType {
    fn default() -> IncomeVerificationPayrollFlowType {
        Self::PayrollDigitalIncome
    }
}

