/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IncomeVerificationDocumentsDownloadRequest : IncomeVerificationDocumentsDownloadRequest defines the request schema for `/income/verification/documents/download`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IncomeVerificationDocumentsDownloadRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// The ID of the verification.
    #[serde(rename = "income_verification_id")]
    pub income_verification_id: String,
}

impl IncomeVerificationDocumentsDownloadRequest {
    /// IncomeVerificationDocumentsDownloadRequest defines the request schema for `/income/verification/documents/download`.
    pub fn new(income_verification_id: String) -> IncomeVerificationDocumentsDownloadRequest {
        IncomeVerificationDocumentsDownloadRequest {
            client_id: None,
            secret: None,
            income_verification_id,
        }
    }
}

