/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IncomeVerificationDocumentsDownloadResponse : IncomeVerificationDocumentsDownloadResponse defines the response schema for `/income/verification/documents/download`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IncomeVerificationDocumentsDownloadResponse {
    #[serde(rename = "id")]
    pub id: String,
}

impl IncomeVerificationDocumentsDownloadResponse {
    /// IncomeVerificationDocumentsDownloadResponse defines the response schema for `/income/verification/documents/download`.
    pub fn new(id: String) -> IncomeVerificationDocumentsDownloadResponse {
        IncomeVerificationDocumentsDownloadResponse {
            id,
        }
    }
}

