/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IncomeInsights : Comprehensive income analysis including total income, income excluding transfers, and inbound transfer amounts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IncomeInsights {
    /// The total amount of all income transactions in the given time period.
    #[serde(rename = "total_income", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_income: Option<Option<models::AmountWithCurrency>>,
    /// Income excluding account transfer transactions for the period, including a monthly average.
    #[serde(rename = "income_excluding_transfers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub income_excluding_transfers: Option<Option<Box<models::AmountWithCurrencyWithMonthlyAverage>>>,
    /// Sum of inbound transfer transactions for the period, including a monthly average.
    #[serde(rename = "transfers_in", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transfers_in: Option<Option<Box<models::AmountWithCurrencyWithMonthlyAverage>>>,
}

impl IncomeInsights {
    /// Comprehensive income analysis including total income, income excluding transfers, and inbound transfer amounts.
    pub fn new() -> IncomeInsights {
        IncomeInsights {
            total_income: None,
            income_excluding_transfers: None,
            transfers_in: None,
        }
    }
}

