/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IncomeSummaryFieldString {
    /// The value of the field.
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "verification_status")]
    pub verification_status: models::VerificationStatus,
}

impl IncomeSummaryFieldString {
    pub fn new(value: String, verification_status: models::VerificationStatus) -> IncomeSummaryFieldString {
        IncomeSummaryFieldString {
            value,
            verification_status,
        }
    }
}

