/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IncomeInsightsVersion : The version of Income Insights to use.
/// The version of Income Insights to use.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncomeInsightsVersion {
    #[serde(rename = "II2")]
    Ii2,

}

impl std::fmt::Display for IncomeInsightsVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ii2 => write!(f, "II2"),
        }
    }
}

impl Default for IncomeInsightsVersion {
    fn default() -> IncomeInsightsVersion {
        Self::Ii2
    }
}

