/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Institution : Details relating to a specific financial institution
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Institution {
    /// Unique identifier for the institution
    #[serde(rename = "institution_id")]
    pub institution_id: String,
    /// The official name of the institution
    #[serde(rename = "name")]
    pub name: String,
    /// A list of the Plaid products supported by the institution. Note that only institutions that support Instant Auth will return `auth` in the product array; institutions that do not list `auth` may still support other Auth methods such as Instant Match or Automated Micro-deposit Verification. For more details, see [Full Auth coverage](https://plaid.com/docs/auth/coverage/).
    #[serde(rename = "products")]
    pub products: Vec<models::Products>,
    /// A list of the country codes supported by the institution.
    #[serde(rename = "country_codes")]
    pub country_codes: Vec<models::CountryCode>,
    /// The URL for the institution's website
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
    /// Hexadecimal representation of the primary color used by the institution
    #[serde(rename = "primary_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub primary_color: Option<Option<String>>,
    /// Base64 encoded representation of the institution's logo
    #[serde(rename = "logo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logo: Option<Option<String>>,
    /// A partial list of routing numbers associated with the institution. This list is provided for the purpose of looking up institutions by routing number. It is not comprehensive and should never be used as a complete list of routing numbers for an institution.
    #[serde(rename = "routing_numbers", deserialize_with = "Option::deserialize")]
    pub routing_numbers: Option<Vec<String>>,
    /// Indicates that the institution has an OAuth login flow. This is primarily relevant to institutions with European country codes.
    #[serde(rename = "oauth")]
    pub oauth: bool,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::InstitutionStatus>,
    #[serde(rename = "payment_initiation_metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_initiation_metadata: Option<Option<models::PaymentInitiationMetadata>>,
}

impl Institution {
    /// Details relating to a specific financial institution
    pub fn new(institution_id: String, name: String, products: Vec<models::Products>, country_codes: Vec<models::CountryCode>, routing_numbers: Option<Vec<String>>, oauth: bool) -> Institution {
        Institution {
            institution_id,
            name,
            products,
            country_codes,
            url: None,
            primary_color: None,
            logo: None,
            routing_numbers,
            oauth,
            status: None,
            payment_initiation_metadata: None,
        }
    }
}

