/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ItemRemoveReasonCode : The reason for removing the item  `FRAUD_FIRST_PARTY`: The end user who owns the connected bank account committed fraud `FRAUD_FALSE_IDENTITY`: The end user created the connection using false identity information or stolen credentials `FRAUD_ABUSE`: The end user is abusing the client's service or platform through their connected account `FRAUD_OTHER`: Other fraud-related reasons involving the end user not covered by the specific fraud categories `CONNECTION_IS_NON_FUNCTIONAL`: The connection to the end user's financial institution is broken and cannot be restored `OTHER`: Any other reason for removing the connection not covered by the above categories 
/// The reason for removing the item  `FRAUD_FIRST_PARTY`: The end user who owns the connected bank account committed fraud `FRAUD_FALSE_IDENTITY`: The end user created the connection using false identity information or stolen credentials `FRAUD_ABUSE`: The end user is abusing the client's service or platform through their connected account `FRAUD_OTHER`: Other fraud-related reasons involving the end user not covered by the specific fraud categories `CONNECTION_IS_NON_FUNCTIONAL`: The connection to the end user's financial institution is broken and cannot be restored `OTHER`: Any other reason for removing the connection not covered by the above categories 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ItemRemoveReasonCode {
    #[serde(rename = "FRAUD_FIRST_PARTY")]
    FraudFirstParty,
    #[serde(rename = "FRAUD_FALSE_IDENTITY")]
    FraudFalseIdentity,
    #[serde(rename = "FRAUD_ABUSE")]
    FraudAbuse,
    #[serde(rename = "FRAUD_OTHER")]
    FraudOther,
    #[serde(rename = "CONNECTION_IS_NON_FUNCTIONAL")]
    ConnectionIsNonFunctional,
    #[serde(rename = "OTHER")]
    Other,

}

impl std::fmt::Display for ItemRemoveReasonCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FraudFirstParty => write!(f, "FRAUD_FIRST_PARTY"),
            Self::FraudFalseIdentity => write!(f, "FRAUD_FALSE_IDENTITY"),
            Self::FraudAbuse => write!(f, "FRAUD_ABUSE"),
            Self::FraudOther => write!(f, "FRAUD_OTHER"),
            Self::ConnectionIsNonFunctional => write!(f, "CONNECTION_IS_NON_FUNCTIONAL"),
            Self::Other => write!(f, "OTHER"),
        }
    }
}

impl Default for ItemRemoveReasonCode {
    fn default() -> ItemRemoveReasonCode {
        Self::FraudFirstParty
    }
}

