/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ItemConsentedDataScope : A data scope for the products that a user can consent to in [Data Transparency Messaging](https://plaid.com/docs/link/data-transparency-messaging-migration-guide)
/// A data scope for the products that a user can consent to in [Data Transparency Messaging](https://plaid.com/docs/link/data-transparency-messaging-migration-guide)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ItemConsentedDataScope {
    #[serde(rename = "account_balance_info")]
    AccountBalanceInfo,
    #[serde(rename = "contact_info")]
    ContactInfo,
    #[serde(rename = "account_routing_number")]
    AccountRoutingNumber,
    #[serde(rename = "transactions")]
    Transactions,
    #[serde(rename = "credit_loan_info")]
    CreditLoanInfo,
    #[serde(rename = "investments")]
    Investments,
    #[serde(rename = "payroll_info")]
    PayrollInfo,
    #[serde(rename = "income_verification_paystubs_info")]
    IncomeVerificationPaystubsInfo,
    #[serde(rename = "income_verification_w2s_info")]
    IncomeVerificationW2sInfo,
    #[serde(rename = "income_verification_bank_statements")]
    IncomeVerificationBankStatements,
    #[serde(rename = "income_verification_employment_info")]
    IncomeVerificationEmploymentInfo,
    #[serde(rename = "bank_statements")]
    BankStatements,
    #[serde(rename = "risk_info")]
    RiskInfo,
    #[serde(rename = "network_insights_lite")]
    NetworkInsightsLite,
    #[serde(rename = "fraud_info")]
    FraudInfo,

}

impl std::fmt::Display for ItemConsentedDataScope {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AccountBalanceInfo => write!(f, "account_balance_info"),
            Self::ContactInfo => write!(f, "contact_info"),
            Self::AccountRoutingNumber => write!(f, "account_routing_number"),
            Self::Transactions => write!(f, "transactions"),
            Self::CreditLoanInfo => write!(f, "credit_loan_info"),
            Self::Investments => write!(f, "investments"),
            Self::PayrollInfo => write!(f, "payroll_info"),
            Self::IncomeVerificationPaystubsInfo => write!(f, "income_verification_paystubs_info"),
            Self::IncomeVerificationW2sInfo => write!(f, "income_verification_w2s_info"),
            Self::IncomeVerificationBankStatements => write!(f, "income_verification_bank_statements"),
            Self::IncomeVerificationEmploymentInfo => write!(f, "income_verification_employment_info"),
            Self::BankStatements => write!(f, "bank_statements"),
            Self::RiskInfo => write!(f, "risk_info"),
            Self::NetworkInsightsLite => write!(f, "network_insights_lite"),
            Self::FraudInfo => write!(f, "fraud_info"),
        }
    }
}

impl Default for ItemConsentedDataScope {
    fn default() -> ItemConsentedDataScope {
        Self::AccountBalanceInfo
    }
}

