/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LedgerEventSourceType : Source of the ledger event.  `\"TRANSFER\"` - The source of the ledger event is a transfer `\"SWEEP\"` - The source of the ledger event is a sweep `\"REFUND\"` - The source of the ledger event is a refund
/// Source of the ledger event.  `\"TRANSFER\"` - The source of the ledger event is a transfer `\"SWEEP\"` - The source of the ledger event is a sweep `\"REFUND\"` - The source of the ledger event is a refund
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LedgerEventSourceType {
    #[serde(rename = "TRANSFER")]
    Transfer,
    #[serde(rename = "SWEEP")]
    Sweep,
    #[serde(rename = "REFUND")]
    Refund,

}

impl std::fmt::Display for LedgerEventSourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Transfer => write!(f, "TRANSFER"),
            Self::Sweep => write!(f, "SWEEP"),
            Self::Refund => write!(f, "REFUND"),
        }
    }
}

impl Default for LedgerEventSourceType {
    fn default() -> LedgerEventSourceType {
        Self::Transfer
    }
}

