/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LendScore : The results of the LendScore
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LendScore {
    /// The score returned by the LendScore model. Will be an integer in the range 1 to 99. Higher scores indicate lower credit risk.
    #[serde(rename = "score", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub score: Option<Option<i32>>,
    /// The reasons for an individual having risk according to the LendScore. For a full list of possible reason codes and a mapping of reason codes to human-readable reasons, contact your Plaid Account Manager. Different LendScore versions will use different sets of reason codes.
    #[serde(rename = "reason_codes", skip_serializing_if = "Option::is_none")]
    pub reason_codes: Option<Vec<String>>,
    /// Human-readable description of why the LendScore could not be computed.
    #[serde(rename = "error_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_reason: Option<Option<String>>,
}

impl LendScore {
    /// The results of the LendScore
    pub fn new() -> LendScore {
        LendScore {
            score: None,
            reason_codes: None,
            error_reason: None,
        }
    }
}

