/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LimitedPurposeType : A limited purpose type identifying the specific use case for limited purpose checking accounts.
/// A limited purpose type identifying the specific use case for limited purpose checking accounts.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LimitedPurposeType {
    #[serde(rename = "RENT_MORTGAGE")]
    RentMortgage,

}

impl std::fmt::Display for LimitedPurposeType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RentMortgage => write!(f, "RENT_MORTGAGE"),
        }
    }
}

impl Default for LimitedPurposeType {
    fn default() -> LimitedPurposeType {
        Self::RentMortgage
    }
}

