/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkSessionSuccess : An object representing an [onSuccess](https://plaid.com/docs/link/web/#onsuccess) callback from Link. This field is returned only for legacy integrations and is deprecated in favor of [`results.item_add_results`](https://plaid.com/docs/api/link/#link-token-get-response-link-sessions-results-item-add-results) which can support multiple public tokens in a single Link session, for flows such as multi-Item Link. If you are receiving `on_success`, contact your Account Manager to migrate to `results.item_add_results` instead.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkSessionSuccess {
    /// Displayed once a user has successfully linked their Item.
    #[serde(rename = "public_token")]
    pub public_token: String,
    #[serde(rename = "metadata", deserialize_with = "Option::deserialize")]
    pub metadata: Option<Box<models::LinkSessionSuccessMetadata>>,
}

impl LinkSessionSuccess {
    /// An object representing an [onSuccess](https://plaid.com/docs/link/web/#onsuccess) callback from Link. This field is returned only for legacy integrations and is deprecated in favor of [`results.item_add_results`](https://plaid.com/docs/api/link/#link-token-get-response-link-sessions-results-item-add-results) which can support multiple public tokens in a single Link session, for flows such as multi-Item Link. If you are receiving `on_success`, contact your Account Manager to migrate to `results.item_add_results` instead.
    pub fn new(public_token: String, metadata: Option<models::LinkSessionSuccessMetadata>) -> LinkSessionSuccess {
        LinkSessionSuccess {
            public_token,
            metadata: if let Some(x) = metadata {Some(Box::new(x))} else {None},
        }
    }
}

