/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkTokenCreateRequestCraOptionsNetworkInsights : Specifies options for initializing Link for use with the CRA Network Insights product.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkTokenCreateRequestCraOptionsNetworkInsights {
    #[serde(rename = "network_insights_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub network_insights_version: Option<Option<models::NetworkInsightsVersion>>,
}

impl LinkTokenCreateRequestCraOptionsNetworkInsights {
    /// Specifies options for initializing Link for use with the CRA Network Insights product.
    pub fn new() -> LinkTokenCreateRequestCraOptionsNetworkInsights {
        LinkTokenCreateRequestCraOptionsNetworkInsights {
            network_insights_version: None,
        }
    }
}

