/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkTokenCreateRequestCraOptionsPartnerInsights : Specifies options for initializing Link for use with the Credit Partner Insights product.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkTokenCreateRequestCraOptionsPartnerInsights {
    #[serde(rename = "prism_versions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prism_versions: Option<Option<Box<models::PrismVersions>>>,
    #[serde(rename = "fico", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fico: Option<Option<Box<models::CraPartnerInsightsFicoInput>>>,
}

impl LinkTokenCreateRequestCraOptionsPartnerInsights {
    /// Specifies options for initializing Link for use with the Credit Partner Insights product.
    pub fn new() -> LinkTokenCreateRequestCraOptionsPartnerInsights {
        LinkTokenCreateRequestCraOptionsPartnerInsights {
            prism_versions: None,
            fico: None,
        }
    }
}

