/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkTokenCreateRequestIncomeVerification : Specifies options for initializing Link for use with the Income (beta) product. This field is required if `income_verification` is included in the `products` array.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkTokenCreateRequestIncomeVerification {
    /// The `income_verification_id` of the verification instance, as provided by `/income/verification/create`.
    #[serde(rename = "income_verification_id")]
    pub income_verification_id: String,
    /// The `asset_report_id` of an asset report associated with the user, as provided by `/asset_report/create`. Providing an `asset_report_id` is optional and can be used to verify the user through a streamlined flow. If provided, the bank linking flow will be skipped.
    #[serde(rename = "asset_report_id", skip_serializing_if = "Option::is_none")]
    pub asset_report_id: Option<String>,
}

impl LinkTokenCreateRequestIncomeVerification {
    /// Specifies options for initializing Link for use with the Income (beta) product. This field is required if `income_verification` is included in the `products` array.
    pub fn new(income_verification_id: String) -> LinkTokenCreateRequestIncomeVerification {
        LinkTokenCreateRequestIncomeVerification {
            income_verification_id,
            asset_report_id: None,
        }
    }
}

