/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkTokenCreateRequestAppearanceMode : Enum representing the desired appearance mode for Link, used to force light or dark modes or set Link to change depending on user system settings. Currently in closed beta.
/// Enum representing the desired appearance mode for Link, used to force light or dark modes or set Link to change depending on user system settings. Currently in closed beta.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LinkTokenCreateRequestAppearanceMode {
    #[serde(rename = "LIGHT")]
    Light,
    #[serde(rename = "DARK")]
    Dark,
    #[serde(rename = "SYSTEM")]
    System,

}

impl std::fmt::Display for LinkTokenCreateRequestAppearanceMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Light => write!(f, "LIGHT"),
            Self::Dark => write!(f, "DARK"),
            Self::System => write!(f, "SYSTEM"),
        }
    }
}

impl Default for LinkTokenCreateRequestAppearanceMode {
    fn default() -> LinkTokenCreateRequestAppearanceMode {
        Self::Light
    }
}

