/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkTokenCreateRequestCraOptionsCashflowInsights : Specifies options for initializing Link for use with the Cashflow Insights product.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkTokenCreateRequestCraOptionsCashflowInsights {
    #[serde(rename = "attributes_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attributes_version: Option<Option<models::CashflowAttributesVersion>>,
}

impl LinkTokenCreateRequestCraOptionsCashflowInsights {
    /// Specifies options for initializing Link for use with the Cashflow Insights product.
    pub fn new() -> LinkTokenCreateRequestCraOptionsCashflowInsights {
        LinkTokenCreateRequestCraOptionsCashflowInsights {
            attributes_version: None,
        }
    }
}

