/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkSessionExitDeprecated : An object representing an [onExit](https://plaid.com/docs/link/web/#onexit) callback from Link. This field is returned only for legacy implementations and has been deprecated in favor of [`exit`](https://plaid.com/docs/api/link/#link-token-get-response-link-sessions-exit), for improved naming consistency. If you are receiving this field, contact your Account Manager to migrate to the newer `exit` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkSessionExitDeprecated {
    #[serde(rename = "error", deserialize_with = "Option::deserialize")]
    pub error: Option<models::PlaidError>,
    #[serde(rename = "metadata", deserialize_with = "Option::deserialize")]
    pub metadata: Option<Box<models::LinkSessionExitMetadata>>,
}

impl LinkSessionExitDeprecated {
    /// An object representing an [onExit](https://plaid.com/docs/link/web/#onexit) callback from Link. This field is returned only for legacy implementations and has been deprecated in favor of [`exit`](https://plaid.com/docs/api/link/#link-token-get-response-link-sessions-exit), for improved naming consistency. If you are receiving this field, contact your Account Manager to migrate to the newer `exit` field.
    pub fn new(error: Option<models::PlaidError>, metadata: Option<models::LinkSessionExitMetadata>) -> LinkSessionExitDeprecated {
        LinkSessionExitDeprecated {
            error,
            metadata: if let Some(x) = metadata {Some(Box::new(x))} else {None},
        }
    }
}

