/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkTokenCreateRequestAccountSubtypesDepository : A filter to apply to `depository`-type accounts
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkTokenCreateRequestAccountSubtypesDepository {
    /// An array of account subtypes to display in Link. If not specified, all account subtypes will be shown. For a full list of valid types and subtypes, see the [Account schema](https://plaid.com/docs/api/accounts#accounts-schema). 
    #[serde(rename = "account_subtypes", skip_serializing_if = "Option::is_none")]
    pub account_subtypes: Option<Vec<models::AccountSubtype>>,
}

impl LinkTokenCreateRequestAccountSubtypesDepository {
    /// A filter to apply to `depository`-type accounts
    pub fn new() -> LinkTokenCreateRequestAccountSubtypesDepository {
        LinkTokenCreateRequestAccountSubtypesDepository {
            account_subtypes: None,
        }
    }
}

