/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkTokenCreateRequestCraOptionsLendScore : Specifies options for initializing Link for use with the CRA LendScore product.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkTokenCreateRequestCraOptionsLendScore {
    #[serde(rename = "lend_score_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lend_score_version: Option<Option<models::PlaidLendScoreVersion>>,
}

impl LinkTokenCreateRequestCraOptionsLendScore {
    /// Specifies options for initializing Link for use with the CRA LendScore product.
    pub fn new() -> LinkTokenCreateRequestCraOptionsLendScore {
        LinkTokenCreateRequestCraOptionsLendScore {
            lend_score_version: None,
        }
    }
}

