/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NegativeBalanceInsights : Insights into negative balance occurrences, including frequency, duration, and minimum balance details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NegativeBalanceInsights {
    /// The number of days since the last transaction that caused any account in the report to have a negative balance.  This value is inclusive of the date of the last negative balance, meaning that if the last negative balance occurred today, this value will be `0`.
    #[serde(rename = "days_since_last_occurrence", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub days_since_last_occurrence: Option<Option<i32>>,
    /// The number of aggregated days that the accounts in the report has had a negative balance within the given time window.
    #[serde(rename = "days_with_negative_balance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub days_with_negative_balance: Option<Option<i32>>,
    #[serde(rename = "minimum_balance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub minimum_balance: Option<Option<models::AmountWithCurrency>>,
    /// The summary of the negative balance occurrences for this account.  If the user has not had a negative balance in the account in the given time window, this list will be empty.
    #[serde(rename = "occurrences", skip_serializing_if = "Option::is_none")]
    pub occurrences: Option<Vec<models::NegativeBalanceOccurrence>>,
}

impl NegativeBalanceInsights {
    /// Insights into negative balance occurrences, including frequency, duration, and minimum balance details.
    pub fn new() -> NegativeBalanceInsights {
        NegativeBalanceInsights {
            days_since_last_occurrence: None,
            days_with_negative_balance: None,
            minimum_balance: None,
            occurrences: None,
        }
    }
}

