/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NegativeBalanceOccurrence : Details about a specific occurrence of a negative balance period, including start and end dates.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NegativeBalanceOccurrence {
    /// The date of the first transaction that caused the account to have a negative balance. The date will be returned in an ISO 8601 format (YYYY-MM-DD).
    #[serde(rename = "start_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<Option<chrono::NaiveDate>>,
    /// The date of the last transaction that caused the account to have a negative balance. The date will be returned in an ISO 8601 format (YYYY-MM-DD). This date is inclusive, meaning that this was the last date that the account had a negative balance.
    #[serde(rename = "end_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "minimum_balance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub minimum_balance: Option<Option<models::AmountWithCurrency>>,
}

impl NegativeBalanceOccurrence {
    /// Details about a specific occurrence of a negative balance period, including start and end dates.
    pub fn new() -> NegativeBalanceOccurrence {
        NegativeBalanceOccurrence {
            start_date: None,
            end_date: None,
            minimum_balance: None,
        }
    }
}

