/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuthTokenResponse : OAuth token grant success response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthTokenResponse {
    /// Access token for OAuth
    #[serde(rename = "access_token")]
    pub access_token: String,
    /// Refresh token for OAuth
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
    /// Type of token the access token is. Currently it is always Bearer
    #[serde(rename = "token_type")]
    pub token_type: String,
    /// Time remaining in seconds before expiration
    #[serde(rename = "expires_in")]
    pub expires_in: i32,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl OAuthTokenResponse {
    /// OAuth token grant success response
    pub fn new(access_token: String, refresh_token: String, token_type: String, expires_in: i32, request_id: String) -> OAuthTokenResponse {
        OAuthTokenResponse {
            access_token,
            refresh_token,
            token_type,
            expires_in,
            request_id,
        }
    }
}

