/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuthErrorResponse : OAuth error response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthErrorResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<models::OAuthErrorCode>,
    /// A human-readable description of the error
    #[serde(rename = "error_description", skip_serializing_if = "Option::is_none")]
    pub error_description: Option<String>,
    /// A URI identifying the specific error
    #[serde(rename = "error_uri", skip_serializing_if = "Option::is_none")]
    pub error_uri: Option<String>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl OAuthErrorResponse {
    /// OAuth error response
    pub fn new(request_id: String) -> OAuthErrorResponse {
        OAuthErrorResponse {
            error: None,
            error_description: None,
            error_uri: None,
            request_id,
        }
    }
}

