/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OriginatingFundSource : The original source of the funds. This field is required by local regulation for certain businesses (e.g. money remittance) to send payouts to recipients in the EU and UK.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OriginatingFundSource {
    /// The full name associated with the source of the funds.
    #[serde(rename = "full_name")]
    pub full_name: String,
    #[serde(rename = "address", deserialize_with = "Option::deserialize")]
    pub address: Option<models::PaymentInitiationAddress>,
    /// The account number from which the funds are sourced.
    #[serde(rename = "account_number")]
    pub account_number: String,
    /// The Business Identifier Code, also known as SWIFT code, for this bank account.
    #[serde(rename = "bic")]
    pub bic: String,
}

impl OriginatingFundSource {
    /// The original source of the funds. This field is required by local regulation for certain businesses (e.g. money remittance) to send payouts to recipients in the EU and UK.
    pub fn new(full_name: String, address: Option<models::PaymentInitiationAddress>, account_number: String, bic: String) -> OriginatingFundSource {
        OriginatingFundSource {
            full_name,
            address,
            account_number,
            bic,
        }
    }
}

