/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartnerEndCustomerCraUseCases : The list of use cases associated with a given permissible purpose.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartnerEndCustomerCraUseCases {
    /// List of use cases for the given permissible purpose.
    #[serde(rename = "use_cases", skip_serializing_if = "Option::is_none")]
    pub use_cases: Option<Vec<models::PartnerEndCustomerCraUseCase>>,
}

impl PartnerEndCustomerCraUseCases {
    /// The list of use cases associated with a given permissible purpose.
    pub fn new() -> PartnerEndCustomerCraUseCases {
        PartnerEndCustomerCraUseCases {
            use_cases: None,
        }
    }
}

