/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartnerEndCustomerCraPurposes : A map of permissible purposes to their corresponding use cases.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartnerEndCustomerCraPurposes {
    #[serde(rename = "WRITTEN_INSTRUCTION", skip_serializing_if = "Option::is_none")]
    pub written_instruction: Option<Box<models::PartnerEndCustomerCraUseCases>>,
    #[serde(rename = "EXTENSION_OF_CREDIT_OR_ACCOUNT_REVIEW", skip_serializing_if = "Option::is_none")]
    pub extension_of_credit_or_account_review: Option<Box<models::PartnerEndCustomerCraUseCases>>,
    #[serde(rename = "EMPLOYMENT", skip_serializing_if = "Option::is_none")]
    pub employment: Option<Box<models::PartnerEndCustomerCraUseCases>>,
    #[serde(rename = "INSURANCE_UNDERWRITING", skip_serializing_if = "Option::is_none")]
    pub insurance_underwriting: Option<Box<models::PartnerEndCustomerCraUseCases>>,
    #[serde(rename = "LICENSE_ELIGIBILITY", skip_serializing_if = "Option::is_none")]
    pub license_eligibility: Option<Box<models::PartnerEndCustomerCraUseCases>>,
    #[serde(rename = "RISK_ASSESSMENT", skip_serializing_if = "Option::is_none")]
    pub risk_assessment: Option<Box<models::PartnerEndCustomerCraUseCases>>,
    #[serde(rename = "BUSINESS_NEED_TRANSACTION", skip_serializing_if = "Option::is_none")]
    pub business_need_transaction: Option<Box<models::PartnerEndCustomerCraUseCases>>,
    #[serde(rename = "BUSINESS_NEED_ACCOUNT_REVIEW", skip_serializing_if = "Option::is_none")]
    pub business_need_account_review: Option<Box<models::PartnerEndCustomerCraUseCases>>,
}

impl PartnerEndCustomerCraPurposes {
    /// A map of permissible purposes to their corresponding use cases.
    pub fn new() -> PartnerEndCustomerCraPurposes {
        PartnerEndCustomerCraPurposes {
            written_instruction: None,
            extension_of_credit_or_account_review: None,
            employment: None,
            insurance_underwriting: None,
            license_eligibility: None,
            risk_assessment: None,
            business_need_transaction: None,
            business_need_account_review: None,
        }
    }
}

