/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartnerEndCustomerRequirementDue : A field that may be required to be submitted for enablement.
/// A field that may be required to be submitted for enablement.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PartnerEndCustomerRequirementDue {
    #[serde(rename = "legal_entity_name")]
    LegalEntityName,
    #[serde(rename = "website")]
    Website,
    #[serde(rename = "application_name")]
    ApplicationName,
    #[serde(rename = "is_diligence_attested")]
    IsDiligenceAttested,
    #[serde(rename = "technical_contact")]
    TechnicalContact,
    #[serde(rename = "billing_contact")]
    BillingContact,
    #[serde(rename = "address")]
    Address,
    #[serde(rename = "bank_addendum_acceptance")]
    BankAddendumAcceptance,
    #[serde(rename = "questionnaires.cra")]
    QuestionnairesCra,

}

impl std::fmt::Display for PartnerEndCustomerRequirementDue {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::LegalEntityName => write!(f, "legal_entity_name"),
            Self::Website => write!(f, "website"),
            Self::ApplicationName => write!(f, "application_name"),
            Self::IsDiligenceAttested => write!(f, "is_diligence_attested"),
            Self::TechnicalContact => write!(f, "technical_contact"),
            Self::BillingContact => write!(f, "billing_contact"),
            Self::Address => write!(f, "address"),
            Self::BankAddendumAcceptance => write!(f, "bank_addendum_acceptance"),
            Self::QuestionnairesCra => write!(f, "questionnaires.cra"),
        }
    }
}

impl Default for PartnerEndCustomerRequirementDue {
    fn default() -> PartnerEndCustomerRequirementDue {
        Self::LegalEntityName
    }
}

