/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartnerEndCustomerQuestionnaires : The questionnaires for the end customer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartnerEndCustomerQuestionnaires {
    #[serde(rename = "cra", skip_serializing_if = "Option::is_none")]
    pub cra: Option<models::PartnerEndCustomerCraQuestionnaire>,
}

impl PartnerEndCustomerQuestionnaires {
    /// The questionnaires for the end customer.
    pub fn new() -> PartnerEndCustomerQuestionnaires {
        PartnerEndCustomerQuestionnaires {
            cra: None,
        }
    }
}

