/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartnerEndCustomerCustomerSupportInfo : This information is public. Users of your app will see this information when managing connections between your app and their bank accounts in Plaid Portal. Defaults to partner's customer support info if omitted. This field is mandatory for partners whose Plaid accounts were created after November 26, 2024 and will be mandatory for all partners by the 1033 compliance deadline.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartnerEndCustomerCustomerSupportInfo {
    /// This field is mandatory for partners whose Plaid accounts were created after November 26, 2024 and will be mandatory for all partners by the 1033 compliance deadline.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "phone_number", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "contact_url", skip_serializing_if = "Option::is_none")]
    pub contact_url: Option<String>,
    #[serde(rename = "link_update_url", skip_serializing_if = "Option::is_none")]
    pub link_update_url: Option<String>,
}

impl PartnerEndCustomerCustomerSupportInfo {
    /// This information is public. Users of your app will see this information when managing connections between your app and their bank accounts in Plaid Portal. Defaults to partner's customer support info if omitted. This field is mandatory for partners whose Plaid accounts were created after November 26, 2024 and will be mandatory for all partners by the 1033 compliance deadline.
    pub fn new() -> PartnerEndCustomerCustomerSupportInfo {
        PartnerEndCustomerCustomerSupportInfo {
            email: None,
            phone_number: None,
            contact_url: None,
            link_update_url: None,
        }
    }
}

