/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PayPeriodDetails : Details about the pay period.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayPeriodDetails {
    /// The pay period start date, in ISO 8601 format: \"yyyy-mm-dd\".
    #[serde(rename = "start_date", deserialize_with = "Option::deserialize")]
    pub start_date: Option<chrono::NaiveDate>,
    /// The pay period end date, in ISO 8601 format: \"yyyy-mm-dd\".
    #[serde(rename = "end_date", deserialize_with = "Option::deserialize")]
    pub end_date: Option<chrono::NaiveDate>,
    /// The date on which the paystub was issued, in ISO 8601 format (\"yyyy-mm-dd\").
    #[serde(rename = "pay_day", deserialize_with = "Option::deserialize")]
    pub pay_day: Option<chrono::NaiveDate>,
    /// Total earnings before tax.
    #[serde(rename = "gross_earnings", deserialize_with = "Option::deserialize")]
    pub gross_earnings: Option<f64>,
    /// The net amount of the paycheck.
    #[serde(rename = "check_amount", deserialize_with = "Option::deserialize")]
    pub check_amount: Option<f64>,
}

impl PayPeriodDetails {
    /// Details about the pay period.
    pub fn new(start_date: Option<chrono::NaiveDate>, end_date: Option<chrono::NaiveDate>, pay_day: Option<chrono::NaiveDate>, gross_earnings: Option<f64>, check_amount: Option<f64>) -> PayPeriodDetails {
        PayPeriodDetails {
            start_date,
            end_date,
            pay_day,
            gross_earnings,
            check_amount,
        }
    }
}

