/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayFrequency {
    /// The frequency of the pay period.
    #[serde(rename = "value")]
    pub value: Value,
    #[serde(rename = "verification_status")]
    pub verification_status: models::VerificationStatus,
}

impl PayFrequency {
    pub fn new(value: Value, verification_status: models::VerificationStatus) -> PayFrequency {
        PayFrequency {
            value,
            verification_status,
        }
    }
}
/// The frequency of the pay period.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Value {
    #[serde(rename = "monthly")]
    Monthly,
    #[serde(rename = "semimonthly")]
    Semimonthly,
    #[serde(rename = "weekly")]
    Weekly,
    #[serde(rename = "biweekly")]
    Biweekly,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "null")]
    Null,
}

impl Default for Value {
    fn default() -> Value {
        Self::Monthly
    }
}

