/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentInitiationRecipientListResponse : PaymentInitiationRecipientListResponse defines the response schema for `/payment_initiation/recipient/list`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentInitiationRecipientListResponse {
    /// An array of payment recipients created for Payment Initiation
    #[serde(rename = "recipients")]
    pub recipients: Vec<models::PaymentInitiationRecipient>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
    /// The value that, when used as the optional `cursor` parameter to `/payment_initiation/recipient/list`, will return the corresponding recipient as its first recipient.
    #[serde(rename = "next_cursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

impl PaymentInitiationRecipientListResponse {
    /// PaymentInitiationRecipientListResponse defines the response schema for `/payment_initiation/recipient/list`
    pub fn new(recipients: Vec<models::PaymentInitiationRecipient>, request_id: String) -> PaymentInitiationRecipientListResponse {
        PaymentInitiationRecipientListResponse {
            recipients,
            request_id,
            next_cursor: None,
        }
    }
}

