/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentInitiationRecipient : PaymentInitiationRecipient defines a payment initiation recipient
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentInitiationRecipient {
    /// The ID of the recipient.
    #[serde(rename = "recipient_id")]
    pub recipient_id: String,
    /// The name of the recipient.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "address", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address: Option<Option<models::PaymentInitiationAddress>>,
    /// The International Bank Account Number (IBAN) for the recipient.
    #[serde(rename = "iban", deserialize_with = "Option::deserialize")]
    pub iban: Option<String>,
    #[serde(rename = "bacs", deserialize_with = "Option::deserialize")]
    pub bacs: Option<Box<models::RecipientBacsNullable>>,
    /// The EMI (E-Money Institution) recipient that this recipient is associated with, if any. This EMI recipient is used as an intermediary account to enable Plaid to reconcile the settlement of funds for Payment Initiation requests.
    #[serde(rename = "emi_recipient_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub emi_recipient_id: Option<Option<String>>,
}

impl PaymentInitiationRecipient {
    /// PaymentInitiationRecipient defines a payment initiation recipient
    pub fn new(recipient_id: String, name: String, iban: Option<String>, bacs: Option<models::RecipientBacsNullable>) -> PaymentInitiationRecipient {
        PaymentInitiationRecipient {
            recipient_id,
            name,
            address: None,
            iban,
            bacs: if let Some(x) = bacs {Some(Box::new(x))} else {None},
            emi_recipient_id: None,
        }
    }
}

