/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentInitiationConsent : PaymentInitiationConsent defines a payment initiation consent.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentInitiationConsent {
    /// The consent ID.
    #[serde(rename = "consent_id")]
    pub consent_id: String,
    #[serde(rename = "status")]
    pub status: models::PaymentInitiationConsentStatus,
    /// Consent creation timestamp, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// The ID of the recipient the payment consent is for.
    #[serde(rename = "recipient_id")]
    pub recipient_id: String,
    /// A reference for the payment consent.
    #[serde(rename = "reference")]
    pub reference: String,
    #[serde(rename = "constraints")]
    pub constraints: Box<models::PaymentInitiationConsentConstraints>,
    /// Deprecated, use the 'type' field instead.
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<models::PaymentInitiationConsentScope>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::PaymentInitiationConsentType>,
    #[serde(rename = "payer_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payer_details: Option<Option<Box<models::ExternalPaymentRefundDetails>>>,
}

impl PaymentInitiationConsent {
    /// PaymentInitiationConsent defines a payment initiation consent.
    pub fn new(consent_id: String, status: models::PaymentInitiationConsentStatus, created_at: chrono::DateTime<chrono::FixedOffset>, recipient_id: String, reference: String, constraints: models::PaymentInitiationConsentConstraints) -> PaymentInitiationConsent {
        PaymentInitiationConsent {
            consent_id,
            status,
            created_at,
            recipient_id,
            reference,
            constraints: Box::new(constraints),
            scopes: None,
            r#type: None,
            payer_details: None,
        }
    }
}

