/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Paystub : An object representing data extracted from the end user's paystub.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Paystub {
    /// The account identifier for the account associated with this paystub.
    #[serde(rename = "account_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<Option<String>>,
    #[serde(rename = "employer")]
    pub employer: models::PaystubEmployer,
    #[serde(rename = "employee")]
    pub employee: models::Employee,
    #[serde(rename = "pay_period_details")]
    pub pay_period_details: models::PayPeriodDetails,
    #[serde(rename = "income_breakdown")]
    pub income_breakdown: models::IncomeBreakdown,
    #[serde(rename = "ytd_earnings")]
    pub ytd_earnings: models::PaystubYtdDetails,
}

impl Paystub {
    /// An object representing data extracted from the end user's paystub.
    pub fn new(employer: models::PaystubEmployer, employee: models::Employee, pay_period_details: models::PayPeriodDetails, income_breakdown: models::IncomeBreakdown, ytd_earnings: models::PaystubYtdDetails) -> Paystub {
        Paystub {
            account_id: None,
            employer,
            employee,
            pay_period_details,
            income_breakdown,
            ytd_earnings,
        }
    }
}

