/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.20.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaystubYtdDetails : The amount of income earned year to date, as based on paystub data.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaystubYtdDetails {
    /// Year-to-date gross earnings.
    #[serde(rename = "gross_earnings")]
    pub gross_earnings: f64,
    /// Year-to-date net (take home) earnings.
    #[serde(rename = "net_earnings")]
    pub net_earnings: f64,
}

impl PaystubYtdDetails {
    /// The amount of income earned year to date, as based on paystub data.
    pub fn new(gross_earnings: f64, net_earnings: f64) -> PaystubYtdDetails {
        PaystubYtdDetails {
            gross_earnings,
            net_earnings,
        }
    }
}

