/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PendingDisconnectWebhook : Fired when an Item is expected to be disconnected. The webhook will currently be fired 7 days before the existing Item is scheduled for disconnection. This can be resolved by having the user go through Link’s [update mode](http://plaid.com/docs/link/update-mode). Currently, this webhook is fired only for US or Canadian institutions; in the UK or EU, you should continue to listed for the [`PENDING_EXPIRATION`](https://plaid.com/docs/api/items/#pending_expiration) webhook instead.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingDisconnectWebhook {
    /// `ITEM`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `PENDING_DISCONNECT`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    /// The `item_id` of the Item associated with this webhook, warning, or error
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// The Plaid `user_id` of the User associated with this webhook, warning, or error.
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "reason")]
    pub reason: models::PendingDisconnectWebhookReason,
    /// The date and time at which the Item is scheduled to disconnect, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "disconnect_time")]
    pub disconnect_time: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "environment")]
    pub environment: models::WebhookEnvironmentValues,
}

impl PendingDisconnectWebhook {
    /// Fired when an Item is expected to be disconnected. The webhook will currently be fired 7 days before the existing Item is scheduled for disconnection. This can be resolved by having the user go through Link’s [update mode](http://plaid.com/docs/link/update-mode). Currently, this webhook is fired only for US or Canadian institutions; in the UK or EU, you should continue to listed for the [`PENDING_EXPIRATION`](https://plaid.com/docs/api/items/#pending_expiration) webhook instead.
    pub fn new(webhook_type: String, webhook_code: String, item_id: String, reason: models::PendingDisconnectWebhookReason, disconnect_time: chrono::DateTime<chrono::FixedOffset>, environment: models::WebhookEnvironmentValues) -> PendingDisconnectWebhook {
        PendingDisconnectWebhook {
            webhook_type,
            webhook_code,
            item_id,
            user_id: None,
            reason,
            disconnect_time,
            environment,
        }
    }
}

