/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PhysicalDocumentExtractedData : Data extracted from a user-submitted document.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PhysicalDocumentExtractedData {
    /// Alpha-numeric ID number extracted via OCR from the user's document image.
    #[serde(rename = "id_number", deserialize_with = "Option::deserialize")]
    pub id_number: Option<String>,
    #[serde(rename = "category")]
    pub category: models::PhysicalDocumentCategory,
    /// The expiration date of the document in the format YYYY-MM-DD (RFC 3339 Section 5.6).
    #[serde(rename = "expiration_date", deserialize_with = "Option::deserialize")]
    pub expiration_date: Option<chrono::NaiveDate>,
    /// The issue date of the document in the format YYYY-MM-DD (RFC 3339 Section 5.6).
    #[serde(rename = "issue_date", deserialize_with = "Option::deserialize")]
    pub issue_date: Option<chrono::NaiveDate>,
    /// Valid, capitalized, two-letter ISO code representing the country of this object. Must be in ISO 3166-1 alpha-2 form.
    #[serde(rename = "issuing_country")]
    pub issuing_country: String,
    /// A subdivision code. \"Subdivision\" is a generic term for \"state\", \"province\", \"prefecture\", \"zone\", etc. For the list of valid codes, see [country subdivision codes](https://plaid.com/documents/country_subdivision_codes.json). Country prefixes are omitted, since they are inferred from the `country` field.
    #[serde(rename = "issuing_region", deserialize_with = "Option::deserialize")]
    pub issuing_region: Option<String>,
    /// A date extracted from the document in the format YYYY-MM-DD (RFC 3339 Section 5.6).
    #[serde(rename = "date_of_birth", deserialize_with = "Option::deserialize")]
    pub date_of_birth: Option<chrono::NaiveDate>,
    #[serde(rename = "address", deserialize_with = "Option::deserialize")]
    pub address: Option<models::IdentityVerificationDocumentAddressResponse>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<models::IdentityVerificationDocumentNameResponse>>,
}

impl PhysicalDocumentExtractedData {
    /// Data extracted from a user-submitted document.
    pub fn new(id_number: Option<String>, category: models::PhysicalDocumentCategory, expiration_date: Option<chrono::NaiveDate>, issue_date: Option<chrono::NaiveDate>, issuing_country: String, issuing_region: Option<String>, date_of_birth: Option<chrono::NaiveDate>, address: Option<models::IdentityVerificationDocumentAddressResponse>) -> PhysicalDocumentExtractedData {
        PhysicalDocumentExtractedData {
            id_number,
            category,
            expiration_date,
            issue_date,
            issuing_country,
            issuing_region,
            date_of_birth,
            address,
            name: None,
        }
    }
}

