/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrismVersions : The versions of Prism products to evaluate
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrismVersions {
    #[serde(rename = "firstdetect", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub firstdetect: Option<Option<models::PrismFirstDetectVersion>>,
    #[serde(rename = "detect", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub detect: Option<Option<models::PrismDetectVersion>>,
    #[serde(rename = "cashscore", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cashscore: Option<Option<models::PrismCashScoreVersion>>,
    #[serde(rename = "extend", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extend: Option<Option<models::PrismExtendVersion>>,
    #[serde(rename = "insights", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub insights: Option<Option<models::PrismInsightsVersion>>,
}

impl PrismVersions {
    /// The versions of Prism products to evaluate
    pub fn new() -> PrismVersions {
        PrismVersions {
            firstdetect: None,
            detect: None,
            cashscore: None,
            extend: None,
            insights: None,
        }
    }
}

