/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrismCashScoreVersion : The version of Prism CashScore. If not specified, will default to v3.
/// The version of Prism CashScore. If not specified, will default to v3.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrismCashScoreVersion {
    #[serde(rename = "4.1")]
    Variant41,
    #[serde(rename = "4")]
    Variant4,
    #[serde(rename = "3_lite")]
    Variant3Lite,
    #[serde(rename = "3")]
    Variant3,

}

impl std::fmt::Display for PrismCashScoreVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant41 => write!(f, "4.1"),
            Self::Variant4 => write!(f, "4"),
            Self::Variant3Lite => write!(f, "3_lite"),
            Self::Variant3 => write!(f, "3"),
        }
    }
}

impl Default for PrismCashScoreVersion {
    fn default() -> PrismCashScoreVersion {
        Self::Variant41
    }
}

