/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrismDetectVersion : The version of Prism Detect
/// The version of Prism Detect
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrismDetectVersion {
    #[serde(rename = "4.1")]
    Variant41,
    #[serde(rename = "4")]
    Variant4,

}

impl std::fmt::Display for PrismDetectVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant41 => write!(f, "4.1"),
            Self::Variant4 => write!(f, "4"),
        }
    }
}

impl Default for PrismDetectVersion {
    fn default() -> PrismDetectVersion {
        Self::Variant41
    }
}

