/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProcessorInvestmentsAuthGetResponse : ProcessorInvestmentsAuthGetResponse defines the response schema for `/processor/investments/auth/get`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessorInvestmentsAuthGetResponse {
    #[serde(rename = "account")]
    pub account: models::AccountBase,
    /// The holdings belonging to the investment account. Details of the securities in the holdings are provided in the `securities` field.
    #[serde(rename = "holdings")]
    pub holdings: Vec<models::Holding>,
    /// Objects describing the securities held in the account.
    #[serde(rename = "securities")]
    pub securities: Vec<models::Security>,
    /// Information about the account owners for the account.
    #[serde(rename = "owners")]
    pub owners: Vec<models::InvestmentsAuthOwner>,
    #[serde(rename = "numbers")]
    pub numbers: models::InvestmentsAuthGetNumbers,
    #[serde(rename = "data_sources")]
    pub data_sources: models::InvestmentsAuthDataSources,
    /// Additional information for accounts of 401k subtype.
    #[serde(rename = "account_details_401k", skip_serializing_if = "Option::is_none")]
    pub account_details_401k: Option<Vec<models::InvestmentsAuthAccountDetails401k>>,
    /// When true, this field indicates that the Item's portfolio was manually created with the Investments Fallback flow.
    #[serde(rename = "is_investments_fallback_item", skip_serializing_if = "Option::is_none")]
    pub is_investments_fallback_item: Option<bool>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl ProcessorInvestmentsAuthGetResponse {
    /// ProcessorInvestmentsAuthGetResponse defines the response schema for `/processor/investments/auth/get`
    pub fn new(account: models::AccountBase, holdings: Vec<models::Holding>, securities: Vec<models::Security>, owners: Vec<models::InvestmentsAuthOwner>, numbers: models::InvestmentsAuthGetNumbers, data_sources: models::InvestmentsAuthDataSources, request_id: String) -> ProcessorInvestmentsAuthGetResponse {
        ProcessorInvestmentsAuthGetResponse {
            account,
            holdings,
            securities,
            owners,
            numbers,
            data_sources,
            account_details_401k: None,
            is_investments_fallback_item: None,
            request_id,
        }
    }
}

