/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProcessorInvestmentsHoldingsGetResponse : ProcessorInvestmentsHoldingsGetResponse defines the response schema for `/processor/invesments/holdings/get`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessorInvestmentsHoldingsGetResponse {
    #[serde(rename = "account")]
    pub account: Box<models::InvestmentAccount>,
    /// The holdings belonging to investment accounts associated with the Item. Details of the securities in the holdings are provided in the `securities` field. 
    #[serde(rename = "holdings")]
    pub holdings: Vec<models::Holding>,
    /// Objects describing the securities held in the account.
    #[serde(rename = "securities")]
    pub securities: Vec<models::Security>,
    /// When true, this field indicates that the Item's portfolio was manually created with the Investments Fallback flow.
    #[serde(rename = "is_investments_fallback_item", skip_serializing_if = "Option::is_none")]
    pub is_investments_fallback_item: Option<bool>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl ProcessorInvestmentsHoldingsGetResponse {
    /// ProcessorInvestmentsHoldingsGetResponse defines the response schema for `/processor/invesments/holdings/get`
    pub fn new(account: models::InvestmentAccount, holdings: Vec<models::Holding>, securities: Vec<models::Security>) -> ProcessorInvestmentsHoldingsGetResponse {
        ProcessorInvestmentsHoldingsGetResponse {
            account: Box::new(account),
            holdings,
            securities,
            is_investments_fallback_item: None,
            request_id: None,
        }
    }
}

