/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProtectComputeRequest : Request object for /protect/compute
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProtectComputeRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// The name of the Trust Index model to use for calculating the Trust Index Score, with a major.minor version suffix. Examples include `ti-link-session-2.0` and `ti-identity-2.0`. The model specified may require certain fields within `model_inputs`. For example, `ti-link-session-2.0` requires the `link` field to be provided in `model_inputs`.
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "user")]
    pub user: models::ProtectUser,
    #[serde(rename = "model_inputs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model_inputs: Option<Option<Box<models::ProtectModelInputs>>>,
}

impl ProtectComputeRequest {
    /// Request object for /protect/compute
    pub fn new(model: String, user: models::ProtectUser) -> ProtectComputeRequest {
        ProtectComputeRequest {
            client_id: None,
            secret: None,
            model,
            user,
            model_inputs: None,
        }
    }
}

