/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProtectUser : Represents an end user for /protect/compute requests.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProtectUser {
    /// The Plaid User ID returned from a previous call to `/user/create`. This or `client_user_id` can be provided, not both.
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// A unique ID representing the end user. Maximum of 128 characters. Typically this will be a user ID number from your application. Personally identifiable information, such as an email address or phone number, should not be used in the `client_user_id`.
    #[serde(rename = "client_user_id", skip_serializing_if = "Option::is_none")]
    pub client_user_id: Option<String>,
}

impl ProtectUser {
    /// Represents an end user for /protect/compute requests.
    pub fn new() -> ProtectUser {
        ProtectUser {
            user_id: None,
            client_user_id: None,
        }
    }
}

