/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProtectUserInsightsGetResponse : Response object for /protect/user/insights/get
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProtectUserInsightsGetResponse {
    /// The Plaid User ID. If a `client_user_id` was provided in the request instead of a `user_id`, a new `user_id` will be generated if one doesn't already exist for that `client_user_id`.
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "latest_scored_event", deserialize_with = "Option::deserialize")]
    pub latest_scored_event: Option<models::LatestScoredEvent>,
    /// List of Protect reports associated with this user, limited to the most recent 100 reports in reverse chronological order (newest first).
    #[serde(rename = "reports", skip_serializing_if = "Option::is_none")]
    pub reports: Option<Vec<models::ProtectReport>>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl ProtectUserInsightsGetResponse {
    /// Response object for /protect/user/insights/get
    pub fn new(user_id: String, latest_scored_event: Option<models::LatestScoredEvent>, request_id: String) -> ProtectUserInsightsGetResponse {
        ProtectUserInsightsGetResponse {
            user_id,
            latest_scored_event,
            reports: None,
            request_id,
        }
    }
}

