/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProtectUserInsightsGetRequest : Request object for /protect/user/insights/get
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProtectUserInsightsGetRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// The Plaid User ID. Either `user_id` or `client_user_id` must be provided.
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// A unique ID representing the end user. Either `user_id` or `client_user_id` must be provided.
    #[serde(rename = "client_user_id", skip_serializing_if = "Option::is_none")]
    pub client_user_id: Option<String>,
}

impl ProtectUserInsightsGetRequest {
    /// Request object for /protect/user/insights/get
    pub fn new() -> ProtectUserInsightsGetRequest {
        ProtectUserInsightsGetRequest {
            client_id: None,
            secret: None,
            user_id: None,
            client_user_id: None,
        }
    }
}

