/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProtectEventSendResponse : Response object for /protect/event/send
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProtectEventSendResponse {
    /// The id of the recorded event.
    #[serde(rename = "event_id")]
    pub event_id: String,
    #[serde(rename = "trust_index", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trust_index: Option<Option<models::TrustIndex>>,
    /// Event fraud attributes as an arbitrary set of key-value pairs.
    #[serde(rename = "fraud_attributes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fraud_attributes: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl ProtectEventSendResponse {
    /// Response object for /protect/event/send
    pub fn new(event_id: String, request_id: String) -> ProtectEventSendResponse {
        ProtectEventSendResponse {
            event_id,
            trust_index: None,
            fraud_attributes: None,
            request_id,
        }
    }
}

