/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProviderBusinessName : Name associated with a business
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderBusinessName {
    /// Indicates whether this is the primary name for the business.
    #[serde(rename = "is_primary")]
    pub is_primary: bool,
    /// The name of the business. Must have at least one character and a maximum length of 500 characters.
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
}

impl ProviderBusinessName {
    /// Name associated with a business
    pub fn new(is_primary: bool, name: Option<String>) -> ProviderBusinessName {
        ProviderBusinessName {
            is_primary,
            name,
        }
    }
}

