/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecommendationString : The recommendation result for that date.
/// The recommendation result for that date.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecommendationString {
    #[serde(rename = "RECOMMENDED")]
    Recommended,
    #[serde(rename = "NOT_RECOMMENDED")]
    NotRecommended,
    #[serde(rename = "UNKNOWN")]
    Unknown,

}

impl std::fmt::Display for RecommendationString {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Recommended => write!(f, "RECOMMENDED"),
            Self::NotRecommended => write!(f, "NOT_RECOMMENDED"),
            Self::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

impl Default for RecommendationString {
    fn default() -> RecommendationString {
        Self::Recommended
    }
}

