/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RiskIndicators : Risk indicators focus on providing signal on the possibility of a borrower defaulting on their loan repayments by providing data points related to its payment behavior, debt, and other relevant financial information, helping lenders gauge the level of risk involved in a certain operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskIndicators {
    #[serde(rename = "bank_penalties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bank_penalties: Option<Option<models::BankPenaltiesIndicators>>,
    #[serde(rename = "gambling", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gambling: Option<Option<models::GamblingIndicators>>,
    #[serde(rename = "loan_disbursements", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub loan_disbursements: Option<Option<models::LoanDisbursementsIndicators>>,
    #[serde(rename = "loan_payments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub loan_payments: Option<Option<models::LoanPaymentsIndicators>>,
    #[serde(rename = "negative_balance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub negative_balance: Option<Option<models::NegativeBalanceInsights>>,
}

impl RiskIndicators {
    /// Risk indicators focus on providing signal on the possibility of a borrower defaulting on their loan repayments by providing data points related to its payment behavior, debt, and other relevant financial information, helping lenders gauge the level of risk involved in a certain operation.
    pub fn new() -> RiskIndicators {
        RiskIndicators {
            bank_penalties: None,
            gambling: None,
            loan_disbursements: None,
            loan_payments: None,
            negative_balance: None,
        }
    }
}

