/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RiskCheckPhone : Result summary object specifying values for `phone` attributes of risk check.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskCheckPhone {
    /// A list of online services where this phone number has been detected to have accounts or other activity.
    #[serde(rename = "linked_services")]
    pub linked_services: Vec<models::RiskCheckLinkedService>,
    #[serde(rename = "risk_level", skip_serializing_if = "Option::is_none")]
    pub risk_level: Option<models::RiskLevel>,
    /// List of factors, when available, that contribute towards the risk level of the given risk check type.
    #[serde(rename = "factors", skip_serializing_if = "Option::is_none")]
    pub factors: Option<Vec<String>>,
}

impl RiskCheckPhone {
    /// Result summary object specifying values for `phone` attributes of risk check.
    pub fn new(linked_services: Vec<models::RiskCheckLinkedService>) -> RiskCheckPhone {
        RiskCheckPhone {
            linked_services,
            risk_level: None,
            factors: None,
        }
    }
}

