/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RiskCheckFacialDuplicate : Result summary object specifying values for the `facial_duplicate` attributes of risk check.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskCheckFacialDuplicate {
    /// ID of the associated Identity Verification attempt.
    #[serde(rename = "id")]
    pub id: String,
    /// Similarity score of the match. Ranges from 0 to 100.
    #[serde(rename = "similarity")]
    pub similarity: i32,
    /// Whether this match occurred after the session was complete. For example, this would be `true` if a later session ended up matching this one.
    #[serde(rename = "matched_after_completed")]
    pub matched_after_completed: bool,
}

impl RiskCheckFacialDuplicate {
    /// Result summary object specifying values for the `facial_duplicate` attributes of risk check.
    pub fn new(id: String, similarity: i32, matched_after_completed: bool) -> RiskCheckFacialDuplicate {
        RiskCheckFacialDuplicate {
            id,
            similarity,
            matched_after_completed,
        }
    }
}

