/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RiskProfile : RiskProfile is deprecated, use `ruleset` instead.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskProfile {
    /// The key of the risk profile used for this transaction.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Legacy method of inspecting the result of the ruleset. New integrations should simply use the “result” property instead. This value will be omitted if you do not have a live existing integration with rules using this field.
    #[serde(rename = "outcome", skip_serializing_if = "Option::is_none")]
    pub outcome: Option<String>,
}

impl RiskProfile {
    /// RiskProfile is deprecated, use `ruleset` instead.
    pub fn new() -> RiskProfile {
        RiskProfile {
            key: None,
            outcome: None,
        }
    }
}

