/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RiskCheckSyntheticIdentity : Field containing the data used in determining the outcome of the synthetic identity risk check.  Contains the following fields:  `score` - A score from 0 to 100 indicating the likelihood that the user is a synthetic identity.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskCheckSyntheticIdentity {
    /// A score from 0 to 100 indicating the likelihood that the user is a synthetic identity.
    #[serde(rename = "score")]
    pub score: i32,
    #[serde(rename = "risk_level", skip_serializing_if = "Option::is_none")]
    pub risk_level: Option<models::RiskLevel>,
    #[serde(rename = "first_party_synthetic_fraud", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_party_synthetic_fraud: Option<Option<models::SyntheticFraud>>,
    #[serde(rename = "third_party_synthetic_fraud", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub third_party_synthetic_fraud: Option<Option<models::SyntheticFraud>>,
}

impl RiskCheckSyntheticIdentity {
    /// Field containing the data used in determining the outcome of the synthetic identity risk check.  Contains the following fields:  `score` - A score from 0 to 100 indicating the likelihood that the user is a synthetic identity.
    pub fn new(score: i32) -> RiskCheckSyntheticIdentity {
        RiskCheckSyntheticIdentity {
            score,
            risk_level: None,
            first_party_synthetic_fraud: None,
            third_party_synthetic_fraud: None,
        }
    }
}

