/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RiskCheckDetails : Additional information for the `risk_check` step.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiskCheckDetails {
    #[serde(rename = "status")]
    pub status: models::IdentityVerificationStepStatus,
    #[serde(rename = "behavior", deserialize_with = "Option::deserialize")]
    pub behavior: Option<models::RiskCheckBehavior>,
    #[serde(rename = "email", deserialize_with = "Option::deserialize")]
    pub email: Option<models::RiskCheckEmail>,
    #[serde(rename = "phone", deserialize_with = "Option::deserialize")]
    pub phone: Option<models::RiskCheckPhone>,
    /// Array of result summary objects specifying values for `device` attributes of risk check.
    #[serde(rename = "devices")]
    pub devices: Vec<models::RiskCheckDevice>,
    #[serde(rename = "identity_abuse_signals", deserialize_with = "Option::deserialize")]
    pub identity_abuse_signals: Option<models::RiskCheckIdentityAbuseSignals>,
    #[serde(rename = "network", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub network: Option<Option<models::RiskCheckNetwork>>,
    /// The attributes related to the facial duplicates captured in risk check.
    #[serde(rename = "facial_duplicates")]
    pub facial_duplicates: Vec<models::RiskCheckFacialDuplicate>,
    /// The trust index score for the `risk_check` step.
    #[serde(rename = "trust_index_score", deserialize_with = "Option::deserialize")]
    pub trust_index_score: Option<i32>,
}

impl RiskCheckDetails {
    /// Additional information for the `risk_check` step.
    pub fn new(status: models::IdentityVerificationStepStatus, behavior: Option<models::RiskCheckBehavior>, email: Option<models::RiskCheckEmail>, phone: Option<models::RiskCheckPhone>, devices: Vec<models::RiskCheckDevice>, identity_abuse_signals: Option<models::RiskCheckIdentityAbuseSignals>, facial_duplicates: Vec<models::RiskCheckFacialDuplicate>, trust_index_score: Option<i32>) -> RiskCheckDetails {
        RiskCheckDetails {
            status,
            behavior,
            email,
            phone,
            devices,
            identity_abuse_signals,
            network: None,
            facial_duplicates,
            trust_index_score,
        }
    }
}

