/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RuleDetails : Rules are run in numerical order. The first rule with a logic match is triggered. These are the details of that rule.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RuleDetails {
    /// An optional message attached to the triggered rule, defined within the Dashboard, for your internal use. Useful for debugging, such as “Account appears to be closed.”
    #[serde(rename = "internal_note", skip_serializing_if = "Option::is_none")]
    pub internal_note: Option<String>,
    /// A string key, defined within the Dashboard, used to trigger programmatic behavior for a certain result. For instance, you could optionally choose to define a \"3-day-hold\" `custom_action_key` for an ACCEPT result.
    #[serde(rename = "custom_action_key", skip_serializing_if = "Option::is_none")]
    pub custom_action_key: Option<String>,
}

impl RuleDetails {
    /// Rules are run in numerical order. The first rule with a logic match is triggered. These are the details of that rule.
    pub fn new() -> RuleDetails {
        RuleDetails {
            internal_note: None,
            custom_action_key: None,
        }
    }
}

