/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SandboxPaymentSimulateResponse : SandboxPaymentSimulateResponse defines the response schema for `/sandbox/payment/simulate`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxPaymentSimulateResponse {
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
    #[serde(rename = "old_status")]
    pub old_status: models::PaymentInitiationPaymentStatus,
    #[serde(rename = "new_status")]
    pub new_status: models::PaymentInitiationPaymentStatus,
}

impl SandboxPaymentSimulateResponse {
    /// SandboxPaymentSimulateResponse defines the response schema for `/sandbox/payment/simulate`
    pub fn new(request_id: String, old_status: models::PaymentInitiationPaymentStatus, new_status: models::PaymentInitiationPaymentStatus) -> SandboxPaymentSimulateResponse {
        SandboxPaymentSimulateResponse {
            request_id,
            old_status,
            new_status,
        }
    }
}

