/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SandboxTransactionsCreateResponse : SandboxTransactionsCreateResponse defines the response schema for `/sandbox/transactions/create`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxTransactionsCreateResponse {
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl SandboxTransactionsCreateResponse {
    /// SandboxTransactionsCreateResponse defines the response schema for `/sandbox/transactions/create`
    pub fn new(request_id: String) -> SandboxTransactionsCreateResponse {
        SandboxTransactionsCreateResponse {
            request_id,
        }
    }
}

