/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SandboxTransferRfpSimulateRequest : Defines the request schema for `/sandbox/transfer/rfp/simulate`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxTransferRfpSimulateRequest {
    /// Plaid’s unique identifier for a transfer.
    #[serde(rename = "transfer_id")]
    pub transfer_id: String,
    #[serde(rename = "action")]
    pub action: models::SandboxTransferRfpSimulateAction,
    /// The transfer amount provided by the caller for validation purposes, must match the amount on the transfer associated with the provided `transfer_id`. 
    #[serde(rename = "amount")]
    pub amount: String,
    /// The client name provided by the caller for validation purposes, must match the sender client name on the transfer associated with the provided `transfer_id`. 
    #[serde(rename = "client_name")]
    pub client_name: String,
}

impl SandboxTransferRfpSimulateRequest {
    /// Defines the request schema for `/sandbox/transfer/rfp/simulate`
    pub fn new(transfer_id: String, action: models::SandboxTransferRfpSimulateAction, amount: String, client_name: String) -> SandboxTransferRfpSimulateRequest {
        SandboxTransferRfpSimulateRequest {
            transfer_id,
            action,
            amount,
            client_name,
        }
    }
}

