/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SandboxPublicTokenCreateRequestOptionsStatements : An optional set of parameters corresponding to statements options.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxPublicTokenCreateRequestOptionsStatements {
    /// The earliest date for which to fetch statements history. Dates should be formatted as YYYY-MM-DD.
    #[serde(rename = "start_date")]
    pub start_date: chrono::NaiveDate,
    /// The most recent date for which to fetch statements history. Dates should be formatted as YYYY-MM-DD.
    #[serde(rename = "end_date")]
    pub end_date: chrono::NaiveDate,
}

impl SandboxPublicTokenCreateRequestOptionsStatements {
    /// An optional set of parameters corresponding to statements options.
    pub fn new(start_date: chrono::NaiveDate, end_date: chrono::NaiveDate) -> SandboxPublicTokenCreateRequestOptionsStatements {
        SandboxPublicTokenCreateRequestOptionsStatements {
            start_date,
            end_date,
        }
    }
}

