/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SandboxItemApplicationSeedResponse : SandboxItemApplicationSeedResponse defines the response schema for `/sandbox/item/application/seed`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxItemApplicationSeedResponse {
    /// The `item_id` of the newly seeded item representing the application connection.
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl SandboxItemApplicationSeedResponse {
    /// SandboxItemApplicationSeedResponse defines the response schema for `/sandbox/item/application/seed`
    pub fn new(item_id: String, request_id: String) -> SandboxItemApplicationSeedResponse {
        SandboxItemApplicationSeedResponse {
            item_id,
            request_id,
        }
    }
}

