/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SandboxBankIncomeWebhookFireRequestWebhookCode : The webhook codes this endpoint can be used to test
/// The webhook codes this endpoint can be used to test
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SandboxBankIncomeWebhookFireRequestWebhookCode {
    #[serde(rename = "BANK_INCOME_REFRESH_UPDATE")]
    BankIncomeRefreshUpdate,
    #[serde(rename = "BANK_INCOME_REFRESH_COMPLETE")]
    BankIncomeRefreshComplete,

}

impl std::fmt::Display for SandboxBankIncomeWebhookFireRequestWebhookCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BankIncomeRefreshUpdate => write!(f, "BANK_INCOME_REFRESH_UPDATE"),
            Self::BankIncomeRefreshComplete => write!(f, "BANK_INCOME_REFRESH_COMPLETE"),
        }
    }
}

impl Default for SandboxBankIncomeWebhookFireRequestWebhookCode {
    fn default() -> SandboxBankIncomeWebhookFireRequestWebhookCode {
        Self::BankIncomeRefreshUpdate
    }
}

