/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SessionTokenCreateResponseLink : Response data for `/session/token/create` intended for use with the Link SDK.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionTokenCreateResponseLink {
    /// A Link token, which can be supplied to Link in order to initialize it and receive a `public_token`.
    #[serde(rename = "link_token")]
    pub link_token: String,
    /// The expiration date for the `link_token`, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format. A `link_token` created to generate a `public_token` that will be exchanged for a new `access_token` expires after 4 hours. A `link_token` created for an existing Item (such as when updating an existing `access_token` by launching Link in update mode) expires after 30 minutes.
    #[serde(rename = "expiration")]
    pub expiration: chrono::DateTime<chrono::FixedOffset>,
    /// A unique user identifier, created by `/user/create`. Integrations that began using `/user/create` after December 10, 2025 use this field to identify a user instead of the `user_token`. For more details, see [new user APIs](https://plaid.com/docs/api/users/user-apis).
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl SessionTokenCreateResponseLink {
    /// Response data for `/session/token/create` intended for use with the Link SDK.
    pub fn new(link_token: String, expiration: chrono::DateTime<chrono::FixedOffset>) -> SessionTokenCreateResponseLink {
        SessionTokenCreateResponseLink {
            link_token,
            expiration,
            user_id: None,
        }
    }
}

