/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SignalScheduleRecommendation : Conveys information on if a retry is recommended on a given date
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignalScheduleRecommendation {
    /// The specific date for submitting the debit entry, formatted in ISO 8601 (e.g., \"2025-01-17\").
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<chrono::NaiveDate>,
    #[serde(rename = "recommendation", skip_serializing_if = "Option::is_none")]
    pub recommendation: Option<models::RecommendationString>,
    /// The rank of the recommendation based on the likelihood of debit success, with 1 representing the most optimal date. Dates with `NOT_RECOMMENDED` or `UNKNOWN` will have rank `null`.
    #[serde(rename = "rank", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rank: Option<Option<i32>>,
}

impl SignalScheduleRecommendation {
    /// Conveys information on if a retry is recommended on a given date
    pub fn new() -> SignalScheduleRecommendation {
        SignalScheduleRecommendation {
            date: None,
            recommendation: None,
            rank: None,
        }
    }
}

