/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatementsStatement : A statement's metadata associated with an account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatementsStatement {
    /// Plaid's unique identifier for the statement.
    #[serde(rename = "statement_id")]
    pub statement_id: String,
    /// Date when the statement was posted by the FI, if known
    #[serde(rename = "date_posted", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_posted: Option<Option<chrono::NaiveDate>>,
    /// Month of the year. Possible values: 1 through 12 (January through December).
    #[serde(rename = "month")]
    pub month: i32,
    /// The year of statement.
    #[serde(rename = "year")]
    pub year: i32,
}

impl StatementsStatement {
    /// A statement's metadata associated with an account
    pub fn new(statement_id: String, month: i32, year: i32) -> StatementsStatement {
        StatementsStatement {
            statement_id,
            date_posted: None,
            month,
            year,
        }
    }
}

