/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferCreditUsageConfiguration : Specifies the originator's expected usage of credits. For all dollar amounts, use a decimal string with two digits of precision e.g. \"10.00\". This field is required if the originator is expected to process credit transfers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferCreditUsageConfiguration {
    #[serde(rename = "expected_frequency")]
    pub expected_frequency: models::OriginatorExpectedTransferFrequency,
    /// The originator’s expected highest amount for a single credit transfer.
    #[serde(rename = "expected_highest_amount")]
    pub expected_highest_amount: String,
    /// The originator’s expected average amount per credit.
    #[serde(rename = "expected_average_amount")]
    pub expected_average_amount: String,
    /// The originator’s monthly expected ACH credit processing amount for the next 6-12 months.
    #[serde(rename = "expected_monthly_amount")]
    pub expected_monthly_amount: String,
    /// Specifies the expected use cases for the originator’s credit transfers. This should be a list that contains one or more of the following codes:  `\"ccd\"` - Corporate Credit or Debit - fund transfer between two corporate bank accounts  `\"ppd\"` - Prearranged Payment or Deposit. The transfer is part of a pre-existing relationship with a consumer. Authorization was obtained from the consumer in person via writing, or through online authorization, or via an electronic document signing, e.g. Docusign. For example language for online authorization, see the 2025 Nacha Operating Rules — Section 2.3.2, Authorization of Entries via Electronic Means. Can be used for credits or debits.  `\"web\"` - Internet-Initiated Entry. The transfer debits a consumer’s bank account. Authorization from the consumer is obtained over the Internet (e.g. a web or mobile application). Can be used for single debits or recurring debits.
    #[serde(rename = "sec_codes")]
    pub sec_codes: Vec<models::CreditAchClass>,
}

impl TransferCreditUsageConfiguration {
    /// Specifies the originator's expected usage of credits. For all dollar amounts, use a decimal string with two digits of precision e.g. \"10.00\". This field is required if the originator is expected to process credit transfers.
    pub fn new(expected_frequency: models::OriginatorExpectedTransferFrequency, expected_highest_amount: String, expected_average_amount: String, expected_monthly_amount: String, sec_codes: Vec<models::CreditAchClass>) -> TransferCreditUsageConfiguration {
        TransferCreditUsageConfiguration {
            expected_frequency,
            expected_highest_amount,
            expected_average_amount,
            expected_monthly_amount,
            sec_codes,
        }
    }
}

