/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferAuthorizationGuaranteeDecision : Indicates whether the transfer is guaranteed by Plaid (Guarantee customers only). This field will contain either `GUARANTEED` or `NOT_GUARANTEED` indicating whether Plaid will guarantee the transfer.
/// Indicates whether the transfer is guaranteed by Plaid (Guarantee customers only). This field will contain either `GUARANTEED` or `NOT_GUARANTEED` indicating whether Plaid will guarantee the transfer.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransferAuthorizationGuaranteeDecision {
    #[serde(rename = "GUARANTEED")]
    Guaranteed,
    #[serde(rename = "NOT_GUARANTEED")]
    NotGuaranteed,

}

impl std::fmt::Display for TransferAuthorizationGuaranteeDecision {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Guaranteed => write!(f, "GUARANTEED"),
            Self::NotGuaranteed => write!(f, "NOT_GUARANTEED"),
        }
    }
}

impl Default for TransferAuthorizationGuaranteeDecision {
    fn default() -> TransferAuthorizationGuaranteeDecision {
        Self::Guaranteed
    }
}

