/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionsRulesRemoveRequest : TransactionsRulesRemoveRequest defines the request schema for `/beta/transactions/rules/v1/remove`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionsRulesRemoveRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// A unique ID representing the end user the rule belongs to.
    #[serde(rename = "client_user_id")]
    pub client_user_id: String,
    /// A rule's unique identifier
    #[serde(rename = "rule_id")]
    pub rule_id: String,
}

impl TransactionsRulesRemoveRequest {
    /// TransactionsRulesRemoveRequest defines the request schema for `/beta/transactions/rules/v1/remove`
    pub fn new(client_user_id: String, rule_id: String) -> TransactionsRulesRemoveRequest {
        TransactionsRulesRemoveRequest {
            client_id: None,
            secret: None,
            client_user_id,
            rule_id,
        }
    }
}

