/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionsCategoryRule : A representation of a transactions category rule.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionsCategoryRule {
    /// A unique identifier of the rule created
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The Plaid-generated unique identifier for the end user this rule belongs to.
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// Date and time when a rule was created in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format ( `YYYY-MM-DDTHH:mm:ssZ` ). 
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Date and time when a rule was last updated in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format ( `YYYY-MM-DDTHH:mm:ssZ` ). 
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// A personal finance primary category. See the [taxonomy csv file](https://plaid.com/documents/pfc-taxonomy-all.csv) for a full list of personal finance categories. 
    #[serde(rename = "pfc_primary_category", skip_serializing_if = "Option::is_none")]
    pub pfc_primary_category: Option<String>,
    /// A personal finance detailed category. See the [taxonomy csv file](https://plaid.com/documents/pfc-taxonomy-all.csv) for a full list of personal finance categories. 
    #[serde(rename = "pfc_detailed_category", skip_serializing_if = "Option::is_none")]
    pub pfc_detailed_category: Option<String>,
    #[serde(rename = "rule_details", skip_serializing_if = "Option::is_none")]
    pub rule_details: Option<Box<models::TransactionsRuleDetails>>,
}

impl TransactionsCategoryRule {
    /// A representation of a transactions category rule.
    pub fn new() -> TransactionsCategoryRule {
        TransactionsCategoryRule {
            id: None,
            user_id: None,
            created_at: None,
            updated_at: None,
            pfc_primary_category: None,
            pfc_detailed_category: None,
            rule_details: None,
        }
    }
}

