/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferPlatformOnboardingUpdateWebhook : Fired when the status of an onboarding originator has been updated. Call `/transfer/originator/get` to check the latest status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferPlatformOnboardingUpdateWebhook {
    /// `\"TRANSFER\"`
    #[serde(rename = "webhook_type")]
    pub webhook_type: String,
    /// `\"PLATFORM_ONBOARDING_UPDATE\"`
    #[serde(rename = "webhook_code")]
    pub webhook_code: String,
    /// The client ID of the originator
    #[serde(rename = "originator_client_id")]
    pub originator_client_id: String,
    #[serde(rename = "environment")]
    pub environment: models::WebhookEnvironmentValues,
}

impl TransferPlatformOnboardingUpdateWebhook {
    /// Fired when the status of an onboarding originator has been updated. Call `/transfer/originator/get` to check the latest status
    pub fn new(webhook_type: String, webhook_code: String, originator_client_id: String, environment: models::WebhookEnvironmentValues) -> TransferPlatformOnboardingUpdateWebhook {
        TransferPlatformOnboardingUpdateWebhook {
            webhook_type,
            webhook_code,
            originator_client_id,
            environment,
        }
    }
}

