/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferOriginatorFundingAccountCreateResponse : Defines the response schema for `/transfer/originator/funding_account/create`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferOriginatorFundingAccountCreateResponse {
    /// The id of the funding account to use, available in the Plaid Dashboard. This determines which of your business checking accounts will be credited or debited.
    #[serde(rename = "funding_account_id", skip_serializing_if = "Option::is_none")]
    pub funding_account_id: Option<String>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl TransferOriginatorFundingAccountCreateResponse {
    /// Defines the response schema for `/transfer/originator/funding_account/create`
    pub fn new(request_id: String) -> TransferOriginatorFundingAccountCreateResponse {
        TransferOriginatorFundingAccountCreateResponse {
            funding_account_id: None,
            request_id,
        }
    }
}

