/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionsRulesCreateRequest : TransactionsRulesCreateRequest defines the request schema for `beta/transactions/rules/v1/create`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionsRulesCreateRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// A unique ID representing the end user. This ID is used to associate rules with a specific user.
    #[serde(rename = "client_user_id")]
    pub client_user_id: String,
    /// A personal finance primary category. See the [taxonomy csv file](https://plaid.com/documents/pfc-taxonomy-all.csv) for a full list of personal finance categories. 
    #[serde(rename = "pfc_primary_category")]
    pub pfc_primary_category: String,
    /// A personal finance detailed category. See the [taxonomy csv file](https://plaid.com/documents/pfc-taxonomy-all.csv) for a full list of personal finance categories. 
    #[serde(rename = "pfc_detailed_category")]
    pub pfc_detailed_category: String,
    #[serde(rename = "rule_details")]
    pub rule_details: Box<models::TransactionsRuleDetails>,
}

impl TransactionsRulesCreateRequest {
    /// TransactionsRulesCreateRequest defines the request schema for `beta/transactions/rules/v1/create`
    pub fn new(client_user_id: String, pfc_primary_category: String, pfc_detailed_category: String, rule_details: models::TransactionsRuleDetails) -> TransactionsRulesCreateRequest {
        TransactionsRulesCreateRequest {
            client_id: None,
            secret: None,
            client_user_id,
            pfc_primary_category,
            pfc_detailed_category,
            rule_details: Box::new(rule_details),
        }
    }
}

