/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferLedgerEvent : Represents a ledger event in the Transfers API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferLedgerEvent {
    /// Plaid's unique identifier for this ledger event.
    #[serde(rename = "ledger_event_id")]
    pub ledger_event_id: String,
    /// The ID of the ledger this event belongs to.
    #[serde(rename = "ledger_id")]
    pub ledger_id: String,
    /// The amount of the ledger event as a decimal string.
    #[serde(rename = "amount")]
    pub amount: String,
    /// The ID of the transfer source that triggered this ledger event.
    #[serde(rename = "transfer_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transfer_id: Option<Option<String>>,
    /// The ID of the refund source that triggered this ledger event.
    #[serde(rename = "refund_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub refund_id: Option<Option<String>>,
    /// The ID of the sweep source that triggered this ledger event.
    #[serde(rename = "sweep_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sweep_id: Option<Option<String>>,
    /// A description of the ledger event.
    #[serde(rename = "description")]
    pub description: String,
    /// The new pending balance after this event.
    #[serde(rename = "pending_balance")]
    pub pending_balance: String,
    /// The new available balance after this event.
    #[serde(rename = "available_balance")]
    pub available_balance: String,
    /// The type of balance that was impacted by this event.
    #[serde(rename = "type")]
    pub r#type: String,
    /// The datetime when this ledger event occurred.
    #[serde(rename = "timestamp")]
    pub timestamp: chrono::DateTime<chrono::FixedOffset>,
}

impl TransferLedgerEvent {
    /// Represents a ledger event in the Transfers API.
    pub fn new(ledger_event_id: String, ledger_id: String, amount: String, description: String, pending_balance: String, available_balance: String, r#type: String, timestamp: chrono::DateTime<chrono::FixedOffset>) -> TransferLedgerEvent {
        TransferLedgerEvent {
            ledger_event_id,
            ledger_id,
            amount,
            transfer_id: None,
            refund_id: None,
            sweep_id: None,
            description,
            pending_balance,
            available_balance,
            r#type,
            timestamp,
        }
    }
}

