/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionsRulesListRequest : TransactionsRulesListRequest defines the request schema for `/beta/transactions/rules/v1/list`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionsRulesListRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// A unique ID representing the end user whose rules should be listed.
    #[serde(rename = "client_user_id")]
    pub client_user_id: String,
}

impl TransactionsRulesListRequest {
    /// TransactionsRulesListRequest defines the request schema for `/beta/transactions/rules/v1/list`
    pub fn new(client_user_id: String) -> TransactionsRulesListRequest {
        TransactionsRulesListRequest {
            client_id: None,
            secret: None,
            client_user_id,
        }
    }
}

