/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TrustIndexSubscores : Contains sub-score metadata.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrustIndexSubscores {
    #[serde(rename = "device_and_connection", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub device_and_connection: Option<Option<models::TrustIndexSubscore>>,
    #[serde(rename = "bank_account_insights", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bank_account_insights: Option<Option<models::TrustIndexSubscore>>,
}

impl TrustIndexSubscores {
    /// Contains sub-score metadata.
    pub fn new() -> TrustIndexSubscores {
        TrustIndexSubscores {
            device_and_connection: None,
            bank_account_insights: None,
        }
    }
}

