/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserAccountSessionEventSendResponse : UserAccountSessionEventSendResponse defines the response schema for `/user_account/session/event/send`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAccountSessionEventSendResponse {
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl UserAccountSessionEventSendResponse {
    /// UserAccountSessionEventSendResponse defines the response schema for `/user_account/session/event/send`
    pub fn new(request_id: String) -> UserAccountSessionEventSendResponse {
        UserAccountSessionEventSendResponse {
            request_id,
        }
    }
}

