/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserAccountIdentityOfficialDocument : Official identity document edit statistics.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAccountIdentityOfficialDocument {
    #[serde(rename = "ssn", skip_serializing_if = "Option::is_none")]
    pub ssn: Option<models::UserAccountIdentityEditCounts>,
}

impl UserAccountIdentityOfficialDocument {
    /// Official identity document edit statistics.
    pub fn new() -> UserAccountIdentityOfficialDocument {
        UserAccountIdentityOfficialDocument {
            ssn: None,
        }
    }
}

