/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserAccountSessionEventSendRequest : UserAccountSessionEventSendRequest defines the request schema for `/user_account/session/event/send`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAccountSessionEventSendRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// Optional cohort identifier for the user session.
    #[serde(rename = "cohort_id", skip_serializing_if = "Option::is_none")]
    pub cohort_id: Option<String>,
    /// The Link session identifier.
    #[serde(rename = "link_session_id")]
    pub link_session_id: String,
    #[serde(rename = "event")]
    pub event: Box<models::UserAccountSessionEvent>,
}

impl UserAccountSessionEventSendRequest {
    /// UserAccountSessionEventSendRequest defines the request schema for `/user_account/session/event/send`
    pub fn new(link_session_id: String, event: models::UserAccountSessionEvent) -> UserAccountSessionEventSendRequest {
        UserAccountSessionEventSendRequest {
            client_id: None,
            secret: None,
            cohort_id: None,
            link_session_id,
            event: Box::new(event),
        }
    }
}

