/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserBasedProducts : A list of user-based products. User-based products include Financial Management products, Protect products, CRA products, and subscription products.
/// A list of user-based products. User-based products include Financial Management products, Protect products, CRA products, and subscription products.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserBasedProducts {
    #[serde(rename = "cra_base_report")]
    CraBaseReport,
    #[serde(rename = "cra_income_insights")]
    CraIncomeInsights,
    #[serde(rename = "cra_partner_insights")]
    CraPartnerInsights,
    #[serde(rename = "cra_network_insights")]
    CraNetworkInsights,
    #[serde(rename = "cra_cashflow_insights")]
    CraCashflowInsights,
    #[serde(rename = "cra_monitoring")]
    CraMonitoring,
    #[serde(rename = "cra_lend_score")]
    CraLendScore,
    #[serde(rename = "cra_plaid_credit_score")]
    CraPlaidCreditScore,
    #[serde(rename = "investments")]
    Investments,
    #[serde(rename = "liabilities")]
    Liabilities,
    #[serde(rename = "protect_linked_bank")]
    ProtectLinkedBank,
    #[serde(rename = "protect_transactions")]
    ProtectTransactions,
    #[serde(rename = "transactions")]
    Transactions,

}

impl std::fmt::Display for UserBasedProducts {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CraBaseReport => write!(f, "cra_base_report"),
            Self::CraIncomeInsights => write!(f, "cra_income_insights"),
            Self::CraPartnerInsights => write!(f, "cra_partner_insights"),
            Self::CraNetworkInsights => write!(f, "cra_network_insights"),
            Self::CraCashflowInsights => write!(f, "cra_cashflow_insights"),
            Self::CraMonitoring => write!(f, "cra_monitoring"),
            Self::CraLendScore => write!(f, "cra_lend_score"),
            Self::CraPlaidCreditScore => write!(f, "cra_plaid_credit_score"),
            Self::Investments => write!(f, "investments"),
            Self::Liabilities => write!(f, "liabilities"),
            Self::ProtectLinkedBank => write!(f, "protect_linked_bank"),
            Self::ProtectTransactions => write!(f, "protect_transactions"),
            Self::Transactions => write!(f, "transactions"),
        }
    }
}

impl Default for UserBasedProducts {
    fn default() -> UserBasedProducts {
        Self::CraBaseReport
    }
}

