/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserGetResponse : UserGetResponse defines the response schema for `/user/get`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserGetResponse {
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
    /// A unique user identifier, created by `/user/create`. Integrations that began using `/user/create` after December 10, 2025 use this field to identify a user instead of the `user_token`. For more details, see [new user APIs](https://plaid.com/docs/api/users/user-apis).
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// Client provided user ID.
    #[serde(rename = "client_user_id", deserialize_with = "Option::deserialize")]
    pub client_user_id: Option<String>,
    /// Timestamp of user creation.
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Timestamp of last user update.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "identity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Option<models::ClientUserIdentity>>,
}

impl UserGetResponse {
    /// UserGetResponse defines the response schema for `/user/get`.
    pub fn new(request_id: String, user_id: String, client_user_id: Option<String>, created_at: chrono::DateTime<chrono::FixedOffset>) -> UserGetResponse {
        UserGetResponse {
            request_id,
            user_id,
            client_user_id,
            created_at,
            updated_at: None,
            identity: None,
        }
    }
}

