/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserAccountIdentityEditHistory : Statistics tracking the number of edits made to identity fields over various time periods.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAccountIdentityEditHistory {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<models::UserAccountIdentityEditCounts>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<models::UserAccountIdentityEditCounts>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<models::UserAccountIdentityEditCounts>,
    #[serde(rename = "date_of_birth", skip_serializing_if = "Option::is_none")]
    pub date_of_birth: Option<models::UserAccountIdentityEditCounts>,
    #[serde(rename = "official_document", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub official_document: Option<Option<models::UserAccountIdentityOfficialDocument>>,
}

impl UserAccountIdentityEditHistory {
    /// Statistics tracking the number of edits made to identity fields over various time periods.
    pub fn new() -> UserAccountIdentityEditHistory {
        UserAccountIdentityEditHistory {
            name: None,
            address: None,
            email: None,
            date_of_birth: None,
            official_document: None,
        }
    }
}

