/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserProductsTerminateRequest : UserProductsTerminateRequest defines the request schema for `/user/products/terminate`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserProductsTerminateRequest {
    /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// A unique user identifier, created by `/user/create`. Integrations that began using `/user/create` after December 10, 2025 use this field to identify a user instead of the `user_token`. For more details, see [new user APIs](https://plaid.com/docs/api/users/user-apis).
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// An optional list of user-based products to terminate. If not provided, all user-based products will be terminated.
    #[serde(rename = "products", skip_serializing_if = "Option::is_none")]
    pub products: Option<Vec<models::UserBasedProducts>>,
}

impl UserProductsTerminateRequest {
    /// UserProductsTerminateRequest defines the request schema for `/user/products/terminate`
    pub fn new(user_id: String) -> UserProductsTerminateRequest {
        UserProductsTerminateRequest {
            client_id: None,
            secret: None,
            user_id,
            products: None,
        }
    }
}

