/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WalletTransactionListResponse : WalletTransactionListResponse defines the response schema for `/wallet/transaction/list`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletTransactionListResponse {
    /// An array of transactions of an e-wallet, associated with the given `wallet_id`
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::WalletTransaction>,
    /// The value that, when used as the optional `cursor` parameter to `/wallet/transaction/list`, will return the corresponding transaction as its first entry.
    #[serde(rename = "next_cursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl WalletTransactionListResponse {
    /// WalletTransactionListResponse defines the response schema for `/wallet/transaction/list`
    pub fn new(transactions: Vec<models::WalletTransaction>, request_id: String) -> WalletTransactionListResponse {
        WalletTransactionListResponse {
            transactions,
            next_cursor: None,
            request_id,
        }
    }
}

