/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * The version of the OpenAPI document: 2020-09-14_1.688.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WalletTransactionPayeeVerificationStatus : Result of payee verification check for EUR payouts. Payee verification checks whether the payee name provided matches the account holder name at the destination institution.  `FULL_MATCH`: The payee name fully matches the account holder.  `PARTIAL_MATCH`: The payee name partially matches the account holder.  `NO_MATCH`: The payee name does not match the account holder.  `ERROR`: An error occurred during payee verification.  `CHECK_NOT_POSSIBLE`: Payee verification could not be performed.  This field is only populated for applicable EUR payout transactions and will be `null` for other transaction types.
/// Result of payee verification check for EUR payouts. Payee verification checks whether the payee name provided matches the account holder name at the destination institution.  `FULL_MATCH`: The payee name fully matches the account holder.  `PARTIAL_MATCH`: The payee name partially matches the account holder.  `NO_MATCH`: The payee name does not match the account holder.  `ERROR`: An error occurred during payee verification.  `CHECK_NOT_POSSIBLE`: Payee verification could not be performed.  This field is only populated for applicable EUR payout transactions and will be `null` for other transaction types.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WalletTransactionPayeeVerificationStatus {
    #[serde(rename = "FULL_MATCH")]
    FullMatch,
    #[serde(rename = "PARTIAL_MATCH")]
    PartialMatch,
    #[serde(rename = "NO_MATCH")]
    NoMatch,
    #[serde(rename = "ERROR")]
    Error,
    #[serde(rename = "CHECK_NOT_POSSIBLE")]
    CheckNotPossible,

}

impl std::fmt::Display for WalletTransactionPayeeVerificationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FullMatch => write!(f, "FULL_MATCH"),
            Self::PartialMatch => write!(f, "PARTIAL_MATCH"),
            Self::NoMatch => write!(f, "NO_MATCH"),
            Self::Error => write!(f, "ERROR"),
            Self::CheckNotPossible => write!(f, "CHECK_NOT_POSSIBLE"),
        }
    }
}

impl Default for WalletTransactionPayeeVerificationStatus {
    fn default() -> WalletTransactionPayeeVerificationStatus {
        Self::FullMatch
    }
}

